'\" t
.\"     Title: sss_usermod
.\"    Author: The SSSD upstream - https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: SSSD-Handbuchseiten
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_USERMOD" "8" "12/09/2020" "SSSD" "SSSD-Handbuchseiten"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_usermod \- ändert ein Benutzerkonto
.SH "SYNOPSIS"
.HP \w'\fBsss_usermod\fR\ 'u
\fBsss_usermod\fR [\fIOptionen\fR] \fIANMELDUNG\fR
.SH "BESCHREIBUNG"
.PP
\fBsss_usermod\fR
ändert das durch
\fIANMELDUNG\fR
angegebene Konto, damit es die auf der Befehlszeile angegebenen Änderungen widerzuspiegelt\&.
.SH "OPTIONEN"
.PP
\fB\-c\fR,\fB\-\-gecos\fR \fIKOMMENTAR\fR
.RS 4
irgendeine Zeichenkette, die den Benutzer beschreibt\&. Dieses Feld wird oft für den vollständigen Namen des Benutzers verwendet\&.
.RE
.PP
\fB\-h\fR,\fB\-\-home\fR \fIHOME_VERZ\fR
.RS 4
das Home\-Verzeichnis des Benutzerkontos
.RE
.PP
\fB\-s\fR,\fB\-\-shell\fR \fISHELL\fR
.RS 4
die Anmelde\-Shell des Benutzers
.RE
.PP
\fB\-a\fR,\fB\-\-append\-group\fR \fIGRUPPEN\fR
.RS 4
hängt diesen Benutzer an die Gruppen an, die durch den Parameter
\fIGRUPPEN\fR
angegeben werden\&. Der Parameter
\fIGRUPPEN\fR
ist eine durch Kommata getrennte Liste von Gruppennamen\&.
.RE
.PP
\fB\-r\fR,\fB\-\-remove\-group\fR \fIGRUPPEN\fR
.RS 4
entfernt diesen Benutzer aus Gruppen, die durch den Parameter
\fIGRUPPEN\fR
angegeben werden\&.
.RE
.PP
\fB\-l\fR,\fB\-\-lock\fR
.RS 4
sperrt das Benutzerkonto\&. Der Benutzer wird sich nicht anmelden können\&.
.RE
.PP
\fB\-u\fR,\fB\-\-unlock\fR
.RS 4
entsperrt das Benutzerkonto\&.
.RE
.PP
\fB\-Z\fR,\fB\-\-selinux\-user\fR \fISELINUX_BENUTZER\fR
.RS 4
der SELinux\-Benutzer für die Anmeldung des Anwenders
.RE
.PP
\fB\-\-addattr\fR \fIATTR_NAME_WERT\fR
.RS 4
Ein Attribut/Wert\-Paar hinzufügen\&. Das Format ist Attributname=Wert\&.
.RE
.PP
\fB\-\-setattr\fR \fIATTR_NAME_WERT\fR
.RS 4
Ein Attribut auf ein Name/Wert\-Paar setzen\&. Das Format ist Attributname=Wert\&. Bei Attributen mit mehreren Werten ersetzt der Befehl die bereits vorhandenen Werte\&.
.RE
.PP
\fB\-\-delattr\fR \fIATTR_NAME_WERT\fR
.RS 4
Ein Attribut/Wert\-Paar löschen\&. Das Format ist Attributname=Wert\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
zeigt den Hilfetext und beendet sich\&.
.RE
.SH "DIE LOKALE DOMAIN"
.PP
Für korrektes Funktionieren muss eine Domain mit \(Fcid_provider=local\(Fo erstellt sein und SSSD muss laufen\&.
.PP
Möglicherweise möchte der Administrator in Fällen, in denen Gruppenverschachtelung (siehe
\fBsss_groupadd\fR(8)) benötigt wird, lokale Benutzer anstelle traditioneller UNIX\-Benutzer verwenden\&. Die lokalen Benutzer sind auch für das Testen und Entwickeln von SSSD nützlich, ohne dass ein vollständiger ferner Server bereitgestellt werden muss\&. Die
\fBsss_user*\fR\- und
\fBsss_group*\fR\-Werkzeuge benutzen einen lokalen LDB\-Speicher, um Benutzer und Gruppen abzulegen\&.
.SH "SIEHE AUCH"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \-
https://pagure\&.io/SSSD/sssd/\fR
