'\" t
.\"     Title: sss_groupmod
.\"    Author: The SSSD upstream - https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Pàgines del manual de l'SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_GROUPMOD" "8" "12/09/2020" "SSSD" "Pàgines del manual de l'SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_groupmod \- modifica un grup
.SH "SYNOPSIS"
.HP \w'\fBsss_groupmod\fR\ 'u
\fBsss_groupmod\fR [\fIopcions\fR] \fIGRUP\fR
.SH "DESCRIPCIÓ"
.PP
\fBsss_groupmod\fR
modifica el grup per reflectir els canvis que s\*(Aqespecifiquen a la línia d\*(Aqordres\&.
.SH "OPCIONS"
.PP
\fB\-a\fR,\fB\-\-append\-group\fR \fIGRUPS\fR
.RS 4
Afegeix aquest grup als grups especificats amb el paràmetre
\fIGRUPS\fR\&. El paràmetre
\fIGRUPS\fR
és una llista delimitada per comes dels noms dels grups\&.
.RE
.PP
\fB\-r\fR,\fB\-\-remove\-group\fR \fIGRUPS\fR
.RS 4
Suprimeix aquest grup dels grups especificats amb el paràmetre
\fIGRUPS\fR\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
Mostra el missatge d\*(Aqajuda i surt\&.
.RE
.SH "EL DOMINI LOCAL"
.PP
Per a un funcionament correcte, s\*(Aqha de crear un domini amb
\(lqid_provider=local\(rq
i l\*(AqSSSD ha d\*(Aqestar en execució\&.
.PP
L\*(Aqadministrador pot ser que vulgui utilitzar els usuaris locals de l\*(AqSSSD en lloc dels usuaris tradicionals d\*(AqUNIX en els casos en què es requereixi la imbricació dels grups (vegeu
\fBsss_groupadd\fR(8))\&. Els usuaris locals també són útils per provar i desplegar l\*(AqSSSD sense haver de desplegar tot un servidor remot\&. Les eines
\fBsss_user*\fR
i
\fBsss_group*\fR
utilitzen l\*(Aqemmagatzematge LDB local per emmagatzemar els usuaris i els grups\&.
.SH "VEGEU TAMBÉ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \-
https://pagure\&.io/SSSD/sssd/\fR
