'\" t
.\"     Title: sss_usermod
.\"    Author: The SSSD upstream - https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: SSSD マニュアル ページ
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_USERMOD" "8" "12/09/2020" "SSSD" "SSSD マニュアル ページ"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_usermod \- ユーザーアカウントを修正します
.SH "SYNOPSIS"
.HP \w'\fBsss_usermod\fR\ 'u
\fBsss_usermod\fR [\fIoptions\fR] \fILOGIN\fR
.SH "概要"
.PP
\fBsss_usermod\fR
は、コマンドラインにおいて指定された変更を反映するために、
\fILOGIN\fR
により指定されたアカウントを変更します。
.SH "オプション"
.PP
\fB\-c\fR,\fB\-\-gecos\fR \fICOMMENT\fR
.RS 4
ユーザーを説明している任意のテキスト文字列です。しばしばユーザーの完全名の項目として使用されます。
.RE
.PP
\fB\-h\fR,\fB\-\-home\fR \fIHOME_DIR\fR
.RS 4
ユーザーアカウントのホームディレクトリーです。
.RE
.PP
\fB\-s\fR,\fB\-\-shell\fR \fISHELL\fR
.RS 4
ユーザーのログインシェルです。
.RE
.PP
\fB\-a\fR,\fB\-\-append\-group\fR \fIGROUPS\fR
.RS 4
このユーザーを
\fIGROUPS\fR
パラメーターにより指定されたグループに追加します。
\fIGROUPS\fR
パラメーターはグループ名のカンマ区切り一覧です。
.RE
.PP
\fB\-r\fR,\fB\-\-remove\-group\fR \fIGROUPS\fR
.RS 4
\fIGROUPS\fR
.RE
.PP
\fB\-l\fR,\fB\-\-lock\fR
.RS 4
ユーザーアカウントをロックします。ユーザーはログインできなくなります。
.RE
.PP
\fB\-u\fR,\fB\-\-unlock\fR
.RS 4
ユーザーアカウントのロックを解除します。
.RE
.PP
\fB\-Z\fR,\fB\-\-selinux\-user\fR \fISELINUX_USER\fR
.RS 4
ユーザーのログインのための SELinux ユーザーです。
.RE
.PP
\fB\-\-addattr\fR \fIATTR_NAME_VAL\fR
.RS 4
Add an attribute/value pair\&. The format is attrname=value\&.
.RE
.PP
\fB\-\-setattr\fR \fIATTR_NAME_VAL\fR
.RS 4
Set an attribute to a name/value pair\&. The format is attrname=value\&. For multi\-valued attributes, the command replaces the values already present
.RE
.PP
\fB\-\-delattr\fR \fIATTR_NAME_VAL\fR
.RS 4
Delete an attribute/value pair\&. The format is attrname=value\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
ヘルプメッセージを表示して終了します。
.RE
.SH "ローカルドメイン"
.PP
In order to function correctly, a domain with
\(lqid_provider=local\(rq
must be created and the SSSD must be running\&.
.PP
The administrator might want to use the SSSD local users instead of traditional UNIX users in cases where the group nesting (see
\fBsss_groupadd\fR(8)) is needed\&. The local users are also useful for testing and development of the SSSD without having to deploy a full remote server\&. The
\fBsss_user*\fR
and
\fBsss_group*\fR
tools use a local LDB storage to store users and groups\&.
.SH "関連項目"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \-
https://pagure\&.io/SSSD/sssd/\fR
