'\" t
.\"     Title: sssd-simple
.\"    Author: The SSSD upstream - https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: ファイル形式および変換
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-SIMPLE" "5" "12/09/2020" "SSSD" "ファイル形式および変換"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-simple \- SSSD の \*(Aqsimple\*(Aq アクセス制御プロバイダーの設定ファイルです。
.SH "概要"
.PP
このマニュアルは
\fBsssd\fR(8)
に対して簡単なアクセス制御の設定を説明しています。詳細は
\fBsssd.conf\fR(5)
マニュアルページの
\(lqファイル形式\(rq
セクションを参照してください。
.PP
シンプルアクセスプロバイダーは、ユーザー名またはグループ名のアクセスまたは拒否の一覧に基づいてアクセスを許可または拒否します。以下の例を適用します:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
すべての一覧が空白ならば、アクセスが認められます
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
何らかの一覧が提供されていると、許可（allow）、拒否（deny）の順に評価されます。拒否ルールに一致するすべてのものは、許可ルールに一致するすべてのものを更新することを意味します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
"allow" 一覧が提供されていると、すべてのユーザーはこの一覧に表れなければ拒否されます。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
"deny" 一覧のみが提供されていると、ユーザーがこの一覧に表れない限り、すべてのユーザーがアクセスを許可されます。
.RE
.sp
.SH "設定オプション"
.PP
SSSD ドメインの設定に関する詳細は
\fBsssd.conf\fR(5)
マニュアルページの
\(lqドメインセクション\(rq
のセクションを参照してください。
.PP
simple_allow_users (文字列)
.RS 4
ログインが許可されたユーザーのカンマ区切り一覧です。
.RE
.PP
simple_deny_users (文字列)
.RS 4
アクセスが明示的に拒否されたユーザーのカンマ区切り一覧です。
.RE
.PP
simple_allow_groups (文字列)
.RS 4
ログインが許可されたグループのカンマ区切り一覧です。この SSSD ドメインの中のグループのみに適用されます。ローカルグループは評価されません。
.RE
.PP
simple_deny_groups (文字列)
.RS 4
アクセスが明示的に拒否されたグループのカンマ区切り一覧です。この SSSD ドメインの中のグループのみに適用されます。ローカルグループは評価されません。
.RE
.PP
Specifying no values for any of the lists is equivalent to skipping it entirely\&. Beware of this while generating parameters for the simple provider using automated scripts\&.
.PP
simple_allow_users と simple_deny_users がどちらも定義されると、設定エラーになることに注意してください。
.SH "例"
.PP
以下の例は、SSSD が正しく設定され、example\&.com が
\fI[sssd]\fR
セクションにあるドメインの 1 つであると仮定します。この例はアクセスプロバイダー固有の簡単なオプションのみを示します。
.PP
.if n \{\
.RS 4
.\}
.nf
[domain/example\&.com]
access_provider = simple
simple_allow_users = user1, user2
.fi
.if n \{\
.RE
.\}
.sp
.SH "注記"
.PP
The complete group membership hierarchy is resolved before the access check, thus even nested groups can be included in the access lists\&. Please be aware that the
\(lqldap_group_nesting_level\(rq
option may impact the results and should be set to a sufficient value\&. (\fBsssd-ldap\fR(5)) option\&.
.SH "関連項目"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \-
https://pagure\&.io/SSSD/sssd/\fR
