'\" t
.\"     Title: sss_rpcidmapd
.\"    Author: Noam Meltzer
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: File Formats and Conventions
.\"    Source: sss rpc.idmapd plugin
.\"  Language: English
.\"
.TH "SSS_RPCIDMAPD" "5" "12/09/2020" "sss rpc.idmapd plugin" "File Formats and Conventions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_rpcidmapd \- sss plugin configuration directives for rpc\&.idmapd
.SH "CONFIGURATION FILE"
.PP
rpc\&.idmapd configuration file is usually found at
\fI/etc/idmapd\&.conf\fR\&. See
\fBidmapd.conf\fR(5)
for more information\&.
.SH "SSS CONFIGURATION EXTENSION"
.SS "Enable SSS plugin"
.PP
In section
\(lq[Translation]\(rq, modify/set
\(lqMethod\(rq
attribute to contain
\fIsss\fR\&.
.SS "[sss] config section"
.PP
In order to change the default of one of the configuration attributes of the
\fIsss\fR
plugin listed below you will need to create a config section for it, named
\(lq[sss]\(rq\&.
.PP
\fBConfiguration attributes\fR
.PP
memcache (bool)
.RS 4
Indicates whether or not to use memcache optimisation technique\&.
.sp
Default: True
.RE
.SH "SSSD INTEGRATION"
.PP
The sss plugin requires the
\fINSS Responder\fR
to be enabled in sssd\&.
.PP
The attribute
\(lquse_fully_qualified_names\(rq
must be enabled on all domains (NFSv4 clients expect a fully qualified name to be sent on the wire)\&.
.SH "EXAMPLE"
.PP
The following example shows a minimal idmapd\&.conf which makes use of the sss plugin\&.
.sp
.if n \{\
.RS 4
.\}
.nf
[General]
Verbosity = 2
# domain must be synced between NFSv4 server and clients
# Solaris/Illumos/AIX use "localdomain" as default!
Domain = default

[Mapping]
Nobody\-User = nfsnobody
Nobody\-Group = nfsnobody

[Translation]
Method = sss
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
\fBsssd\fR(8),
\fBidmapd.conf\fR(5)
.SH "AUTHORS"
.PP
\fBNoam Meltzer\fR
.br
Primary Data Inc\&.
.RS 4
Developer (2013\-2014)
.RE
.PP
\fBNoam Meltzer\fR <\&tsnoam@gmail\&.com\&>
.RS 4
Developer (2014\-)
.RE
