'\" t
.\"     Title: sss_obfuscate
.\"    Author: The SSSD upstream - https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Pages de manuel de SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_OBFUSCATE" "8" "12/09/2020" "SSSD" "Pages de manuel de SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_obfuscate \- obscurcir un mot de passe en clair
.SH "SYNOPSIS"
.HP \w'\fBsss_obfuscate\fR\ 'u
\fBsss_obfuscate\fR [\fIoptions\fR] \fI[PASSWORD]\fR
.SH "DESCRIPTION"
.PP
\fBsss_obfuscate\fR
convertit un mot de passe donné en un format illisible par un humain et le place dans la section de domaine appropriée du fichier de configuration SSSD\&.
.PP
Le mot de passe en clair est lu dans l\*(Aqentrée standard ou entré interactivement\&. Les mots de passes chiffrés sont mis dans
\(lqldap_default_authtok\(rq
pour un domaine SSSD donné et le paramètre
\(lqldap_default_authtok_type\(rq
est défini à
\(lqobfuscated_password\(rq\&. Cf\&.
\fBsssd-ldap\fR(5)
pour plus de détails sur ces paramètres\&.
.PP
Veuillez noter que les mots de passe chiffrés ne fournissent
\fIaucun réel bénéfice de sécurité\fR
étant donné qu\*(Aqil est possible de retrouver le mot de passe par ingénierie\-inverse\&. Utiliser un meilleur mécanisme d\*(Aqauthentification tel que les certificats côté client ou GSSAPI est
\fItrès\fR
conseillé\&.
.SH "OPTIONS"
.PP
\fB\-h\fR,\fB\-\-help\fR
.RS 4
Affiche l\*(Aqaide et quitte\&.
.RE
.PP
\fB\-s\fR,\fB\-\-stdin\fR
.RS 4
Le mot de passe chiffré sera lu sur l\*(Aqentrée standard\&.
.RE
.PP
\fB\-d\fR,\fB\-\-domain\fR \fIDOMAINE\fR
.RS 4
Le domaine SSSD auquel est lié le mot de passe\&. Le nom par défaut est
\(lqdefault\(rq\&.
.RE
.PP
\fB\-f\fR,\fB\-\-file\fR \fIFICHIER\fR
.RS 4
Lit le fichier de configuration spécifié par le paramètre\&.
.sp
Par défaut :
/etc/sssd/sssd\&.conf
.RE
.SH "VOIR AUSSI"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \-
https://pagure\&.io/SSSD/sssd/\fR
