'\" t
.\"     Title: sss_userdel
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_USERDEL" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_userdel \- вилучення облікового запису користувача
.SH "SYNOPSIS"
.HP \w'\fBsss_userdel\fR\ 'u
\fBsss_userdel\fR [\fIпараметри\fR] \fIНАЗВА_ОБЛІКОВОГО_ЗАПИСУ\fR
.SH "ОПИС"
.PP
\fBsss_userdel\fR
вилучає обліковий запис користувача
\fIІМ\(cqЯ_КОРИСТУВАЧА\fR
з системи\&.
.SH "ПАРАМЕТРИ"
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-r\fR,\fB\-\-remove\fR
.RS 4
Файли у домашньому каталозі користувача буде вилучено разом з самим домашнім каталогом та поштовим буфером користувача\&. Може бути перевизначено у налаштуваннях\&.
.RE
.PP
\fB\-R\fR,\fB\-\-no\-remove\fR
.RS 4
Файли у домашньому каталозі користувача НЕ буде вилучено разом з самим домашнім каталогом та поштовим буфером користувача\&. Може бути перевизначено у налаштуваннях\&.
.RE
.PP
\fB\-f\fR,\fB\-\-force\fR
.RS 4
За допомогою цього параметра можна примусити
\fBsss_userdel\fR
вилучати домашній каталог користувача та буфер пошти, навіть якщо їхнім власником не є вказаний користувач\&.
.RE
.PP
\fB\-k\fR,\fB\-\-kick\fR
.RS 4
До вилучення запису користувача завершити роботу всіх процесів, власником яких є цей користувач\&.
.RE
.SH "ЛОКАЛЬНИЙ ДОМЕН"
.PP
З метою забезпечення належної роботи слід створити домен з
\(lqid_provider=local\(rq
та запустити SSSD\&.
.PP
Адміністратор може надати перевагу використанню локальних записів користувачів SSSD замість традиційних записів користувачів UNIX, якщо для роботи потрібна вкладеність груп (див\&.
\fBsss_groupadd\fR(8))\&. Використання локальних записів може також бути корисним для тестування та розробки програмного забезпечення з підтримкою SSSD (у такому разі не потрібно розгортати повноцінний віддалений сервер)\&. Інструменти
\fBsss_user*\fR
та
\fBsss_group*\fR
використовують для зберігання записів користувачів і груп локальне сховище даних LDB\&.
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
