'\" t
.\"     Title: sss_seed
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_SEED" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_seed \- надсилає дані кешу SSSD щодо користувача
.SH "SYNOPSIS"
.HP \w'\fBsss_seed\fR\ 'u
\fBsss_seed\fR [\fIпараметри\fR] \-D\ \fIДОМЕН\fR \-n\ \fIКОРИСТУВАЧ\fR
.SH "ОПИС"
.PP
\fBsss_seed\fR
розповсюджує кеш SSSD з записом користувача і тимчасовим паролем\&. Якщо запис користувача вже є у кеші SSSD, запис буде оновлено зі встановленням тимчасового пароля\&.
.PP
.SH "ПАРАМЕТРИ"
.PP
\fB\-D\fR,\fB\-\-domain\fR \fIДОМЕН\fR
.RS 4
Визначає назву домену, учасником якого є користувач\&. Домен використовується для отримання даних щодо користувачів\&. Домен має бути налаштовано у sssd\&.conf\&. Має бути надано аргумент
\fIДОМЕН\fR\&. Дані, отримані з домену, матимуть вищий пріоритет за дані, вказані за допомогою параметрів\&.
.RE
.PP
\fB\-n\fR,\fB\-\-username\fR \fIКОРИСТУВАЧ\fR
.RS 4
Ім\(cqя користувача, запис якого слід створити або змінити у кеші\&. Має бути вказано аргумент
\fIКОРИСТУВАЧ\fR\&.
.RE
.PP
\fB\-u\fR,\fB\-\-uid\fR \fIідентифікатор користувача\fR
.RS 4
Встановити UID користувача у значення
\fIUID\fR\&.
.RE
.PP
\fB\-g\fR,\fB\-\-gid\fR \fIGID\fR
.RS 4
Встановити GID користувача у значення
\fIGID\fR\&.
.RE
.PP
\fB\-c\fR,\fB\-\-gecos\fR \fIКОМЕНТАР\fR
.RS 4
Будь\-який рядок тексту, що описує користувача\&. Часто використовується для зберігання паспортного імені користувача\&.
.RE
.PP
\fB\-h\fR,\fB\-\-home\fR \fIДОМАШНІЙ_КАТАЛОГ\fR
.RS 4
Встановити домашній каталог користувача у значення
\fIДОМАШНІЙ_КАТАЛОГ\fR\&.
.RE
.PP
\fB\-s\fR,\fB\-\-shell\fR \fIОБОЛОНКА\fR
.RS 4
Встановити оболонку реєстрації користувача у значення
\fIОБОЛОНКА\fR\&.
.RE
.PP
\fB\-i\fR,\fB\-\-interactive\fR
.RS 4
Інтерактивний режим для введення даних користувача\&. У разі використання цього параметра програма надсилатиме запит лише щодо даних, які не було отримано з параметрів команди або домену\&.
.RE
.PP
\fB\-p\fR,\fB\-\-password\-file\fR \fIФАЙЛ_ПАРОЛІВ\fR
.RS 4
Вказати файл, звідки слід читати дані щодо паролів користувачів\&. Якщо пароль не буде знайдено, програма надішле запит на його введення\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.SH "ЗАУВАЖЕННЯ"
.PP
Довжина пароля (або розмір файла, визначеного за допомогою параметра \-p або \-\-password\-file) має бути меншою або рівною PASS_MAX байтів (64 байти у системах без визначеного на загальному рівні значення PASS_MAX)\&.
.PP
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
