'\" t
.\"     Title: sss_useradd
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_USERADD" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_useradd \- створення нового запису користувача
.SH "SYNOPSIS"
.HP \w'\fBsss_useradd\fR\ 'u
\fBsss_useradd\fR [\fIпараметри\fR] \fIНАЗВА_ОБЛІКОВОГО_ЗАПИСУ\fR
.SH "ОПИС"
.PP
\fBsss_useradd\fR
створює обліковий запис користувача на основі значень, вказаних у командному рядку та типових значень системи\&.
.SH "ПАРАМЕТРИ"
.PP
\fB\-u\fR,\fB\-\-uid\fR \fIідентифікатор користувача\fR
.RS 4
Встановити для параметра ідентифікатора користувача (UID) значення
\fIUID\fR\&. Якщо таке значення не буде вказано, програма вибере його автоматично\&.
.RE
.PP
\fB\-c\fR,\fB\-\-gecos\fR \fIКОМЕНТАР\fR
.RS 4
Будь\-який рядок тексту, що описує користувача\&. Часто використовується для зберігання паспортного імені користувача\&.
.RE
.PP
\fB\-h\fR,\fB\-\-home\fR \fIДОМАШНІЙ_КАТАЛОГ\fR
.RS 4
Домашній каталог облікового запису користувача\&. Типовою назвою такого каталогу є назва, що утворюється додаванням
\fIІМЕНІ_КОРИСТУВАЧА\fR
до запису
/home\&. Рядок, який буде додано перед
\fIІМЕНЕМ_КОРИСТУВАЧА\fR, можна визначити за допомогою параметра \(Fouser_defaults/baseDirectory\(Fc у sssd\&.conf\&.
.RE
.PP
\fB\-s\fR,\fB\-\-shell\fR \fIОБОЛОНКА\fR
.RS 4
Командна оболонка реєстрації користувача\&. У поточній версії типовою оболонкою є
/bin/bash\&. Типову оболонку можна змінити за допомогою параметра \(Fouser_defaults/defaultShell\(Fc у sssd\&.conf\&.
.RE
.PP
\fB\-G\fR,\fB\-\-groups\fR \fIГРУПИ\fR
.RS 4
Список груп, учасником яких є користувач\&.
.RE
.PP
\fB\-m\fR,\fB\-\-create\-home\fR
.RS 4
Створити домашній каталог користувача, якщо такого ще не існує\&. До такого домашнього каталогу буде скопійовано файли і каталоги з каркасного каталогу (який можна визначити за допомогою параметра \-k або запису у файлі налаштувань)\&.
.RE
.PP
\fB\-M\fR,\fB\-\-no\-create\-home\fR
.RS 4
Не створювати домашнього каталогу користувача\&. Має пріоритет над іншими параметрами налаштування\&.
.RE
.PP
\fB\-k\fR,\fB\-\-skel\fR \fIКАТАЛОГ_SKEL\fR
.RS 4
Каркасний каталог, який містить файли і каталоги, які буде скопійовано до домашнього каталогу користувача, коли такий домашній каталог створюється командою
\fBsss_useradd\fR\&.
.sp
Спеціальні файли (блокові пристрої, символьні пристрої, іменовані канали та сокети UNIX) скопійовано не буде\&.
.sp
Цей параметр набуде чинності, лише якщо вказано параметр
\fB\-m\fR
(або
\fB\-\-create\-home\fR) або для створення домашніх каталогів вказано TRUE у налаштуваннях\&.
.RE
.PP
\fB\-Z\fR,\fB\-\-selinux\-user\fR \fIКОРИСТУВАЧ_SELINUX\fR
.RS 4
Користувач SELinux, що відповідає користувачеві, який увійшов до системи\&. Якщо не вказано, буде використано типового користувача системи\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.SH "ЛОКАЛЬНИЙ ДОМЕН"
.PP
З метою забезпечення належної роботи слід створити домен з
\(lqid_provider=local\(rq
та запустити SSSD\&.
.PP
Адміністратор може надати перевагу використанню локальних записів користувачів SSSD замість традиційних записів користувачів UNIX, якщо для роботи потрібна вкладеність груп (див\&.
\fBsss_groupadd\fR(8))\&. Використання локальних записів може також бути корисним для тестування та розробки програмного забезпечення з підтримкою SSSD (у такому разі не потрібно розгортати повноцінний віддалений сервер)\&. Інструменти
\fBsss_user*\fR
та
\fBsss_group*\fR
використовують для зберігання записів користувачів і груп локальне сховище даних LDB\&.
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
