'\" t
.\"     Title: sss_cache
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_CACHE" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_cache \- виконати спорожнення кешу
.SH "SYNOPSIS"
.HP \w'\fBsss_cache\fR\ 'u
\fBsss_cache\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
\fBsss_cache\fR
скасовує визначення записів у кеші SSSD\&. Дані записів зі скасованими визначеннями буде перезавантажено з сервера у примусовому порядку, щойно відповідний модуль SSSD отримає до них доступ\&. Параметри, які скасовують визначення окремого об\*(Aqєкта приймають лише один аргумент\&.
.SH "ПАРАМЕТРИ"
.PP
\fB\-E\fR,\fB\-\-everything\fR
.RS 4
Скасувати чинність усіх кешованих записів\&.
.RE
.PP
\fB\-u\fR,\fB\-\-user\fR \fIреєстраційні дані\fR
.RS 4
Скасувати визначення вказаного користувача\&.
.RE
.PP
\fB\-U\fR,\fB\-\-users\fR
.RS 4
Скасувати визначення всіх записів\&. Цей параметр має вищий пріоритет за параметр скасування визначення для будь\-якого користувача, якщо такий параметр вказано\&.
.RE
.PP
\fB\-g\fR,\fB\-\-group\fR \fIгрупа\fR
.RS 4
Скасувати визначення вказаної групи\&.
.RE
.PP
\fB\-G\fR,\fB\-\-groups\fR
.RS 4
Скасувати визначення записів для всіх груп\&. Цей параметр має вищий пріоритет за параметр скасування визначення для будь\-якої групи, якщо такий параметр вказано\&.
.RE
.PP
\fB\-n\fR,\fB\-\-netgroup\fR \fIмережева група\fR
.RS 4
Скасувати визначення вказаної мережевої групи\&.
.RE
.PP
\fB\-N\fR,\fB\-\-netgroups\fR
.RS 4
Скасувати визначення всіх записів мережевих груп\&. Цей параметр має вищий пріоритет за параметр скасування визначення для будь\-якої мережевої групи, якщо такий параметр вказано\&.
.RE
.PP
\fB\-s\fR,\fB\-\-service\fR \fIслужба\fR
.RS 4
Скасувати визначення вказаної служби\&.
.RE
.PP
\fB\-S\fR,\fB\-\-services\fR
.RS 4
Скасувати визначення всіх записів служб\&. Цей параметр має вищий пріоритет за параметр скасування визначення для будь\-якої служби, якщо такий параметр вказано\&.
.RE
.PP
\fB\-a\fR,\fB\-\-autofs\-map\fR \fIкарта autofs\fR
.RS 4
Скасувати визначення певної карти autofs\&.
.RE
.PP
\fB\-A\fR,\fB\-\-autofs\-maps\fR
.RS 4
Скасувати визначення всіх записів карт autofs\&. Цей параметр має вищий пріоритет за параметр скасування визначення для будь\-якої карти, якщо такий параметр вказано\&.
.RE
.PP
\fB\-h\fR,\fB\-\-ssh\-host\fR \fIназва вузла\fR
.RS 4
Скасувати чинність відкритих ключів SSH певного вузла\&.
.RE
.PP
\fB\-H\fR,\fB\-\-ssh\-hosts\fR
.RS 4
Скасувати чинність усіх відкритих ключів SSH усіх вузлів\&. Цей параметр перевизначає скасовування чинності ключів SSH певних вузлів, якщо для них було використано таке скасовування\&.
.RE
.PP
\fB\-r\fR,\fB\-\-sudo\-rule\fR \fIправило\fR
.RS 4
Скасувати чинність певного правила sudo\&.
.RE
.PP
\fB\-R\fR,\fB\-\-sudo\-rules\fR
.RS 4
Скасувати визначення усіх кешованих правил sudo\&. Цей параметр має вищий пріоритет за параметр скасування визначення для будь\-якого правила sudo, якщо такий параметр вказано\&.
.RE
.PP
\fB\-d\fR,\fB\-\-domain\fR \fIдомен\fR
.RS 4
Обмежити процедуру скасування визначення лише певним доменом\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
