'\" t
.\"     Title: sss_override
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_OVERRIDE" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_override \- створити локальні перевизначення атрибутів користувача і групи
.SH "SYNOPSIS"
.HP \w'\fBsss_override\fR\ 'u
\fBsss_override\fR \fIКОМАНДА\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
\fBsss_override\fR
надає змогу створювати перегляди на боці клієнта і змінювати вибрані значення для певного користувача і груп\&. Ці зміни буде застосовано лише на локальному комп\*(Aqютері\&.
.PP
Дані перевизначень зберігаються у кеші SSSD\&. Якщо кеш вилучено, усі локальні перевизначення буде втрачено\&. Будь ласка, зауважте, що після першого створення перевизначення за допомогою команди
\fIuser\-add\fR,
\fIgroup\-add\fR,
\fIuser\-import\fR
або
\fIgroup\-import\fR
SSSD слід перезапустити, щоб зміни набули чинності\&. Якщо потрібен перезапуск,
\fIsss_override\fR
виведе відповідне повідомлення\&.
.SH "ДОСТУПНІ КОМАНДИ"
.PP
Аргумент
\fIНАЗВА\fR
в усіх командах є назвою початкового об\*(Aqєкта\&. Не можна перевизначити
\fIuid\fR
або
\fIgid\fR
на 0\&.
.PP
\fBuser\-add\fR \fIНАЗВА\fR [\fB\-n,\-\-name\fR НАЗВА] [\fB\-u,\-\-uid\fR UID] [\fB\-g,\-\-gid\fR GID] [\fB\-h,\-\-home\fR ДОМІВКА] [\fB\-s,\-\-shell\fR ОБОЛОНКА] [\fB\-c,\-\-gecos\fR GECOS] [\fB\-x,\-\-certificate\fR СЕРТИФІКАТ У КОДУВАННІ BASE64]
.RS 4
Перевизначити атрибути запису користувача\&. Будь ласка, зверніть увагу, що виклик цієї команди замінить усі попередні перевизначення для вказаного за назвою облікового запису користувача\&.
.RE
.PP
\fBuser\-del\fR \fIНАЗВА\fR
.RS 4
Вилучити перевизначення користувача\&. Втім, слід мати на увазі, що перевизначені атрибути може бути повернено з кешу у пам\*(Aqяті\&. Будь ласка, ознайомтеся із документацією до параметра SSSD
\fImemcache_timeout\fR, щоб дізнатися більше\&.
.RE
.PP
\fBuser\-find\fR [\fB\-d,\-\-domain\fR ДОМЕН]
.RS 4
Вивести список усіх користувачів, для яких встановлено перевизначення\&. Якщо встановлено параметр
\fIДОМЕН\fR, буде показано лише користувачів з відповідного домену\&.
.RE
.PP
\fBuser\-show\fR \fIНАЗВА\fR
.RS 4
Показати перевизначення користувача\&.
.RE
.PP
\fBuser\-import\fR \fIФАЙЛ\fR
.RS 4
Імпортувати перевизначення користувачів з файла
\fIФАЙЛ\fR\&. Формат даних у файлі має бути таким самим, як у стандартному файлі passwd\&. Приклад:
.sp
початкова_назва:назва:uid:gid:gecos:домівка:оболонка:сертифікат_у_кодуванні_base64
.sp
де \(Foпочаткова_назва\(Fc \(em початкова назва запису користувача, чиї атрибути має бути перевизначено\&. Решта полів відповідає новим значенням\&. Ви можете пропустити значення, не заповнюючи відповідного поля\&.
.sp
Приклади:
.sp
ckent:superman::::::
.sp
ckent@krypton\&.com::501:501:Superman:/home/earth:/bin/bash:
.RE
.PP
\fBuser\-export\fR \fIФАЙЛ\fR
.RS 4
Експортувати усі перевизначені атрибути і зберегти їх у файлі
\fIФАЙЛ\fR\&. Див\&.
\fIuser\-import\fR, щоб дізнатися більше про формат даних\&.
.RE
.PP
\fBgroup\-add\fR \fIНАЗВА\fR [\fB\-n,\-\-name\fR НАЗВА] [\fB\-g,\-\-gid\fR GID]
.RS 4
Перевизначити атрибути запису групи\&. Будь ласка, зверніть увагу, що виклик цієї команди замінить усі попередні перевизначення для вказаної за назвою групи\&.
.RE
.PP
\fBgroup\-del\fR \fIНАЗВА\fR
.RS 4
Вилучити перевизначення групи\&. Втім, слід мати на увазі, що перевизначені атрибути може бути повернено з кешу у пам\*(Aqяті\&. Будь ласка, ознайомтеся із документацією до параметра SSSD
\fImemcache_timeout\fR, щоб дізнатися більше\&.
.RE
.PP
\fBgroup\-find\fR [\fB\-d,\-\-domain\fR ДОМЕН]
.RS 4
Вивести список усіх груп, для яких встановлено перевизначення\&. Якщо встановлено параметр
\fIДОМЕН\fR, буде показано лише групи з відповідного домену\&.
.RE
.PP
\fBgroup\-show\fR \fIНАЗВА\fR
.RS 4
Показати перевизначення групи\&.
.RE
.PP
\fBgroup\-import\fR \fIФАЙЛ\fR
.RS 4
Імпортувати перевизначення груп з файла
\fIФАЙЛ\fR\&. Формат даних у файлі має бути таким самим, як у стандартному файлі group\&. Приклад:
.sp
початкова_назва:назва:gid
.sp
де \(Foпочаткова_назва\(Fc \(em початкова назва групи, чиї атрибути має бути перевизначено\&. Решта полів відповідає новим значенням\&. Ви можете пропустити значення, не заповнюючи відповідного поля\&.
.sp
Приклади:
.sp
admins:administrators:
.sp
Domain Users:Users:501
.RE
.PP
\fBgroup\-export\fR \fIФАЙЛ\fR
.RS 4
Експортувати усі перевизначені атрибути і зберегти їх у файлі
\fIФАЙЛ\fR\&. Див\&.
\fIgroup\-import\fR, щоб дізнатися більше про формат даних\&.
.RE
.SH "ЗАГАЛЬНІ ПАРАМЕТРИ"
.PP
Ці параметри можна використовувати з усіма командами\&.
.PP
\fB\-\-debug\fR \fIРІВЕНЬ\fR
.RS 4
У SSSD передбачено два представлення для визначення рівня діагностики\&. Найпростішим є визначення десяткового значення у діапазоні 0\-9\&. Кожному значенню відповідає вмикання відповідного рівня діагностики і усіх нижчих рівнів\&. Точніше визначення вмикання або вимикання (якщо це потрібно) специфічних рівнів можна встановити за допомогою шістнадцяткової бітової маски\&.
.sp
Рівні діагностики, передбачені у поточній версії:
.sp
\fI0\fR,
\fI0x0010\fR: критичні помилки з аварійним завершенням роботи\&. Всі помилки, які не дають SSSD змоги розпочати або продовжувати роботу\&.
.sp
\fI1\fR,
\fI0x0020\fR: критичні помилки\&. Помилки, які не призводять до аварійного завершення роботи SSSD, але означають, що одна з основних можливостей не працює належним чином\&.
.sp
\fI2\fR,
\fI0x0040\fR: серйозні помилки\&. Повідомлення про такі помилки означають, що не вдалося виконати певний запит або дію\&.
.sp
\fI3\fR,
\fI0x0080\fR: незначні помилки\&. Це помилки які можуть призвести до помилок під час виконання дій\&.
.sp
\fI4\fR,
\fI0x0100\fR: параметри налаштування\&.
.sp
\fI5\fR,
\fI0x0200\fR: дані функцій\&.
.sp
\fI6\fR,
\fI0x0400\fR: повідомлення трасування для функцій дій\&.
.sp
\fI7\fR,
\fI0x1000\fR: повідомлення трасування для функцій внутрішнього трасування\&.
.sp
\fI8\fR,
\fI0x2000\fR: вміст внутрішніх змінних функцій, який може бути цікавим\&.
.sp
\fI9\fR,
\fI0x4000\fR: дані трасування найнижчого рівня\&.
.sp
Щоб до журналу було записано дані потрібних бітових масок рівнів діагностики, просто додайте відповідні числа, як це показано у наведених нижче прикладах:
.sp
\fIExample\fR: щоб до журналу було записано дані щодо критичних помилок з аварійним завершенням роботи, критичних помилок, серйозних помилок та дані функцій, скористайтеся рівнем діагностики 0x0270\&.
.sp
\fIПриклад\fR: щоб до журналу було записано критичні помилки з аварійним завершенням роботи, параметри налаштування, дані функцій та повідомлення трасування для функцій внутрішнього керування, скористайтеся рівнем 0x1310\&.
.sp
\fIЗауваження\fR: формат бітових масок для рівнів діагностики впроваджено у версії 1\&.7\&.0\&.
.sp
\fIТипове значення\fR: 0
.RE
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
