'\" t
.\"     Title: sssctl
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSCTL" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssctl \- Засіб керування і визначення стану SSSD
.SH "SYNOPSIS"
.HP \w'\fBsssctl\fR\ 'u
\fBsssctl\fR \fIКОМАНДА\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
\fBsssctl\fR
є простим і уніфікованим засобом отримання даних щодо стану SSSD, зокрема активного сервера, серверів автоматичного визначення, доменів і кешованих об\*(Aqєктів\&. Крім того, програма здатна керувати файлами даних SSSD для усування вад у такий спосіб, щоб з ними можна було безпечно працювати, доки працює SSSD\&.
.SH "ДОСТУПНІ КОМАНДИ"
.PP
Щоб ознайомитися зі списком усіх доступних команд, віддайте команду
\fBsssctl\fR
без параметрів\&. Щоб програма вивела довідкове повідомлення щодо певної команди, віддайте команду
\fBsssctl КОМАНДА \-\-help\fR\&.
.SH "ЗАГАЛЬНІ ПАРАМЕТРИ"
.PP
Ці параметри можна використовувати з усіма командами\&.
.PP
\fB\-\-debug\fR \fIРІВЕНЬ\fR
.RS 4
У SSSD передбачено два представлення для визначення рівня діагностики\&. Найпростішим є визначення десяткового значення у діапазоні 0\-9\&. Кожному значенню відповідає вмикання відповідного рівня діагностики і усіх нижчих рівнів\&. Точніше визначення вмикання або вимикання (якщо це потрібно) специфічних рівнів можна встановити за допомогою шістнадцяткової бітової маски\&.
.sp
Рівні діагностики, передбачені у поточній версії:
.sp
\fI0\fR,
\fI0x0010\fR: критичні помилки з аварійним завершенням роботи\&. Всі помилки, які не дають SSSD змоги розпочати або продовжувати роботу\&.
.sp
\fI1\fR,
\fI0x0020\fR: критичні помилки\&. Помилки, які не призводять до аварійного завершення роботи SSSD, але означають, що одна з основних можливостей не працює належним чином\&.
.sp
\fI2\fR,
\fI0x0040\fR: серйозні помилки\&. Повідомлення про такі помилки означають, що не вдалося виконати певний запит або дію\&.
.sp
\fI3\fR,
\fI0x0080\fR: незначні помилки\&. Це помилки які можуть призвести до помилок під час виконання дій\&.
.sp
\fI4\fR,
\fI0x0100\fR: параметри налаштування\&.
.sp
\fI5\fR,
\fI0x0200\fR: дані функцій\&.
.sp
\fI6\fR,
\fI0x0400\fR: повідомлення трасування для функцій дій\&.
.sp
\fI7\fR,
\fI0x1000\fR: повідомлення трасування для функцій внутрішнього трасування\&.
.sp
\fI8\fR,
\fI0x2000\fR: вміст внутрішніх змінних функцій, який може бути цікавим\&.
.sp
\fI9\fR,
\fI0x4000\fR: дані трасування найнижчого рівня\&.
.sp
Щоб до журналу було записано дані потрібних бітових масок рівнів діагностики, просто додайте відповідні числа, як це показано у наведених нижче прикладах:
.sp
\fIExample\fR: щоб до журналу було записано дані щодо критичних помилок з аварійним завершенням роботи, критичних помилок, серйозних помилок та дані функцій, скористайтеся рівнем діагностики 0x0270\&.
.sp
\fIПриклад\fR: щоб до журналу було записано критичні помилки з аварійним завершенням роботи, параметри налаштування, дані функцій та повідомлення трасування для функцій внутрішнього керування, скористайтеся рівнем 0x1310\&.
.sp
\fIЗауваження\fR: формат бітових масок для рівнів діагностики впроваджено у версії 1\&.7\&.0\&.
.sp
\fIТипове значення\fR: 0
.RE
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
