'\" t
.\"     Title: sssd-files
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Формати файлів та правила
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-FILES" "5" "12/09/2020" "SSSD" "Формати файлів та правила"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-files \- Засіб надання файлів SSSD
.SH "ОПИС"
.PP
На цій сторінці довідника описано налаштування засобу обробки файлів для
\fBsssd\fR(8)\&. Щоб дізнатися більше про синтаксис налаштування, зверніться до розділу \(FoФОРМАТ ФАЙЛА\(Fc сторінки довідника
\fBsssd.conf\fR(5)\&.
.PP
Засіб надання даних файлів створює дзеркальну копію вмісту файлів
\fBpasswd\fR(5)
і
\fBgroup\fR(5)\&. Метою роботи засобу надання даних файлів є забезпечення доступу до даних користувачів і груп, які традиційно доступні за допомогою інтерфейсів NSS, також за допомогою інтерфейсів SSSD, зокрема
\fBsssd-ifp\fR(5)\&.
.PP
Іншою причиною може бути потреба у забезпеченні ефективного кешування даних локальних користувачів і груп\&.
.PP
Будь ласка, зауважте, що у деяких дистрибутивах домен files увімкнено автоматично, оскільки цей домен додано до будь\-якого із явно визначених доменів\&. Див\&. enable_files_domain у
\fBsssd.conf\fR(5)\&.
.PP
SSSD ніколи не виконує визначення для користувача або групи \(Foroot\(Fc\&. Крім того, SSSD не обробляє запити щодо визначення UID/GID 0\&. Такі запити передаються наступному модулю NSS (зазвичай, files)\&.
.PP
Якщо SSSD не запущено або програма не відповідає, nss_sss повертає код UNAVAIL, що спричиняє передавання запиту наступному модулю\&.
.SH "ПАРАМЕТРИ НАЛАШТУВАННЯ"
.PP
Окрім параметрів із наведеного нижче списку, можна встановлювати, де це є відповідним, загальні параметри домену SSSD\&. Зверніться до розділу
\(lqРОЗДІЛИ ДОМЕНІВ\(rq
сторінки підручника
\fBsssd.conf\fR(5), щоб дізнатися більше про налаштовування домені SSSD\&. Втім, призначенням надавача даних files є надання тих самих даних, які встановлюються для файлів UNIX, просто за допомогою інтерфейсів SSSD\&. Тому передбачено підтримку не усіх загальних параметрів доменів\&. Так само, деякі загальні параметри, зокрема перевизначення командної оболонки у розділі
\(lqnss\(rq
для усіх доменів, ні на що не впливають у домені files, якщо їх не вказано явним чином для окремих доменів\&.
.PP
passwd_files (рядок)
.RS 4
Список з однієї чи декількох відокремлених комами назв файлів паролів, які слід прочитати і нумерувати засобу надання даних файлів\&. Для кожного вказаного файла буде встановлено спостереження за допомогою inotify для динамічного виявлення внесених до нього змін\&.
.sp
Типове значення: /etc/passwd
.RE
.PP
group_files (рядок)
.RS 4
Список з однієї чи декількох відокремлених комами назв файлів груп, які слід прочитати і нумерувати засобу надання даних файлів\&. Для кожного вказаного файла буде встановлено спостереження за допомогою inotify для динамічного виявлення внесених до нього змін\&.
.sp
Типове значення: /etc/group
.RE
.SH "ПРИКЛАД"
.PP
У наведеному нижче прикладі припускається, що SSSD налаштовано належним чином, а files встановлено на один з доменів з розділу
\fI[sssd]\fR\&.
.PP
.if n \{\
.RS 4
.\}
.nf
[domain/files]
id_provider = files
.fi
.if n \{\
.RE
.\}
.PP
Для балансування кешування даних локальних користувачів та груп у SSSD модуль nss_sss має перебувати у списку файла /etc/nsswitch\&.conf вище за модуль nss_files\&.
.PP
.if n \{\
.RS 4
.\}
.nf
passwd:     sss files
group:      sss files
.fi
.if n \{\
.RE
.\}
.sp
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
