'\" t
.\"     Title: sssd-session-recording
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Формати файлів та правила
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-SESSION\-RECOR" "5" "12/09/2020" "SSSD" "Формати файлів та правила"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-session-recording \- Налаштовування записів сеансів за допомогою SSSD
.SH "ОПИС"
.PP
На цій сторінці підручника описано налаштовування
\fBsssd\fR(8)
на роботу з
\fBtlog-rec-session\fR(8), частиною пакунка tlog, для реалізації записування сеансів користувачів у текстових терміналах\&. Докладний довідник щодо синтаксису налаштувань можна знайти у розділі
\(lqФОРМАТ ФАЙЛА\(rq
сторінки підручника з
\fBsssd.conf\fR(5)\&.
.PP
SSSD можна налаштувати так, щоб уможливити запис усіх даних, які бачать або вводять протягом сеансу у текстових терміналах вказані користувачі\&. Наприклад, можна записувати дані щодо входу користувачів за допомогою консолі або SSH\&. Сама SSSD нічого не записує, а лише забезпечує запуск tlog\-rec\-session під час входу до системи користувача, щоб можна було здійснювати запис відповідно до налаштувань\&.
.PP
Для користувачів, для яких увімкнено запис сеансів, SSSD замінює командну оболонку користувача на tlog\-rec\-session у відповідях NSS і додає змінну, яка вказує на початкову командну оболонку до середовища користувача у налаштування сеансу PAM\&. Таким чином забезпечується запуск tlog\-rec\-session замість командної оболонки користувача і надання даних про те, яку командну оболонку слід запустити, щойно розпочнеться записування\&.
.SH "ПАРАМЕТРИ НАЛАШТУВАННЯ"
.PP
Цими параметрами можна скористатися для налаштовування запису сеансів\&.
.PP
scope (рядок)
.RS 4
Один із вказаних нижче рядків, що визначають область запису сеансів:
.PP
"none"
.RS 4
Користувачі не записуються\&.
.RE
.PP
"some"
.RS 4
Запис вестиметься для користувачів і груп, вказаних параметрами
\fIкористувачі\fR
і
\fIгрупи\fR\&.
.RE
.PP
"all"
.RS 4
Усі користувачі записуються\&.
.RE
.sp
Типове значення: none
.RE
.PP
users (рядок)
.RS 4
Список відокремлених комами записів користувачів, для яких увімкнено записування сеансів\&. Належність до списку визначатиметься за іменами, повернутими NSS, тобто після можливих замін пробілів, змін регістру символів тощо\&.
.sp
Типове значення: порожнє\&. Не відповідає жодному користувачу\&.
.RE
.PP
groups (рядок)
.RS 4
Список відокремлених комами записів груп, для користувачів яких буде увімкнено записування сеансів\&. Належність до списку визначатиметься за назвами, повернутими NSS, тобто після можливих замін пробілів, змін регістру символів тощо\&.
.sp
Зауваження: використання цього параметра (встановлення для нього будь\-якого значення) значно впливає на швидкодію, оскільки некешований запит щодо користувача потребує отримання і встановлення відповідності груп, до яких належить користувач\&.
.sp
Типове значення: порожнє\&. Не відповідає жодній групі\&.
.RE
.SH "ПРИКЛАД"
.PP
У наведеному нижче фрагменті файла sssd\&.conf увімкнено запис сеансів для користувачів contractor1 і contractor2\(Fc та групи students\&.
.PP
.if n \{\
.RS 4
.\}
.nf
[session_recording]
scope = some
users = contractor1, contractor2
groups = students
.fi
.if n \{\
.RE
.\}
.sp
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
