'\" t
.\"     Title: sssd
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Сторінки підручника SSSD
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD" "8" "12/09/2020" "SSSD" "Сторінки підручника SSSD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd \- Фонова служба безпеки системи
.SH "SYNOPSIS"
.HP \w'\fBsssd\fR\ 'u
\fBsssd\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
У
\fBSSSD\fR
передбачено набір фонових служб для керування доступом до віддалених каталогів та механізмами розпізнавання\&.
\fBSSSD\fR
надає операційній системі інтерфейси NSS і PAM, а також систему придатних для під\(cqєднання модулів для встановлення з\(cqєднання з декількома різними джерелами даних щодо облікових записів та інтерфейс D\-Bus\&.
\fBSSSD\fR
також є основою для систем перевірки клієнтських систем та служб обслуговування правил доступу для проєктів, подібних до FreeIPA\&.
\fBSSSD\fR
надає стійкішу базу даних для збереження записів локальних користувачів, а також додаткових даних щодо користувачів\&.
.SH "ПАРАМЕТРИ"
.PP
\fB\-d\fR,\fB\-\-debug\-level\fR \fIРІВЕНЬ\fR
.RS 4
У SSSD передбачено два представлення для визначення рівня діагностики\&. Найпростішим є визначення десяткового значення у діапазоні 0\-9\&. Кожному значенню відповідає вмикання відповідного рівня діагностики і усіх нижчих рівнів\&. Точніше визначення вмикання або вимикання (якщо це потрібно) специфічних рівнів можна встановити за допомогою шістнадцяткової бітової маски\&.
.sp
Будь ласка, зауважте, що кожна служба SSSD веде журнал у власному файлі\&. Також зауважте, що вмикання
\(lqdebug_level\(rq
у розділі
\(lq[sssd]\(rq
вмикає діагностику лише для самого процесу sssd, а не для процесів відповідача чи надавача даних\&. Для отримання діагностичних повідомлень слід додати параметр \(Fodebug_level\(Fc до усіх розділів, для яких слід створювати журнал діагностичних повідомлень\&.
.sp
Окрім зміни рівня ведення журналу у файлі налаштувань за допомогою параметра \(Fodebug_level\(Fc, який не змінюється під час роботи, але зміна якого потребує перезапуску SSSD, можна змінити режим діагностики без перезапуску за допомогою програми
\fBsss_debuglevel\fR(8)\&.
.sp
Рівні діагностики, передбачені у поточній версії:
.sp
\fI0\fR,
\fI0x0010\fR: критичні помилки з аварійним завершенням роботи\&. Всі помилки, які не дають SSSD змоги розпочати або продовжувати роботу\&.
.sp
\fI1\fR,
\fI0x0020\fR: критичні помилки\&. Помилки, які не призводять до аварійного завершення роботи SSSD, але означають, що одна з основних можливостей не працює належним чином\&.
.sp
\fI2\fR,
\fI0x0040\fR: серйозні помилки\&. Повідомлення про такі помилки означають, що не вдалося виконати певний запит або дію\&.
.sp
\fI3\fR,
\fI0x0080\fR: незначні помилки\&. Це помилки які можуть призвести до помилок під час виконання дій\&.
.sp
\fI4\fR,
\fI0x0100\fR: параметри налаштування\&.
.sp
\fI5\fR,
\fI0x0200\fR: дані функцій\&.
.sp
\fI6\fR,
\fI0x0400\fR: повідомлення трасування для функцій дій\&.
.sp
\fI7\fR,
\fI0x1000\fR: повідомлення трасування для функцій внутрішнього трасування\&.
.sp
\fI8\fR,
\fI0x2000\fR: вміст внутрішніх змінних функцій, який може бути цікавим\&.
.sp
\fI9\fR,
\fI0x4000\fR: дані трасування найнижчого рівня\&.
.sp
Щоб до журналу було записано дані потрібних бітових масок рівнів діагностики, просто додайте відповідні числа, як це показано у наведених нижче прикладах:
.sp
\fIExample\fR: щоб до журналу було записано дані щодо критичних помилок з аварійним завершенням роботи, критичних помилок, серйозних помилок та дані функцій, скористайтеся рівнем діагностики 0x0270\&.
.sp
\fIПриклад\fR: щоб до журналу було записано критичні помилки з аварійним завершенням роботи, параметри налаштування, дані функцій та повідомлення трасування для функцій внутрішнього керування, скористайтеся рівнем 0x1310\&.
.sp
\fIЗауваження\fR: формат бітових масок для рівнів діагностики впроваджено у версії 1\&.7\&.0\&.
.sp
\fIТипове значення\fR: 0
.RE
.PP
\fB\-\-debug\-timestamps=\fR\fIрежим\fR
.RS 4
\fI1\fR: додати часову позначку до діагностичних повідомлень\&.
.sp
\fI0\fR: вимкнути часову позначку у діагностичних повідомленнях
.sp
Типове значення: 1
.RE
.PP
\fB\-\-debug\-microseconds=\fR\fIрежим\fR
.RS 4
\fI1\fR: додати значення мікросекунд до часової позначки у діагностичних повідомленнях
.sp
\fI0\fR: вимкнути додавання мікросекунд до часової позначки
.sp
Типове значення: 0
.RE
.PP
\fB\-f\fR,\fB\-\-debug\-to\-files\fR
.RS 4
Надіслати діагностичні дані до файлів, а не до stderr\&. Типово файли журналів зберігаються у
/var/log/sssd, передбачено також окремий журнал для кожної служби і домену SSSD\&.
.sp
Цей параметр вважається застарілим\&. Його замінено параметром
\fB\-\-logger=files\fR\&.
.RE
.PP
\fB\-\-logger=\fR\fIзначення\fR
.RS 4
Місце, куди SSSD надсилатиме повідомлення журналу\&. Значення цього параметра має вищий пріоритет за значення застарілого параметра
\fB\-\-debug\-to\-files\fR\&. Застарілий параметр працюватиме, якщо не використано параметр
\fB\-\-logger\fR\&.
.sp
\fIstderr\fR: переспрямувати діагностичні повідомлення до стандартного виведення помилок\&.
.sp
\fIfiles\fR: переспрямувати діагностичні повідомлення до файлів журналу\&. Типово файли журналів зберігаються у
/var/log/sssd, передбачено також окремий журнал для кожної служби і домену SSSD\&.
.sp
\fIjournald\fR: переспрямувати діагностичні повідомлення до systemd\-journald
.sp
Типове значення: not set
.RE
.PP
\fB\-D\fR,\fB\-\-daemon\fR
.RS 4
Перейти у режим фонової служби після запуску\&.
.RE
.PP
\fB\-i\fR,\fB\-\-interactive\fR
.RS 4
Запустити програму у звичайному режимі, не створювати фонової служби\&.
.RE
.PP
\fB\-c\fR,\fB\-\-config\fR
.RS 4
Визначити нетиповий файл налаштувань\&. Типовим файлом налаштувань є
/etc/sssd/sssd\&.conf\&. Довідку щодо синтаксису та параметрів файла налаштувань можна знайти на сторінці довідника (man)
\fBsssd.conf\fR(5)\&.
.RE
.PP
\fB\-g\fR,\fB\-\-genconf\fR
.RS 4
Не запускати SSSD, а лише оновити базу даних налаштувань на основі вмісту
/etc/sssd/sssd\&.conf
і завершити роботу\&.
.RE
.PP
\fB\-s\fR,\fB\-\-genconf\-section\fR
.RS 4
Подібний до
\(lq\-\-genconf\(rq, але наказує програмі освіжити лише окремий розділу на основі файла налаштувань\&. Цей параметр корисний, в основному, для виклику з файлів модулів systemd з метою дозволити відповідачам, які активуються з сокетів, освіжати налаштування без потреби у перезапуску адміністратором усього SSSD\&.
.RE
.PP
\fB\-?\fR,\fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Вивести номер версії і завершити роботу\&.
.RE
.SH "Сигнали"
.PP
SIGTERM/SIGINT
.RS 4
Повідомляє SSSD, що слід поступово завершити роботу всіх дочірніх процесів, а потім завершити роботу монітора\&.
.RE
.PP
SIGHUP
.RS 4
Повідомляє SSSD, що слід припинити запис до файлів діагностичних даних з поточними дескрипторами, закрити і повторно відкрити ці файли\&. Цей сигнал призначено для полегшення процедури архівування журналів за допомогою програм, подібних до logrotate\&.
.RE
.PP
SIGUSR1
.RS 4
Наказує SSSD імітувати автономну дію, тривалість якої визначається параметром \(Fooffline_timeout\(Fc\&. Найкориснішим застосуванням є тестування служби\&. Сигнал може бути надіслано або процесу sssd, або процесу sssd_be безпосередньо\&.
.RE
.PP
SIGUSR2
.RS 4
Наказує SSSD перейти у режим роботи у мережі негайно\&. Найкориснішим застосуванням є тестування служби\&. Сигнал може бути надіслано або процесу sssd, або процесу sssd_be безпосередньо\&.
.RE
.SH "ЗАУВАЖЕННЯ"
.PP
If the environment variable SSS_NSS_USE_MEMCACHE is set to "NO", client applications will not use the fast in\-memory cache\&.
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
