'\" t
.\"     Title: sssd-ldap
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Формати файлів та правила
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-LDAP" "5" "12/09/2020" "SSSD" "Формати файлів та правила"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-ldap \- Модуль надання даних LDAP SSSD
.SH "ОПИС"
.PP
На цій сторінці довідника описано налаштування доменів LDAP для
\fBsssd\fR(8)\&. Щоб дізнатися більше про синтаксис налаштування, зверніться до розділу \(FoФОРМАТ ФАЙЛА\(Fc сторінки довідника
\fBsssd.conf\fR(5)\&.
.PP
Ви можете налаштувати SSSD на використання декількох доменів LDAP\&.
.PP
У основному модулі LDAP передбачено підтримку засобів надання ідентифікатора (id), уповноважень (auth), доступу (access) та зміни паролів (chpass)\&. Якщо ви бажаєте виконувати розпізнавання на сервері LDAP, потрібен TLS/SSL або LDAPS\&. У
\fBsssd\fR
\fIне передбачено\fR
підтримки розпізнавання за допомогою шифрованого каналу обміну даними\&. Якщо сервер LDAP використовується лише для надання даних профілів, потреби у шифруванні каналу обміну даними немає\&. Будь ласка, зверніться до опису параметра налаштування
\(lqldap_access_filter\(rq, щоб дізнатися більше про використання LDAP, як засобу керування доступом\&.
.SH "ПАРАМЕТРИ НАЛАШТУВАННЯ"
.PP
All of the common configuration options that apply to SSSD domains also apply to LDAP domains\&. Refer to the
\(lqDOMAIN SECTIONS\(rq
section of the
\fBsssd.conf\fR(5)
manual page for full details\&. Note that SSSD LDAP mapping attributes are described in the
\fBsssd-ldap-attributes\fR(5)
manual page\&.
.PP
ldap_uri, ldap_backup_uri (рядок)
.RS 4
Визначає список адрес серверів LDAP, відокремлених комами, з якими SSSD має встановлювати з\(cqєднання у порядку пріоритету\&. Зверніться до розділу \(FoРЕЗЕРВ\(Fc, щоб дізнатися більше про перемикання на резервні ресурси та додаткові сервери\&. Якщо не вказано, буде використано автоматичне виявлення служб\&. Докладніші відомості можна знайти у розділі \(FoПОШУК СЛУЖБ\(Fc\&.
.sp
Формат адреси має відповідати формату, що визначається RFC 2732:
.sp
ldap[s]://<вузол>[:порт]
.sp
У явних адресах IPv6 <вузол> має бути вказано у квадратних дужках, []
.sp
приклад: ldap://[fc00::126:25]:389
.RE
.PP
ldap_chpass_uri, ldap_chpass_backup_uri (рядок)
.RS 4
Визначає список адрес серверів LDAP, відокремлених комами, з якими SSSD має встановлювати з\(cqєднання у порядку пріоритету для зміни пароля користувача\&. Зверніться до розділу \(FoРЕЗЕРВ\(Fc, щоб дізнатися більше про перемикання на резервні ресурси та додаткові сервери\&.
.sp
Для того, щоб уможливити визначення служб, слід встановити значення параметра ldap_chpass_dns_service_name\&.
.sp
Типове значення: порожнє, тобто використовується ldap_uri\&.
.RE
.PP
ldap_search_base (рядок)
.RS 4
Типова базова назва домену, яку слід використовувати для виконання дій від імені користувача LDAP\&.
.sp
Починаючи з SSSD 1\&.7\&.0, у SSSD передбачено підтримку визначення декількох основ для пошуку за допомогою таких синтаксичних конструкцій:
.sp
основа_пошуку[?діапазон?[фільтр][?основа_пошуку?діапазон?[фільтр]]*]
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&.
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади:
.sp
ldap_search_base = dc=example,dc=com (еквівалентне до) ldap_search_base = dc=example,dc=com?subtree?
.sp
ldap_search_base = cn=host_specific,dc=example,dc=com?subtree?(host=thishost)?dc=example\&.com?subtree?
.sp
Зауваження: підтримки визначення декількох основ пошуку з посиланням на об\(cqєкти з однаковими назвами (наприклад груп з однаковою назвою у двох різних основах пошуку) не передбачено\&. Такі визначення можуть призвести до непередбачуваних результатів на клієнтських комп\(cqютерах\&.
.sp
Типове значення: якщо значення не встановлено, буде використано значення атрибута defaultNamingContext або namingContexts з RootDSE сервера LDAP\&. Якщо запису defaultNamingContext не існує або цей запис має порожнє значення, буде використано namingContexts\&. Для роботи системи потрібно, щоб атрибут namingContexts має єдине значення DN бази пошуку сервера LDAP\&. Підтримки визначення декількох значень не передбачено\&.
.RE
.PP
ldap_schema (рядок)
.RS 4
Визначає тип схеми, що використовується на сервері LDAP призначення\&. Відповідно до вибраної схеми, типові назви атрибутів, отриманих з сервера, можуть бути різними\&. Спосіб обробки атрибутів також може бути різним\&.
.sp
У поточній версії передбачено підтримку чотирьох типів схем:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
rfc2307
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
rfc2307bis
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
IPA
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
AD
.RE
.sp
Основною відмінністю між цими типами схем є спосіб запису даних щодо участі у групах на сервері\&. Відповідно до rfc2307, список учасників груп впорядковується за користувачами у атрибуті
\fImemberUid\fR\&. Відповідно до rfc2307bis і IPA, список учасників груп впорядковується за назвою домену (DN) і зберігається у атрибуті
\fImember\fR\&. Відповідно до типу схеми AD, встановлюється відповідність зі значеннями Active Directory 2008r2\&.
.sp
Типове значення: rfc2307
.RE
.PP
ldap_pwmodify_mode (рядок)
.RS 4
Визначає дію, яку буде здійснено для зміни пароля користувача\&.
.sp
У поточній версії передбачено два режими:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
exop \(em розширена дія зі зміни пароля (RFC 3062)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ldap_modify \(em безпосереднє внесення змін до userPassword (не рекомендуємо)\&.
.RE
.sp
Зауваження: спочатку буде встановлено нове з\*(Aqєднання для перевірки поточного пароля шляхом прив\*(Aqязування до системи від імені користувача, від якого надійшов запит щодо зміни пароля\&. Якщо з\*(Aqєднання вдасться встановити, його буде використано для зміни пароля, тому у користувача має бути доступ до запису атрибута userPassword\&.
.sp
Типове значення: exop
.RE
.PP
ldap_default_bind_dn (рядок)
.RS 4
Типова назва домену прив\(cqязки, яку слід використовувати для виконання дій LDAP\&.
.RE
.PP
ldap_default_authtok_type (рядок)
.RS 4
Тип розпізнавання для типової назви сервера прив\(cqязки\&.
.sp
У поточній версії передбачено підтримку двох механізмів:
.sp
password
.sp
obfuscated_password
.sp
Типове значення: password
.RE
.PP
ldap_default_authtok (рядок)
.RS 4
Лексема розпізнавання типової назви сервера прив\(cqязки\&. У поточній версії передбачено підтримку лише паролів у форматі звичайного тексту\&.
.RE
.PP
ldap_force_upper_case_realm (булеве значення)
.RS 4
Деякі з серверів каталогів, наприклад Active Directory, можуть надавати частину області адреси UPN лише малими літерами (літерами нижнього регістру), що може призвести до невдалої спроби розпізнавання\&. Встановіть ненульове значення цього параметра, якщо ви бажаєте використовувати назву області у верхньому регістрі\&.
.sp
Типове значення: false
.RE
.PP
ldap_enumeration_refresh_timeout (ціле число)
.RS 4
Визначає кількість секунд, протягом яких SSSD має очікувати до оновлення свого кешу нумерованих записів\&.
.sp
Типове значення: 300
.RE
.PP
ldap_purge_cache_timeout (ціле число)
.RS 4
Визначає частоту пошуків у кеші неактивних записів (зокрема груп без учасників та користувачів, які ніколи не входили до системи) та вилучення цих записів з метою економії місця\&.
.sp
Встановлення нульового значення цього параметра вимикає дію з очищення кешу\&. Будь ласка, зауважте, що якщо увімкнено нумерацію, дія з очищення є необхідною з метою виявлення записів, вилучених із сервера, її не можна вимикати\&. Типово, дія з очищення, якщо увімкнено нумерацію, виконується кожні 3 години\&.
.sp
Типове значення: 0 (вимкнено)
.RE
.PP
ldap_group_nesting_level (ціле число)
.RS 4
Якщо ldap_schema встановлено у значення формату схеми, у якому передбачено підтримку вкладеності груп (наприклад RFC2307bis), цей параметр визначає кількість рівнів вкладеності, які оброблятимуться SSSD\&. Значення цього параметра буде проігноровано, якщо використано схему RFC2307\&.
.sp
Зауваження: за допомогою цього параметра визначається гарантований рівень вкладеності груп для обробки під час будь\-якого пошуку\&. Втім,
\fIможе бути\fR
повернуто і групи із більшим рівнем вкладеності, якщо під час попередніх пошуків відбувалася обробка вищих рівнів вкладеності\&. Крім того, послідовні пошуки інших груп можуть розширити набір результатів початкового пошуку, якщо запити щодо пошуку надходять повторно\&.
.sp
Якщо значенням ldap_group_nesting_level є 0, вкладені групи взагалі не оброблятимуться\&. Втім, якщо з\(cqєднання встановлено з Active\-Directory Server 2008 та новішими версіями з використанням
\(lqid_provider=ad\(rq, слід також вимкнути використання груп реєстраційних записів (Token\-Groups) встановленням для параметра ldap_use_tokengroups значення false з метою обмеження вкладеності у групах\&.
.sp
Типове значення: 2
.RE
.PP
ldap_use_tokengroups
.RS 4
За допомогою цього параметра можна увімкнути або вимкнути використання атрибута Token\-Groups під час виконання initgroup для користувачів Active Directory Server 2008 та новіших версій\&.
.sp
Типове значення: True для AD і IPA, інакше False\&.
.RE
.PP
ldap_host_search_base (рядок)
.RS 4
Необов\(cqязковий\&. Використати вказаний рядок як основу пошуку об\(cqєктів вузлів\&.
.sp
Ознайомтеся з розділом щодо \(Foldap_search_base\(Fc, щоб дізнатися більше про налаштування декількох основ пошуку\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.RE
.PP
ldap_service_search_base (рядок)
.RS 4
Додатковий основний DN, область пошуку і фільтр LDAP для обмеження пошуків LDAP цим типом атрибутів\&.
.sp
синтаксис:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&. Докладніший опис діапазонів наведено у розділі 4\&.5\&.1\&.2 документа http://tools\&.ietf\&.org/html/rfc4511
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади використання цих синтаксичних конструкцій можна знайти у розділі прикладів \(Foldap_search_base\(Fc\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.sp
Будь ласка, зауважте, що підтримки визначення області або фільтра для пошуків на сервері Active Directory не передбачено\&. Це може призвести до отримання значної кількості результатів і викликати реакцію з боку розширення діапазону отримання (Range Retrieval)\&.
.RE
.PP
ldap_search_timeout (ціле число)
.RS 4
Визначає час очікування на дані (у секундах) для виконання пошуків ldap, перш ніж пошук буде скасовано з поверненням кешованих даних (і переходом до автономного режиму роботи)
.sp
Зауваження: роботу цього параметра буде змінено у наступних версіях SSSD\&. Ймовірно, його буде колись замінено на послідовність часів очікування для окремих типів пошуків\&.
.sp
Типове значення: 6
.RE
.PP
ldap_enumeration_search_timeout (ціле число)
.RS 4
Визначає час очікування на дані (у секундах) для виконання пошуків номерів користувачів та груп у ldap, перш ніж пошук буде скасовано з поверненням кешованих даних (і переходом до автономного режиму роботи)
.sp
Типове значення: 60
.RE
.PP
ldap_network_timeout (ціле число)
.RS 4
Визначає час очікування (у секундах), після завершення якого
\fBpoll\fR(2)/\fBselect\fR(2)
з наступним
\fBconnect\fR(2)
повертається до стану бездіяльності\&.
.sp
Типове значення: 6
.RE
.PP
ldap_opt_timeout (ціле число)
.RS 4
Визначає час очікування (у секундах), після завершення якого виклики до синхронних програмних інтерфейсів LDAP буде перервано, якщо не буде отримано відповіді\&. Також керує часом очікування під час обміну даними з KDC у випадку прив\(cqязки SASL, часом очікування на дію з прив\(cqязування LDAP, розширеної операції зі зміни пароля та дії StartTLS\&.
.sp
Типове значення: 8
.RE
.PP
ldap_connection_expire_timeout (ціле значення)
.RS 4
Визначає час очікування (у секундах), протягом якого підтримуватиметься з\(cqєднання з сервером LDAP\&. По завершенню цього часу буде зроблено спробу повторно встановити з\(cqєднання\&. У разі використання паралельно до SASL/GSSAPI буде використано перше за часом значення (це значення або значення строку дії TGT)\&.
.sp
Типове значення: 900 (15 хвилин)
.RE
.PP
ldap_page_size (ціле число)
.RS 4
Визначити кількість записів, які слід отримати з LDAP у відповідь на один запит\&. На деяких серверах LDAP визначено обмеження максимальної кількості на один запит\&.
.sp
Типове значення: 1000
.RE
.PP
ldap_disable_paging (булеве значення)
.RS 4
Вимикає контроль сторінок LDAP\&. Цим параметром слід скористатися, якщо сервер LDAP повідомляє про підтримку контролю сторінок LDAP у своєму RootDSE, але цю підтримку не увімкнено або вона не працює належним чином\&.
.sp
Приклад: сервери OpenLDAP з модулем контролю сторінок, встановленим на сервері, але не увімкненим, повідомляють про підтримку у RootDSE, але цією підтримкою не можна скористатися\&.
.sp
Приклад: 389 DS має ваду, пов\(cqязану з тим, що здатен підтримувати лише один процес контролю сторінок для одного з\(cqєднання\&. У разі значного навантаження це може призвести до відмови у виконанні запитів\&.
.sp
Типове значення: False
.RE
.PP
ldap_disable_range_retrieval (булеве значення)
.RS 4
Вимкнути отримання діапазону Active Directory\&.
.sp
У Active Directory за допомогою правила MaxValRange (типове значення 1500 записів) обмежується кількість записів, які може бути отримано під час пошуку\&. Якщо у певній групі міститься більше записів учасників, до відповіді буде включено специфічне для AD розширення діапазону\&. За допомогою цього параметра можна вимкнути обробку розширення діапазону, отже великі групи буде представлено як такі, у яких немає учасників\&.
.sp
Типове значення: False
.RE
.PP
ldap_sasl_minssf (ціле значення)
.RS 4
Під час обміну даними з сервером LDAP за допомогою SASL визначає мінімальний рівень захисту, потрібний для встановлення з\(cqєднання\&. Значення цього параметра визначається OpenLDAP\&.
.sp
Типове значення: типове для системи значення (зазвичай, визначається у ldap\&.conf)
.RE
.PP
ldap_deref_threshold (ціле число)
.RS 4
Вказує кількість учасників групи, записів яких має не вистачати у зовнішньому кеші для запуску загального пошуку з розіменуванням\&. Якщо пропущених записів буде менше за вказану кількість, пошук для них виконуватиметься окремо\&.
.sp
Ви можете повністю вимкнути запити щодо розіменувань встановленням значення 0\&. Будь ласка, зауважте, що у коді SSSD, зокрема засобу надання даних HBAC IPA, є інструкції, які реалізовано лише з використанням викликів щодо розіменування, тому навіть явне вимикання розіменувань не призведе до вимикання розіменувань у цих частинах коду, якщо на сервері передбачено підтримку розіменувань і оголошено про керування розіменуваннями у об\*(Aqєкті rootDSE\&.
.sp
Пошук з розіменуванням \(em це отримання всіх записів учасників групи за одним викликом LDAP\&. У різних серверах LDAP може бути передбачено різні способи розіменування\&. У поточній версії передбачено підтримку серверів 389/RHDS, OpenLDAP та Active Directory\&.
.sp
\fIЗауваження:\fR
якщо у одній з основ пошуку визначається фільтр пошуку, покращення швидкодії фільтрів розіменування буде вимкнено, незалежно від використання цього параметра\&.
.sp
Типове значення: 10
.RE
.PP
ldap_tls_reqcert (рядок)
.RS 4
Визначає перелік перевірок, які слід виконати для сертифікатів серверів у сеансі TLS, якщо такі перевірки слід виконувати\&. Може бути визначено одне з таких значень:
.sp
\fInever\fR
= клієнт не надсилатиме запиту і не перевірятиме жодних сертифікатів сервера\&.
.sp
\fIallow\fR
= надіслати запит щодо сертифіката сервера\&. Якщо сертифікат не буде надано, продовжити сеанс у звичайному режимі\&. Якщо буде надано помилковий сертифікат, ігнорувати і продовжити сеанс у звичайному режимі\&.
.sp
\fItry\fR
= надіслати запит щодо сертифіката сервера\&. Якщо сертифікат не буде надано, продовжити сеанс у звичайному режимі\&. Якщо буде надано помилковий сертифікат, негайно перервати сеанс\&.
.sp
\fIdemand\fR
= надіслати запит щодо сертифіката сервера\&. Якщо сертифікат не буде надано або буде надано помилковий сертифікат, негайно перервати сеанс\&.
.sp
\fIhard\fR
= те саме, що і
\(lqdemand\(rq
.sp
Типове значення: hard
.RE
.PP
ldap_tls_cacert (рядок)
.RS 4
Визначає файл, який містить сертифікати для всіх служб сертифікації, які розпізнаються
\fBsssd\fR\&.
.sp
Типове значення: використовувати типові параметри OpenLDAP, що зберігаються у
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_tls_cacertdir (рядок)
.RS 4
Визначає шлях до каталогу, де у окремих файлах містяться сертифікати служб сертифікації (CA)\&. Типовими назвами файлів є хеші сертифікатів з додаванням \(Fo\&.0\(Fc\&. Для створення відповідних назв можна скористатися
\fBcacertdir_rehash\fR, якщо ця програма є доступною\&.
.sp
Типове значення: використовувати типові параметри OpenLDAP, що зберігаються у
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_tls_cert (рядок)
.RS 4
Визначає файл, який містить сертифікат для ключа клієнта\&.
.sp
Типове значення: not set
.RE
.PP
ldap_tls_key (рядок)
.RS 4
Визначає файл, у якому міститься ключ клієнта\&.
.sp
Типове значення: not set
.RE
.PP
ldap_tls_cipher_suite (рядок)
.RS 4
Визначає прийнятні комплекти програм для шифрування\&. Записи у типовому списку слід відокремлювати комами\&. З форматом можна ознайомитися на сторінці довідника до
\fBldap.conf\fR(5)\&.
.sp
Типове значення: використовувати типові параметри OpenLDAP, що зберігаються у
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_id_use_start_tls (булеве значення)
.RS 4
Визначає, що з\(cqєднання id_provider має також використовувати
tls
для захисту каналу\&.
.sp
Типове значення: false
.RE
.PP
ldap_id_mapping (булеве значення)
.RS 4
Визначає, що SSSD має намагатися встановити відповідність ідентифікаторів користувача і групи на основі атрибутів ldap_user_objectsid та ldap_group_objectsid, замість атрибутів ldap_user_uid_number та ldap_group_gid_number\&.
.sp
У поточній версії у цій можливості передбачено підтримку лише встановлення відповідності objectSID у ActiveDirectory\&.
.sp
Типове значення: false
.RE
.PP
ldap_min_id, ldap_max_id (ціле число)
.RS 4
На відміну від прив\(cqязування ідентифікаторів на основі SID, яке використовується, якщо параметр ldap_id_mapping має значення true, діапазон дозволених ідентифікаторів для ldap_user_uid_number і ldap_group_gid_number є необмеженим\&. У конфігураціях з піддоменами та довіреними доменами це може призвести до конфліктів ідентифікаторів\&. Щоб уникнути конфліктів, можна встановити значення ldap_min_id і ldap_max_id для обмеження дозволеного діапазону ідентифікаторів, які буде прочитано безпосередньо з сервера\&. Після цього піддомени можуть вибирати інші діапазони для прив\(cqязування ідентифікаторів\&.
.sp
Типове значення: не встановлено (обидва параметри встановлено у значення 0)
.RE
.PP
ldap_sasl_mech (рядок)
.RS 4
Визначає механізм SASL, який слід використовувати\&. У поточній версії перевірено і передбачено підтримку лише механізмів GSSAPI та GSS\-SPNEGO\&.
.sp
Якщо у модулі обробки передбачено підтримку піддоменів, значення для піддоменів ldap_sasl_mech буде автоматично успадковано від домену\&. Якщо для якогось піддомену потрібне інше значення, його можна перезаписати встановленням ldap_sasl_mech для цього піддомену окремо\&. Докладніший опис можна знайти у розділі щодо довірених доменів у підручнику з
\fBsssd.conf\fR(5)\&.
.sp
Типове значення: not set
.RE
.PP
ldap_sasl_authid (рядок)
.RS 4
Визначає ідентифікатор уповноваження SASL, яким слід скористатися\&. Якщо використовується GSSAPI/GSS\-SPNEGO, цим ідентифікатором є реєстраційні дані Kerberos, які використовуються для розпізнавання при доступі до каталогу\&. Цей параметр може містити або повні реєстраційні дані (наприклад host/myhost@EXAMPLE\&.COM) або просто назву реєстраційного запису (наприклад host/myhost)\&. Типово, значення не встановлено і використовуються такі реєстраційні записи:
.sp
.if n \{\
.RS 4
.\}
.nf
hostname@REALM
netbiosname$@REALM
host/hostname@REALM
*$@REALM
host/*@REALM
host/*
                            
.fi
.if n \{\
.RE
.\}
.sp
Якщо жоден з них не буде знайдено, буде повернуто перший реєстраційний запис у таблиці ключів\&.
.sp
Типове значення: вузол/назва_вузла@ОБЛАСТЬ
.RE
.PP
ldap_sasl_realm (рядок)
.RS 4
Визначає область SASL, яку слід використовувати\&. Якщо не вказано значення, типовим значенням цього параметра є значення krb5_realm\&. Якщо ldap_sasl_authid також містить запис області, цей параметр буде проігноровано\&.
.sp
Типове значення: значення krb5_realm\&.
.RE
.PP
ldap_sasl_canonicalize (булеве значення)
.RS 4
Якщо встановлено значення true (1), бібліотека LDAP виконувати зворотній пошук з метою переведення назв вузлів у канонічну форму під час прив\(cqязки до SASL\&.
.sp
Типове значення: false;
.RE
.PP
ldap_krb5_keytab (рядок)
.RS 4
Визначає таблицю ключів, яку слід використовувати разом з SASL/GSSAPI/GSS\-SPNEGO\&.
.sp
Типове значення: системна таблиця ключів, зазвичай
/etc/krb5\&.keytab
.RE
.PP
ldap_krb5_init_creds (булеве значення)
.RS 4
Визначає, що id_provider має ініціалізувати реєстраційні дані Kerberos (TGT)\&. Цю дію буде виконано, лише якщо використовується SASL і вибрано механізм GSSAPI або GSS\-SPNEGO\&.
.sp
Типове значення: true
.RE
.PP
ldap_krb5_ticket_lifetime (ціле число)
.RS 4
Визначає строк дії (у секундах) TGT, якщо використовується GSSAPI або GSS\-SPNEGO\&.
.sp
Типове значення: 86400 (24 години)
.RE
.PP
krb5_server, krb5_backup_server (рядок)
.RS 4
Визначає список IP\-адрес або назв вузлів, відокремлених комами, серверів Kerberos, з якими SSSD має встановлювати з\(cqєднання\&. Список має бути впорядковано за пріоритетом\&. Докладніше про резервування та додаткові сервери можна дізнатися з розділу \(FoРЕЗЕРВ\(Fc\&. До адрес або назв вузлів може бути додано номер порту (перед номером слід вписати двокрапку)\&. Якщо параметр матиме порожнє значення, буде увімкнено виявлення служб\&. Докладніше про виявлення служб можна дізнатися з розділу \(FoПОШУК СЛУЖБ\(Fc\&.
.sp
Під час використання виявлення служб для серверів KDC або kpasswd SSSD спочатку намагається знайти записи DNS, у яких визначається протокол _udp\&. Використання протоколу _tcp відбувається, лише якщо таких записів не вдасться знайти\&.
.sp
У попередніх випусках SSSD цей параметр мав назву \(Fokrb5_kdcip\(Fc\&. У поточній версії передбачено розпізнавання цієї застарілої назви, але користувачам варто перейти на використання \(Fokrb5_server\(Fc у файлах налаштувань\&.
.RE
.PP
krb5_realm (рядок)
.RS 4
Вказати область Kerberos (для розпізнавання за SASL/GSSAPI/GSS\-SPNEGO)\&.
.sp
Типове значення: типове значення системи, див\&.
/etc/krb5\&.conf
.RE
.PP
krb5_canonicalize (булеве значення)
.RS 4
Визначає, чи слід перетворювати реєстраційний запис вузла у канонічну форму під час встановлення з\(cqєднання з сервером LDAP\&. Цю можливість передбачено з версії MIT Kerberos >= 1\&.7
.sp
Типове значення: false
.RE
.PP
krb5_use_kdcinfo (булеве значення)
.RS 4
Визначає, чи слід SSSD вказувати бібліотекам Kerberos, яку область і які значення KDC слід використовувати\&. Типово, дію параметра увімкнено\&. Якщо ви вимкнете його, вам слід налаштувати бібліотеку Kerberos за допомогою файла налаштувань
\fBkrb5.conf\fR(5)\&.
.sp
Див\&. сторінку підручника (man)
\fBsssd_krb5_locator_plugin\fR(8), щоб дізнатися більше про додаток пошуку\&.
.sp
Типове значення: true
.RE
.PP
ldap_pwd_policy (рядок)
.RS 4
Визначає правил оцінки строку дії пароля на боці клієнта\&. Можна використовувати такі значення:
.sp
\fInone\fR
\(em не використовувати перевірки на боці клієнта\&. У разі використання цього варіанта перевірку на боці сервера вимкнено не буде\&.
.sp
\fIshadow\fR
\(em використовувати атрибути у стилі
\fBshadow\fR(5)
для визначення того, чи чинним є пароль\&.
.sp
\fImit_kerberos\fR
\(em використовувати атрибути MIT Kerberos для визначення завершення строку дії пароля\&. У разі зміни пароля скористайтеся chpass_provider=krb5 для оновлення цих атрибутів\&.
.sp
Типове значення: none
.sp
\fIЗауваження\fR: якщо правила поводження з паролями налаштовано на боці сервера, ці правила мають пріоритет над правилами, встановленими за допомогою цього параметра\&.
.RE
.PP
ldap_referrals (булеве значення)
.RS 4
Визначає, чи має бути увімкнено автоматичне визначення напрямків пошуку\&.
.sp
Зауважте, що sssd підтримує визначення напрямків, лише якщо систему зібрано з версією OpenLDAP 2\&.4\&.13 або новішою версією\&.
.sp
Перехід за спрямуваннями може призвести до значних втрат швидкодії у середовищах, де такі спрямування використовуються широко\&. Прикладом такого середовища може бути Microsoft Active Directory\&. Якщо у вашому середовищі спрямування не є обов\(cqязковими, встановлення для цього параметра значення \(Fofalse\(Fc може значно пришвидшити роботу\&.
.sp
Типове значення: true
.RE
.PP
ldap_dns_service_name (рядок)
.RS 4
Визначає назву служби, яку буде використано у разі вмикання визначення служб\&.
.sp
Типове значення: ldap
.RE
.PP
ldap_chpass_dns_service_name (рядок)
.RS 4
Визначає назву служби, яку буде використано для пошуку сервера LDAP, який уможливлює зміну паролів, у разі вмикання визначення служб\&.
.sp
Типове значення: не встановлено, тобто пошук служб вимкнено
.RE
.PP
ldap_chpass_update_last_change (булеве значення)
.RS 4
Визначає, чи слід оновлювати атрибут ldap_user_shadow_last_change даними щодо кількості днів з часу виконання дії зі зміни пароля\&.
.sp
Типове значення: False
.RE
.PP
ldap_access_filter (рядок)
.RS 4
Якщо використовується access_provider = ldap та ldap_access_order = filter (типова поведінка), цей параметр є обов\(cqязковим\&. Він вказує критерії фільтрування LDAP, яким має задовольняти запис користувача для надання доступу до цього вузла\&. Якщо визначено access_provider = ldap та ldap_access_order = filter, а цей параметр не встановлено, доступ буде заборонено всім користувачам\&. Щоб змінити таку типову поведінку системи, скористайтеся параметром access_provider = permit\&. Будь ласка, зауважте, що цей фільтр застосовуватиметься лише до запису користувача LDAP, отже фільтрування, засноване на вкладених групах може не працювати (наприклад, атрибут memberOf для записів AD вказує лише на безпосередні батьківські записи)\&. Якщо вам потрібне фільтрування, засноване на вкладених групах, будь ласка, скористайтеся параметром
\fBsssd-simple\fR(5)\&.
.sp
Приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
access_provider = ldap
ldap_access_filter = (employeeType=admin)
                        
.fi
.if n \{\
.RE
.\}
.sp
У прикладі доступ до цього вузла обмежено користувачами, чий атрибут employeeType встановлено у значення \(Foadmin\(Fc\&.
.sp
Автономне кешування для цієї можливості обмежено визначенням того, чи було надано користувачеві під час попередньої спроби увійти до системи з мережі права доступу\&. Якщо під час останньої спроби увійти такі права було надано, система продовжуватиме надавати права доступу у автономному режимі\&. Якщо ж таких прав не було надано, у автономному режимі їх також не буде надано\&.
.sp
Типове значення: порожній рядок
.RE
.PP
ldap_account_expire_policy (рядок)
.RS 4
За допомогою цього параметра може бути увімкнено визначення атрибутів керування доступом на боці клієнта\&.
.sp
Будь ласка, зауважте, що завжди варто використовувати керування доступом на боці сервера, тобто сервер LDAP має відмовляти у запитах щодо прив\(cqязування з відповідним кодом помилки, навіть якщо вказано правильний пароль\&.
.sp
Можна використовувати такі значення:
.sp
\fIshadow\fR: це значення ldap_user_shadow_expire допомагає визначити, чи завершено строк дії облікового запису\&.
.sp
\fIad\fR: скористатися значенням 32\-бітового поля ldap_user_ad_user_account_control і дозволити доступ, якщо другий біт має нульове значення\&. Якщо атрибут не буде знайдено, доступ буде дозволено\&. Також буде перевірено, чи не вичерпано строк дії облікового запису\&.
.sp
\fIrhds\fR,
\fIipa\fR,
\fI389ds\fR: використовувати для перевірки доступу значення ldap_ns_account_lock\&.
.sp
\fInds\fR: для перевірки доступу використовувати значення ldap_user_nds_login_allowed_time_map, ldap_user_nds_login_disabled і ldap_user_nds_login_expiration_time\&. Якщо не буде виявлено жодного з цих атрибутів, надати доступ\&.
\fI Цю можливість ще не перевірено достатнім чином Будь ласка, якщо помітите якісь вади, повідомте про них за допомогою настанов на сторінці https://pagure\&.io/SSSD/sssd/\&. \fR
.sp
Будь ласка, зауважте, що параметр налаштування ldap_access_order
\fIмає\fR
включати
\(lqexpire\(rq, щоб можна було користуватися параметром ldap_account_expire_policy\&.
.sp
Типове значення: порожній рядок
.RE
.PP
ldap_access_order (рядок)
.RS 4
Список відокремлених комами параметрів керування доступом\&. Можливі значення списку:
.sp
\fIfilter\fR: використовувати ldap_access_filter
.sp
\fIlockout\fR: використовувати блокування облікових записів\&. Якщо встановлено, цей параметр забороняє доступ, якщо існує атрибут ldap \(FopwdAccountLockedTime\(Fc і його значенням є \(Fo000001010000Z\(Fc\&. Будь ласка, ознайомтеся із документацією до параметра ldap_pwdlockout_dn\&. Зауважте, що для працездатності цієї можливості слід встановити \(Foaccess_provider = ldap\(Fc\&.
.sp
\fI Будь ласка, зауважте, що цей параметр має нижчий пріоритет за параметр \(Foppolicy\(Fc, його може бути вилучено у наступних випусках\&. \fR
.sp
\fIppolicy\fR: використовувати блокування облікових записів\&. Якщо встановлено, забороняє доступ у випадку наявності атрибута ldap \(FopwdAccountLockedTime\(Fc рівного \(Fo000001010000Z\(Fc або такого, що відповідає моменту часу у минулому\&. Значення атрибута \(FopwdAccountLockedTime\(Fc має завершуватися на \(FoZ\(Fc, що позначає часовий пояс UTC\&. Підтримки інших часових поясів у поточній версії не передбачено, їхнє використання призводитиме до появи повідомлення про заборону доступу, коли користувачі намагатимуться увійти до системи\&. Докладніший опис можна знайти у розділі щодо параметра ldap_pwdlockout_dn\&. Будь ласка, зауважте, що для працездатності цього параметра слід встановити значення \(Foaccess_provider = ldap\(Fc\&.
.sp
\fIexpire\fR: використовувати ldap_account_expire_policy
.sp
\fIpwd_expire_policy_reject, pwd_expire_policy_warn, pwd_expire_policy_renew: \fR
Ці параметри корисні, якщо користувачам потрібні попередження щодо скорого завершення строку дії пароля, і у випадках, коли розпізнавання засновано на відмінних від паролів методах, наприклад на ключах SSH\&.
.sp
Відмінність між цими параметрами полягає у дії, яку буде виконано, якщо строк дії пароля вичерпано: pwd_expire_policy_reject \(em користувачеві буде заборонено вхід до системи, pwd_expire_policy_warn \(em користувач ще зможе увійти до системи, pwd_expire_policy_renew \(em система попросить користувача негайно змінити пароль\&.
.sp
Зауважте, що якщо строк дії пароля вичерпано, запит із явним повідомленням від SSSD не надходитиме\&.
.sp
Будь ласка, зауважте, що для того, щоб цим можна було скористатися, слід встановити \(Foaccess_provider = ldap\(Fc\&. Крім того, слід встановити для параметра \(Foldap_pwd_policy\(Fc відповідні правила поводження із паролями\&.
.sp
\fIauthorized_service\fR: використовувати для визначення можливості доступу атрибут authorizedService
.sp
\fIhost\fR: за допомогою цього атрибута вузла можна визначити права доступу
.sp
\fIrhost\fR: використовувати атрибут rhost для визначення того, чи матиме віддалений вузол доступ
.sp
Будь ласка, зауважте, що значення поля rhost у pam встановлюється програмою\&. Варто перевірити, що програма надсилає pam, перш ніж вмикати цей варіант керування доступом\&.
.sp
Типове значення: filter
.sp
Зауважте, що програма повідомить про помилку, якщо одне значення було використано декілька разів\&.
.RE
.PP
ldap_pwdlockout_dn (рядок)
.RS 4
За допомогою цього параметра визначається DN запису правил поводження із паролями на сервері LDAP\&. Будь ласка, зауважте, що те, що цього параметра не буде у sssd\&.conf, у випадку увімкненого блокування облікових записів призведе до заборони доступу, оскільки атрибути ppolicy на сервері LDAP не можна буде перевірити належним чином\&.
.sp
Приклад: cn=ppolicy,ou=policies,dc=example,dc=com
.sp
Типове значення: cn=ppolicy,ou=policies,$ldap_search_base
.RE
.PP
ldap_deref (рядок)
.RS 4
Визначає спосіб виконання розіменовування псевдонімів під час виконання пошуку\&. Можливі такі варіанти:
.sp
\fInever\fR: ніколи не виконувати розіменування псевдонімів\&.
.sp
\fIsearching\fR: розіменування псевдонімів відбувається у межах основного об\(cqєкта, а не на основі визначення місця основного об\(cqєкта пошуку\&.
.sp
\fIfinding\fR: розіменування псевдонімів відбувається лише під час визначення місця основного об\(cqєкта пошуку\&.
.sp
\fIalways\fR: розіменування псевдонімів відбувається як під час пошуку, так і під час визначення місця основного об\(cqєкта пошуку\&.
.sp
Типове значення: не встановлено (обробка бібліотеками LDAP клієнта за сценарієм
\fInever\fR)
.RE
.PP
ldap_rfc2307_fallback_to_local_users (булеве значення)
.RS 4
Надає змогу зберігати локальних користувачів як учасників групи LDAP для серверів, у яких використовується схема RFC2307\&.
.sp
У деяких середовищах, де використовується схема RFC2307, локальних користувачів можна зробити учасниками груп LDAP додаванням імен цих користувачів до атрибута memberUid\&. Узгодженість домену може бути скомпрометовано, якщо буде виконано подібне додавання учасника, тому SSSD за звичайних умов вилучає записи користувачів, яких \(Foне вистачає\(Fc, з кешованих даних щодо участі у групах, щойно nsswitch спробує отримати дані щодо користувачів за допомогою виклику getpw*() або initgroups()\&.
.sp
У разі використання цього параметра програма повертається до перевірки посилань на локальних користувачів і кешує їх так, що наступні виклики initgroups() розширюватимуть список локальних користувачів додатковими групами LDAP\&.
.sp
Типове значення: false
.RE
.PP
wildcard_limit (ціле число)
.RS 4
Визначає верхню межу для кількості записів, які отримуватимуться під час пошуку з використанням символів\-замінників\&.
.sp
У поточній версії пошук із використанням символів\-замінників передбачено лише для відповідача InfoPipe\&.
.sp
Типове значення: 1000 (часто розмір однієї сторінки)
.RE
.SH "ПАРАМЕТРИ SUDO"
.PP
Докладні настанов щодо налаштовування sudo_provider можна знайти на сторінці довідника (man)
\fBsssd-sudo\fR(5)\&.
.PP
.PP
ldap_sudo_full_refresh_interval (ціле число)
.RS 4
Проміжок часу у секундах між послідовними повними оновленнями правил sudo SSSD у автоматичному режимі\&. Під час таких оновлень буде отримано повний набір правил, що зберігаються на сервері\&.
.sp
Це значення має перевищувати значення
\fIldap_sudo_smart_refresh_interval \fR
.sp
Типове значення: 21600 (6 годин)
.RE
.PP
ldap_sudo_smart_refresh_interval (ціле число)
.RS 4
Проміжок часу у секундах між послідовними кмітливими оновленнями правил sudo SSSD у автоматичному режимі\&. Під час таких оновлень буде отримано всі дані правил, USN яких перевищує найбільше значення сервера USN, яке відоме SSSD\&.
.sp
Якщо підтримки атрибутів USN на сервері не передбачено, буде використано дані атрибута modifyTimestamp\&.
.sp
\fIЗауваження:\fR
набільше значення USN можна оновити у три способи: 1) повним і кмітливим оновленням sudo (якщо виявлено оновлені правила), 2) нумеруванням користувачів і груп (якщо виявлено увімкнені і оновлені записи користувачів або груп) і 3) повторним з\*(Aqєднанням із сервером (типово, кожні 15 хвилин, див\&.
\fIldap_connection_expire_timeout\fR)\&.
.sp
Типове значення: 900 (15 хвилин)
.RE
.PP
ldap_sudo_use_host_filter (булеве значення)
.RS 4
Якщо визначено значення true, SSSD отримуватиме лише правила, що стосуються цього комп\(cqютера (на основі адрес вузла або мережі у форматах IPv4 і IPv6 та назв вузлів)\&.
.sp
Типове значення: true
.RE
.PP
ldap_sudo_hostnames (рядок)
.RS 4
Список назв вузлів або повних доменних назв, відокремлених пробілами, для фільтрування списку правил\&.
.sp
Якщо значення цього параметра є порожнім, SSSD намагатиметься визначити назву вузла та повну назву комп\(cqютера у домені у автоматичному режимі\&.
.sp
Якщо для
\fIldap_sudo_use_host_filter\fR
встановлено значення
\fIfalse\fR, цей параметр ні на що не впливатиме\&.
.sp
Типове значення: не вказано
.RE
.PP
ldap_sudo_ip (рядок)
.RS 4
Список адрес вузлів або мереж у форматах IPv4 і IPv6 для фільтрування списку правил\&.
.sp
Якщо значення цього параметра є порожнім, SSSD намагатиметься визначити адресу у автоматичному режимі\&.
.sp
Якщо для
\fIldap_sudo_use_host_filter\fR
встановлено значення
\fIfalse\fR, цей параметр ні на що не впливатиме\&.
.sp
Типове значення: не вказано
.RE
.PP
ldap_sudo_include_netgroups (булеве значення)
.RS 4
Якщо вказано значення true, SSSD отримуватиме всі правила, що містять мережеву групу (netgroup) у атрибуті sudoHost\&.
.sp
Якщо для
\fIldap_sudo_use_host_filter\fR
встановлено значення
\fIfalse\fR, цей параметр ні на що не впливатиме\&.
.sp
Типове значення: true
.RE
.PP
ldap_sudo_include_regexp (булеве значення)
.RS 4
Якщо вказано значення true, SSSD отримуватиме всі правила, що містять шаблон заміни у атрибуті sudoHost\&.
.sp
Якщо для
\fIldap_sudo_use_host_filter\fR
встановлено значення
\fIfalse\fR, цей параметр ні на що не впливатиме\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Використання символів\-замінників є дуже обчислювально вартісною операцією для сервера LDAP!
.sp .5v
.RE
Типове значення: false
.RE
.PP
На цій сторінці довідника наведено дані щодо відповідності назв атрибутів\&. Докладний опис семантики атрибутів, пов\(cqязаних з sudo, можна знайти у довідці з
\fBsudoers.ldap\fR(5)\&.
.SH "ПАРАМЕТРИ AUTOFS"
.PP
Деякі типові значення параметрів, описаних нижче, залежать від бази даних LDAP\&.
.PP
.PP
ldap_autofs_map_master_name (рядок)
.RS 4
Назва основної карти автоматичного монтування у LDAP\&.
.sp
Типове значення: auto\&.master
.RE
.PP
ldap_autofs_map_object_class (рядок)
.RS 4
Клас об\(cqєктів запису карти автоматичного монтування у LDAP\&.
.sp
Типове значення: nisMap (rfc2307, autofs_provider=ad), у інших випадках automountMap
.RE
.PP
ldap_autofs_map_name (рядок)
.RS 4
Назва запису карти автоматичного монтування у LDAP\&.
.sp
Типове значення: nisMapName (rfc2307, autofs_provider=ad), у інших випадках automountMapName
.RE
.PP
ldap_autofs_entry_object_class (рядок)
.RS 4
Клас об\*(Aqєктів автоматичного монтування LDAP\&. Цей запис зазвичай відповідає точні монтування\&.
.sp
Типове значення: nisObject (rfc2307, autofs_provider=ad), у інших випадках automount
.RE
.PP
ldap_autofs_entry_key (рядок)
.RS 4
Ключ запису автоматичного монтування LDAP\&. Цей запис зазвичай відповідає точні монтування\&.
.sp
Типове значення: cn (rfc2307, autofs_provider=ad), у інших випадках automountKey
.RE
.PP
ldap_autofs_entry_value (рядок)
.RS 4
Ключ запису автоматичного монтування LDAP\&. Цей запис зазвичай відповідає точні монтування\&.
.sp
Типове значення: nisMapEntry (rfc2307, autofs_provider=ad), у інших випадках automountInformation
.RE
.PP
Будь ласка, зауважте, що засіб автоматичного монтування читає основну карту лише під час запуску, отже якщо до ssd\&.conf внесено будь\-які пов\(cqязані з autofs зміни, типово слід перезапустити фонову службу автоматичного монтування після перезапуску SSSD\&.
.SH "ДОДАТКОВІ ПАРАМЕТРИ"
.PP
Підтримку цих параметрів передбачено доменами LDAP, але користуватися ними слід обережно\&. Будь ласка, використовуйте їх у налаштуваннях, лише якщо вам відомі наслідки ваших дій\&.
.PP
ldap_netgroup_search_base (рядок)
.RS 4
Додатковий основний DN, область пошуку і фільтр LDAP для обмеження пошуків LDAP цим типом атрибутів\&.
.sp
синтаксис:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&. Докладніший опис діапазонів наведено у розділі 4\&.5\&.1\&.2 документа http://tools\&.ietf\&.org/html/rfc4511
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади використання цих синтаксичних конструкцій можна знайти у розділі прикладів \(Foldap_search_base\(Fc\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.sp
Будь ласка, зауважте, що підтримки визначення області або фільтра для пошуків на сервері Active Directory не передбачено\&. Це може призвести до отримання значної кількості результатів і викликати реакцію з боку розширення діапазону отримання (Range Retrieval)\&.
.RE
.PP
ldap_user_search_base (рядок)
.RS 4
Додатковий основний DN, область пошуку і фільтр LDAP для обмеження пошуків LDAP цим типом атрибутів\&.
.sp
синтаксис:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&. Докладніший опис діапазонів наведено у розділі 4\&.5\&.1\&.2 документа http://tools\&.ietf\&.org/html/rfc4511
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади використання цих синтаксичних конструкцій можна знайти у розділі прикладів \(Foldap_search_base\(Fc\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.sp
Будь ласка, зауважте, що підтримки визначення області або фільтра для пошуків на сервері Active Directory не передбачено\&. Це може призвести до отримання значної кількості результатів і викликати реакцію з боку розширення діапазону отримання (Range Retrieval)\&.
.RE
.PP
ldap_group_search_base (рядок)
.RS 4
Додатковий основний DN, область пошуку і фільтр LDAP для обмеження пошуків LDAP цим типом атрибутів\&.
.sp
синтаксис:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&. Докладніший опис діапазонів наведено у розділі 4\&.5\&.1\&.2 документа http://tools\&.ietf\&.org/html/rfc4511
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади використання цих синтаксичних конструкцій можна знайти у розділі прикладів \(Foldap_search_base\(Fc\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.sp
Будь ласка, зауважте, що підтримки визначення області або фільтра для пошуків на сервері Active Directory не передбачено\&. Це може призвести до отримання значної кількості результатів і викликати реакцію з боку розширення діапазону отримання (Range Retrieval)\&.
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
Якщо увімкнено параметр
\(lqldap_use_tokengroups\(rq, пошуки в Active Directory не буде обмежено \(em він повертатиме усі дані щодо участі у групах, навіть без прив\*(Aqязки до GID\&. Рекомендуємо вимкнути цю можливість, якщо назви груп показуються неправильно\&.
.sp .5v
.RE
.PP
ldap_sudo_search_base (рядок)
.RS 4
Додатковий основний DN, область пошуку і фільтр LDAP для обмеження пошуків LDAP цим типом атрибутів\&.
.sp
синтаксис:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&. Докладніший опис діапазонів наведено у розділі 4\&.5\&.1\&.2 документа http://tools\&.ietf\&.org/html/rfc4511
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади використання цих синтаксичних конструкцій можна знайти у розділі прикладів \(Foldap_search_base\(Fc\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.sp
Будь ласка, зауважте, що підтримки визначення області або фільтра для пошуків на сервері Active Directory не передбачено\&. Це може призвести до отримання значної кількості результатів і викликати реакцію з боку розширення діапазону отримання (Range Retrieval)\&.
.RE
.PP
ldap_autofs_search_base (рядок)
.RS 4
Додатковий основний DN, область пошуку і фільтр LDAP для обмеження пошуків LDAP цим типом атрибутів\&.
.sp
синтаксис:
.sp
.if n \{\
.RS 4
.\}
.nf
search_base[?scope?[filter][?search_base?scope?[filter]]*]
.fi
.if n \{\
.RE
.\}
.sp
Діапазоном може бути одне зі значень, \(Fobase\(Fc (основа), \(Foonelevel\(Fc (окремий рівень) або \(Fosubtree\(Fc (піддерево)\&. Докладніший опис діапазонів наведено у розділі 4\&.5\&.1\&.2 документа http://tools\&.ietf\&.org/html/rfc4511
.sp
Фільтром має бути коректний запис фільтрування LDAP, відповідно до специфікації http://www\&.ietf\&.org/rfc/rfc2254\&.txt
.sp
Приклади використання цих синтаксичних конструкцій можна знайти у розділі прикладів \(Foldap_search_base\(Fc\&.
.sp
Типове значення: значення
\fIldap_search_base\fR
.sp
Будь ласка, зауважте, що підтримки визначення області або фільтра для пошуків на сервері Active Directory не передбачено\&. Це може призвести до отримання значної кількості результатів і викликати реакцію з боку розширення діапазону отримання (Range Retrieval)\&.
.RE
.SH "РЕЗЕРВ"
.PP
Можливість резервування надає змогу модулям обробки автоматично перемикатися на інші сервери, якщо спроба встановлення з\(cqєднання з поточним сервером зазнає невдачі\&.
.SS "Синтаксичні конструкції визначення резервного сервера"
.PP
Список записів серверів, відокремлених комами\&. Між комами можна використовувати довільну кількість пробілів\&. Порядок у списку визначає пріоритет\&. У списку може бути будь\-яка кількість записів серверів\&.
.PP
Для кожного з параметрів налаштування з увімкненим резервним отриманням існує два варіанти:
\fIосновний\fR
і
\fIрезервний\fR\&. Ідея полягає у тому, що сервери з основного списку мають вищий пріоритет за резервні сервери, пошук же на резервних серверах виконується, лише якщо не вдасться з\(cqєднатися з жодним з основних серверів\&. Якщо буде вибрано резервний сервер, встановлюється час очікування у 31 секунду\&. Після завершення часу очікування SSSD періодично намагатиметься повторно встановити з\(cqєднання з основними серверами\&. Якщо спроба буде успішною, поточний активний резервний сервер буде замінено на основний\&.
.SS "Механізм визначення резервного сервера"
.PP
Механізмом резервного використання розрізняються окремі комп\(cqютери і служби\&. Спочатку модуль намагається визначити назву вузла вказаного комп\(cqютера\&. Якщо спроби визначення зазнають невдачі, комп\(cqютер вважатиметься від\(cqєднаним від мережі\&. Подальших спроб встановити з\(cqєднання з цим комп\(cqютером для всіх інших служб не виконуватиметься\&. Якщо вдасться виконати визначення, модуль зробити спробу встановити з\(cqєднання зі службою на визначеному комп\(cqютері\&. Якщо спроба з\(cqєднання зі службою не призведе до успіху, непрацездатною вважатиметься лише служба, модуль автоматично перемкнеться на наступну службу\&. Комп\(cqютер служби вважатиметься з\(cqєднаним з мережею, можливі подальші спроби використання інших служб\&.
.PP
Подальші спроби встановлення з\(cqєднання з комп\(cqютерами або службами, позначеними як такі, що перебувають поза мережею, буде виконано за певний проміжок часу\&. У поточній версії цей проміжок є незмінним і дорівнює 30 секундам\&.
.PP
Якщо список комп\(cqютерів буде вичерпано, основний модуль перейде у режим автономної роботи і повторюватиме спроби з\(cqєднання кожні 30 секунд\&.
.SS "Час очікування на перемикання на резервний ресурс та точне налаштовування"
.PP
Для визначення сервера для з\*(Aqєднання достатньо одного запиту DNS або декількох кроків, зокрема визначення відповідного сайта або спроба використати декілька назв вузлів у випадку, якщо якісь із налаштованих серверів недоступні\&. Складніші сценарії можуть потребувати додаткового часу, а SSSD треба збалансувати надання достатнього часу для завершення процесу визначення і використання притомного часу на виконання цього запиту перед переходом до автономного режиму\&. Якщо діагностичний журнал SSSD показує, що під час визначення сервера перевищено час очікування на з\*(Aqєднання із працездатним сервером, варто змінити значення параметрів часу очікування\&.
.PP
У цьому розділі наведено списки доступних для коригування параметрів\&. Будь ласка, ознайомтеся із їхніми описами за допомогою сторінки підручника
\fBsssd.conf\fR(5)\&.
.PP
dns_resolver_server_timeout
.RS 4
Time in milliseconds that sets how long would SSSD talk to a single DNS server before trying next one\&.
.sp
Типове значення: 1000
.RE
.PP
dns_resolver_op_timeout
.RS 4
Time in seconds to tell how long would SSSD try to resolve single DNS query (e\&.g\&. resolution of a hostname or an SRV record) before trying the next hostname or discovery domain\&.
.sp
Типове значення: 2
.RE
.PP
dns_resolver_timeout
.RS 4
Наскільки довго має чекати SSSD на визначення резервної служби надання даних\&. На внутрішньому рівні визначення такої служби може включати декілька кроків, зокрема визначення адрес запитів DNS SRV або пошук розташування сайта\&.
.sp
Типове значення: 4
.RE
.PP
For LDAP\-based providers, the resolve operation is performed as part of an LDAP connection operation\&. Therefore, also the
\(lqldap_opt_timeout>\(rq
timeout should be set to a larger value than
\(lqdns_resolver_timeout\(rq
which in turn should be set to a larger value than
\(lqdns_resolver_op_timeout\(rq
which should be larger than
\(lqdns_resolver_server_timeout\(rq\&.
.SH "ПОШУК СЛУЖБ"
.PP
За допомогою можливості виявлення служб основні модулі мають змогу автоматично визначати відповідні сервери для встановлення з\(cqєднання на основі даних, отриманих у відповідь на спеціальний запит до DNS\&. Підтримки цієї можливості для резервних серверів не передбачено\&.
.SS "Налаштування"
.PP
Якщо серверів не буде вказано, модуль автоматично використає визначення служб для пошуку сервера\&. Крім того, користувач може використовувати і фіксовані адреси серверів і виявлення служб\&. Для цього слід вставити особливе ключове слово, \(Fo_srv_\(Fc, до списку серверів\&. Пріоритет визначається за вказаним порядком\&. Ця можливість є корисною, якщо, наприклад, користувач надає перевагу використанню виявлення служб, якщо це можливо, з поверненням до використання певного сервера, якщо за допомогою DNS не вдасться виявити жодного сервера\&.
.SS "Назва домену"
.PP
З докладнішими відомостями щодо параметра \(Fodns_discovery_domain\(Fc можна ознайомитися на сторінці підручника (man)
\fBsssd.conf\fR(5)\&.
.SS "Протокол"
.PP
Запитами зазвичай визначається протокол _tcp\&. Виключення документовано у описі відповідного параметра\&.
.SS "Також прочитайте"
.PP
Докладніші відомості щодо механізмів визначення служб можна знайти у RFC 2782\&.
.SH "ВСТАНОВЛЕННЯ ВІДПОВІДНОСТІ ІДЕНТИФІКАТОРІВ"
.PP
Можливість встановлення відповідності ідентифікаторів надає SSSD змогу працювати у режимі клієнта Active Directory без потреби для адміністраторів розширювати атрибути користувача з метою підтримки атрибутів POSIX для ідентифікаторів користувачів та груп\&.
.PP
Зауваження: якщо увімкнено встановлення відповідності ідентифікаторів, атрибути uidNumber та gidNumber буде проігноровано\&. Так зроблено з метою уникання конфліктів між автоматично визначеними та визначеними вручну значеннями\&. Якщо вам потрібно призначити певні значення вручну, вручну доведеться призначати ВСІ значення\&.
.PP
Будь ласка, зауважте, що зміна параметрів налаштувань, пов\(cqязаних із встановленням відповідності ідентифікаторів, призведе до зміни ідентифікаторів користувачів і груп\&. У поточній версії SSSD зміни ідентифікаторів не передбачено, отже, вам доведеться вилучити базу даних SSSD\&. Оскільки кешовані паролі також зберігаються у базі даних, вилучення бази даних слід виконувати, лише якщо сервери розпізнавання є доступними, інакше користувачі не зможуть отримати потрібного їм доступу\&. З метою кешування паролів слід виконати сеанс розпізнавання\&. Для вилучення бази даних недостатньо використання команди
\fBsss_cache\fR(8), процедура має складатися з декількох кроків:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Переконуємося, що віддалені сервери є доступними\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Зупиняємо роботу служби SSSD
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Вилучаємо базу даних
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Запускаємо службу SSSD
.RE
.sp
Крім того, оскільки зміна ідентифікаторів може потребувати коригування інших властивостей системи, зокрема прав власності на файли і каталоги, варто спланувати усе наперед і ретельно перевірити налаштування встановлення відповідності ідентифікаторів\&.
.SS "Алгоритм встановлення відповідності"
.PP
Active Directory надає значення objectSID для всіх об\(cqєктів користувачів і груп у каталозі\&. Таке значення objectSID можна розбити на компоненти, які відповідають профілю домену Active Directory та відносному ідентифікатору (RID) об\(cqєкта користувача або групи\&.
.PP
Алгоритмом встановлення відповідності ідентифікаторів SSSD передбачено поділ діапазону доступних UID на розділи однакових розмірів, які називаються \(Foзрізами\(Fc\&. Кожен зріз відповідає простору, доступному певному домену Active Directory\&.
.PP
Коли SSSD вперше зустрічає запис користувача або групи певного домену, SSSD віддає один з доступних зрізів під цей домен\&. З метою уможливлення відтворення такого призначення зрізів на різних клієнтських системах, зріз вибирається за таким алгоритмом:
.PP
Рядок SID передається алгоритмові murmurhash3 з метою перетворення його на хешоване 32\-бітове значення\&. Для вибору зрізу використовується ціла частина від ділення цього значення на загальну кількість доступних зрізів\&.
.PP
Зауваження: за такого алгоритму можливі збіги за хешем та відповідною цілою частиною від ділення\&. У разі виявлення таких збігів буде вибрано наступний доступних зріз, але це може призвести до неможливості відтворити точно такий самий набір зрізів на інших комп\(cqютерах (оскільки в такому разі на вибір зрізів може вплинути порядок, у якому виконується обробка даних)\&. Якщо ви зіткнулися з подібною ситуацією, рекомендуємо вам або перейти на використання явних атрибутів POSIX у Active Directory (вимкнути встановлення відповідності ідентифікаторів) або налаштувати типовий домен з метою гарантування того, що принаймні цей домен матиме еталонні дані\&. Докладніше про це у розділі \(FoНалаштування\(Fc\&.
.SS "Налаштування"
.PP
Мінімальне налаштовування (у розділі
\(lq[domain/НАЗВА_ДОМЕНУ]\(rq):
.PP
.if n \{\
.RS 4
.\}
.nf
ldap_id_mapping = True
ldap_schema = ad
.fi
.if n \{\
.RE
.\}
.PP
За типових налаштувань буде створено 10000 зрізів, кожен з яких може містити до 200000 ідентифікаторів, починаючи з 2000000 і аж до 2000200000\&. Цього має вистачити для більшості розгорнутих середовищ\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBДодаткові налаштування\fR
.RS 4
.PP
ldap_idmap_range_min (ціле число)
.RS 4
Визначає нижню межу діапазону ідентифікаторів POSIX, які слід використовувати для встановлення відповідності SID користувачів і груп Active Directory\&.
.sp
Зауваження: цей параметр відрізняється від
\(lqmin_id\(rq
тим, що
\(lqmin_id\(rq
працює як фільтр відповідей на запити щодо цього домену, а цей параметр керує діапазоном призначення ідентифікаторів\&. Ця відмінність є мінімальною, але загалом варто визначати
\(lqmin_id\(rq
меншим або рівним
\(lqldap_idmap_range_min\(rq
.sp
Типове значення: 200000
.RE
.PP
ldap_idmap_range_max (ціле число)
.RS 4
Визначає верхню межу діапазону ідентифікаторів POSIX, які слід використовувати для встановлення відповідності SID користувачів і груп Active Directory\&.
.sp
Зауваження: цей параметр відрізняється від
\(lqmax_id\(rq
тим, що
\(lqmax_id\(rq
працює як фільтр відповідей на запити щодо цього домену, а цей параметр керує діапазоном призначення ідентифікаторів\&. Ця відмінність є мінімальною, але загалом варто визначати
\(lqmax_id\(rq
більшим або рівним
\(lqldap_idmap_range_max\(rq
.sp
Типове значення: 2000200000
.RE
.PP
ldap_idmap_range_size (ціле число)
.RS 4
Визначає кількість ідентифікаторів доступних на кожному зі зрізів\&. Якщо розмір діапазону не ділиться націло на мінімальне і максимальне значення, буде створено якомога більше повних зрізів\&.
.sp
ЗАУВАЖЕННЯ: значення цього параметра має бути не меншим за значення максимального запланованого до використання RID на сервері Active Directory\&. Пошук даних та вхід для будь\-яких користувачів з RID, що перевищує це значення, буде неможливим\&.
.sp
Приклад: якщо найсвіжішим доданим користувачем Active Directory є користувач з objectSid=S\-1\-5\-21\-2153326666\-2176343378\-3404031434\-1107, \(Foldap_idmap_range_size\(Fc повинне мати значення, яке є не меншим за 1108, оскільки розмір діапазону дорівнює максимальному SID мінус мінімальний SID плюс 1\&. (Наприклад, 1108 = 1107 \- 0 + 1)\&.
.sp
Для майбутнього можливого розширення важливо все спланувати наперед, оскільки зміна цього значення призведе до зміни усіх прив\(cqязок ідентифікаторів у системі, отже зміни попередніх локальних ідентифікаторів користувачів\&.
.sp
Типове значення: 200000
.RE
.PP
ldap_idmap_default_domain_sid (рядок)
.RS 4
Визначає SID типового домену\&. За допомогою цього параметра можна гарантувати те, що цей домен буде завжди призначено до нульового зрізу у карті ідентифікаторів без використання алгоритму murmurhash описаного вище\&.
.sp
Типове значення: not set
.RE
.PP
ldap_idmap_default_domain (рядок)
.RS 4
Вказати назву типового домену\&.
.sp
Типове значення: not set
.RE
.PP
ldap_idmap_autorid_compat (булеве значення)
.RS 4
Змінює поведінку алгоритму встановлення відповідності ідентифікаторів так, щоб обчислення відбувалися за алгоритмом подібним до алгоритму
\(lqidmap_autorid\(rq
winbind\&.
.sp
Якщо встановлено цей параметр, домени призначатимуться, починаючи з нульового зрізу з поступовим зростанням номерів на кожен додатковий домен\&.
.sp
Зауваження: цей алгоритм є недетерміністичним (залежить від порядку записів користувачів та груп)\&. Якщо з метою сумісності з системою, у якій запущено winbind, буде використано цей алгоритм, варто також скористатися параметром
\(lqldap_idmap_default_domain_sid\(rq
з метою гарантування послідовного призначення принаймні одного домену до нульового зрізу\&.
.sp
Типове значення: False
.RE
.PP
ldap_idmap_helper_table_size (ціле число)
.RS 4
Максимальна кількість вторинних зрізів, яку можна використовувати під час виконання прив\*(Aqязки ідентифікатора UNIX до SID\&.
.sp
Зауваження: під час прив\*(Aqязування SID до ідентифікатора UNIX може бути створено додаткові вторинні зрізи, якщо частини RID SID перебувають поза межами діапазону вже створених вторинних зрізів\&. Якщо значенням ldap_idmap_helper_table_size буде 0, додаткові вторинні зрізи не створюватимуться\&.
.sp
Типове значення: 10
.RE
.RE
.SS "Добре відомі SID"
.PP
У SSSD передбачено підтримку пошуку назв за добре відомими (Well\-Known) SID, тобто SID із особливим запрограмованим призначенням\&. Оскільки типові користувачі і групи, пов\(cqязані із цими добре відомими SID не мають еквівалентів у середовищі Linux/UNIX, ідентифікаторів POSIX для цих об\(cqєктів немає\&.
.PP
Простір назв SID упорядковано службами сертифікації, які виглядають як інші домени\&. Службами сертифікації для добре відомих (Well\-Known) SID є
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Фіктивна служба сертифікації (Null Authority)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Загальна служба сертифікації (World Authority)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Локальна служба сертифікації (Local Authority)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Авторська служба сертифікації (Creator Authority)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Служба сертифікації NT (NT Authority)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Вбудована (Built\-in)
.RE
.sp
Написані літерами верхнього регістру ці назви буде використано як назви доменів для повернення повних назв добре відомих (Well\-Known) SID\&.
.PP
Оскільки деякі з програм надають змогу змінювати дані щодо керування доступом на основі SID за допомогою назви, а не безпосереднього використання, у SSSD передбачено підтримку пошуку SID за назвою\&. Щоб уникнути конфліктів, для пошуку добре відомих (Well\-Known) SID приймаються лише повні назви\&. Отже, не можна використовувати як назви доменів у
sssd\&.conf
такі назви: \(FoNULL AUTHORITY\(Fc, \(FoWORLD AUTHORITY\(Fc, \(FoLOCAL AUTHORITY\(Fc, \(FoCREATOR AUTHORITY\(Fc, \(FoNT AUTHORITY\(Fc та \(FoBUILTIN\(Fc\&.
.SH "ПРИКЛАД"
.PP
У наведеному нижче прикладі припускається, що SSSD налаштовано належним чином, а LDAP встановлено на один з доменів з розділу
\fI[domains]\fR\&.
.PP
.if n \{\
.RS 4
.\}
.nf
[domain/LDAP]
id_provider = ldap
auth_provider = ldap
ldap_uri = ldap://ldap\&.mydomain\&.org
ldap_search_base = dc=mydomain,dc=org
ldap_tls_reqcert = demand
cache_credentials = true
.fi
.if n \{\
.RE
.\}
.sp
.SH "ПРИКЛАД ФІЛЬТРА ДОСТУПУ LDAP"
.PP
У наведеному нижче прикладі припускається, що SSSD налаштовано належним чином і використано ldap_access_order=lockout\&.
.PP
.if n \{\
.RS 4
.\}
.nf
[domain/LDAP]
id_provider = ldap
auth_provider = ldap
access_provider = ldap
ldap_access_order = lockout
ldap_pwdlockout_dn = cn=ppolicy,ou=policies,dc=mydomain,dc=org
ldap_uri = ldap://ldap\&.mydomain\&.org
ldap_search_base = dc=mydomain,dc=org
ldap_tls_reqcert = demand
cache_credentials = true
.fi
.if n \{\
.RE
.\}
.sp
.SH "ЗАУВАЖЕННЯ"
.PP
Описи деяких з параметрів налаштування на цій сторінці підручника засновано на даних сторінки підручника (man)
\fBldap.conf\fR(5)
з пакунка OpenLDAP 2\&.4\&.
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
