'\" t
.\"     Title: sssd-simple
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Формати файлів та правила
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-SIMPLE" "5" "12/09/2020" "SSSD" "Формати файлів та правила"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-simple \- файл налаштувань інструмента керування доступом \(Fosimple\(Fc SSSD
.SH "ОПИС"
.PP
На цій сторінці довідника описано налаштування простого засобу керування доступом для
\fBsssd\fR(8)\&. Щоб дізнатися більше про синтаксис налаштування, зверніться до розділу \(FoФОРМАТ ФАЙЛА\(Fc сторінки довідника
\fBsssd.conf\fR(5)\&.
.PP
Простий засіб керування доступом надає або забороняє доступ на основі списку допуску або заборони, складеного за назвами облікових записів користувачів та групами\&. Використовуються такі правила:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Якщо всі списки є порожніми, доступ буде надано\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Якщо вказано будь\-який зі списків, обробка виконуватиметься за послідовністю \(Foдопуск, потім заборона\(Fc (allow,deny)\&. Це означає, що будь\-яке з правил заборони матиме пріоритет над будь\-яким правилом допуску\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Якщо буде вказано один або обидва списки допуску (\(Foallow\(Fc), всім користувачам поза цими списками доступ буде заборонено\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Якщо буде вказано лише списки заборони (\(Fodeny\(Fc), всі користувачам поза цими списками доступ буде надано\&.
.RE
.sp
.SH "ПАРАМЕТРИ НАЛАШТУВАННЯ"
.PP
Зверніться до розділу \(FoРОЗДІЛИ ДОМЕНІВ\(Fc сторінки довідника (man)
\fBsssd.conf\fR(5), щоб дізнатися більше про налаштування домену SSSD\&.
.PP
simple_allow_users (рядок)
.RS 4
Відокремлений комами список користувачів, яким дозволено вхід до системи\&.
.RE
.PP
simple_deny_users (рядок)
.RS 4
Список користувачів, яким явно заборонено доступ; записи відокремлюються комами\&.
.RE
.PP
simple_allow_groups (рядок)
.RS 4
Відокремлений комами список груп, користувачам яких дозволено вхід до системи\&. Стосується лише груп у межах цього домену SSSD\&. Локальні групи не обробляються\&.
.RE
.PP
simple_deny_groups (рядок)
.RS 4
Відокремлений комами список груп, користувачам яких явно заборонено доступ\&. Стосується лише груп у межах цього домену SSSD\&. Локальні групи не обробляються\&.
.RE
.PP
Якщо не вказувати значень для жодного зі списків, вважатиметься, що параметр не визначено\&. Пам\(cqятайте про це, якщо захочете створити параметри для простого надавача автоматизованими скриптами\&.
.PP
Будь ласка, зауважте, що визначення обох параметрів, simple_allow_users і simple_deny_users, є помилкою у налаштуванні\&.
.SH "ПРИКЛАД"
.PP
У наведеному нижче прикладі припускаємо, що SSSD налаштовано належним чином, а example\&.com є одним з доменів у розділі
\fI[sssd]\fR\&. У прикладі продемонстровано лише параметри, специфічні для простого засобу доступу\&.
.PP
.if n \{\
.RS 4
.\}
.nf
[domain/example\&.com]
access_provider = simple
simple_allow_users = user1, user2
.fi
.if n \{\
.RE
.\}
.sp
.SH "ЗАУВАЖЕННЯ"
.PP
Повна обробка ієрархії участі у групах виконується до перевірки прав доступу, отже, до списку груп доступу може бути включено навіть вкладені групи\&. Будь ласка, зауважте, що на результати може вплинути значення параметра \(Foldap_group_nesting_level\(Fc\&. Вам слід встановити для нього достатнє значення\&. Див\&.
\fBsssd-ldap\fR(5)\&.
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
