'\" t
.\"     Title: sssd.conf
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Формати файлів та правила
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\&.CONF" "5" "12/09/2020" "SSSD" "Формати файлів та правила"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd.conf \- файл налаштування SSSD
.SH "ФОРМАТ ФАЙЛА"
.PP
Файл складено з використанням синтаксичний конструкцій у стилі ini, він складається з розділів і окремих записів параметрів\&. Розділ починається з рядка назви розділу у квадратних дужках і продовжується до початку нового розділу\&. Приклад розділу з параметрами, які мають єдине і декілька значень:
.sp
.if n \{\
.RS 4
.\}
.nf
\fI[розділ]\fR
\fIключ\fR = \fIзначення\fR
\fIключ2\fR = \fIзначення2,значення3\fR
            
.fi
.if n \{\
.RE
.\}
.PP
Типами даних є рядок (без символів лапок), ціле число і булеве значення (можливі два значення \(em
\(lqTRUE\(rq
і
\(lqFALSE\(rq)\&.
.PP
Рядок коментаря починається з символу решітки (\(lq#\(rq) або крапки з комою (\(lq;\(rq)\&. Підтримки вбудованих коментарів не передбачено\&.
.PP
Для всіх розділів передбачено додатковий параметр
\fIdescription\fR\&. Його призначено лише для позначення розділу\&.
.PP
sssd\&.conf
має бути звичайним файлом, власником якого є користувач root\&. Права на читання та запис до цього файла повинен мати лише користувач root\&.
.SH "ФРАГМЕНТИ НАЛАШТУВАНЬ З КАТАЛОГУ ВКЛЮЧЕННЯ"
.PP
До файла налаштувань
sssd\&.conf
буде включено фрагменти налаштувань з каталогу
conf\&.d\&. Цією можливістю можна буде скористатися, якщо SSSD було зібрано із бібліотекою libini версії 1\&.3\&.0 або новішою\&.
.PP
Будь\-який файл, розташований у
conf\&.d, назва якого завершується на
\(lq\&.conf\(rq
і не починається з крапки (\(lq\&.\(rq), буде використано разом із
sssd\&.conf
для налаштовування SSSD\&.
.PP
Фрагменти налаштувань з
conf\&.d
мають вищий пріоритет за
sssd\&.conf, вони мають вищий пріоритет за
sssd\&.conf, якщо виникне конфлікт\&. Якщо у
conf\&.d
буде виявлено декілька фрагментів, їх буде включено за абеткою (на основі параметрів локалі)\&. Файли, які включаються пізніше, мають вищий пріоритет\&. Числові префікси (01_фрагмент\&.conf,
02_фрагмент\&.conf
тощо) можуть допомогти у візуалізації пріоритетності (більше число означає вищу пріоритетність)\&.
.PP
Файли фрагментів мають належати одному користувачеві і мати однакові права доступу із файлом
sssd\&.conf\&. Типовим власником є root:root, а типовими правами доступу \(em 0600\&.
.SH "ЗАГАЛЬНІ ПАРАМЕТРИ"
.PP
Нижче наведено параметри, які можна використовувати у декількох розділах налаштувань\&.
.SS "Параметри, які можна використовувати у всіх розділах"
.PP
.PP
debug_level (ціле число)
.RS 4
У SSSD передбачено два представлення для визначення рівня діагностики\&. Найпростішим є визначення десяткового значення у діапазоні 0\-9\&. Кожному значенню відповідає вмикання відповідного рівня діагностики і усіх нижчих рівнів\&. Точніше визначення вмикання або вимикання (якщо це потрібно) специфічних рівнів можна встановити за допомогою шістнадцяткової бітової маски\&.
.sp
Будь ласка, зауважте, що кожна служба SSSD веде журнал у власному файлі\&. Також зауважте, що вмикання
\(lqdebug_level\(rq
у розділі
\(lq[sssd]\(rq
вмикає діагностику лише для самого процесу sssd, а не для процесів відповідача чи надавача даних\&. Для отримання діагностичних повідомлень слід додати параметр \(Fodebug_level\(Fc до усіх розділів, для яких слід створювати журнал діагностичних повідомлень\&.
.sp
Окрім зміни рівня ведення журналу у файлі налаштувань за допомогою параметра \(Fodebug_level\(Fc, який не змінюється під час роботи, але зміна якого потребує перезапуску SSSD, можна змінити режим діагностики без перезапуску за допомогою програми
\fBsss_debuglevel\fR(8)\&.
.sp
Рівні діагностики, передбачені у поточній версії:
.sp
\fI0\fR,
\fI0x0010\fR: критичні помилки з аварійним завершенням роботи\&. Всі помилки, які не дають SSSD змоги розпочати або продовжувати роботу\&.
.sp
\fI1\fR,
\fI0x0020\fR: критичні помилки\&. Помилки, які не призводять до аварійного завершення роботи SSSD, але означають, що одна з основних можливостей не працює належним чином\&.
.sp
\fI2\fR,
\fI0x0040\fR: серйозні помилки\&. Повідомлення про такі помилки означають, що не вдалося виконати певний запит або дію\&.
.sp
\fI3\fR,
\fI0x0080\fR: незначні помилки\&. Це помилки які можуть призвести до помилок під час виконання дій\&.
.sp
\fI4\fR,
\fI0x0100\fR: параметри налаштування\&.
.sp
\fI5\fR,
\fI0x0200\fR: дані функцій\&.
.sp
\fI6\fR,
\fI0x0400\fR: повідомлення трасування для функцій дій\&.
.sp
\fI7\fR,
\fI0x1000\fR: повідомлення трасування для функцій внутрішнього трасування\&.
.sp
\fI8\fR,
\fI0x2000\fR: вміст внутрішніх змінних функцій, який може бути цікавим\&.
.sp
\fI9\fR,
\fI0x4000\fR: дані трасування найнижчого рівня\&.
.sp
Щоб до журналу було записано дані потрібних бітових масок рівнів діагностики, просто додайте відповідні числа, як це показано у наведених нижче прикладах:
.sp
\fIExample\fR: щоб до журналу було записано дані щодо критичних помилок з аварійним завершенням роботи, критичних помилок, серйозних помилок та дані функцій, скористайтеся рівнем діагностики 0x0270\&.
.sp
\fIПриклад\fR: щоб до журналу було записано критичні помилки з аварійним завершенням роботи, параметри налаштування, дані функцій та повідомлення трасування для функцій внутрішнього керування, скористайтеся рівнем 0x1310\&.
.sp
\fIЗауваження\fR: формат бітових масок для рівнів діагностики впроваджено у версії 1\&.7\&.0\&.
.sp
\fIТипове значення\fR: 0
.RE
.PP
debug (ціле число)
.RS 4
У SSSD 1\&.14 і новіших версіях з міркувань зручності також передбачено альтернативний варіант
\fIdebug\fR
для
\fIdebug_level\fR\&. Якщо вказано одразу обидва варіанти, буде використано варіант
\fIdebug_level\fR\&.
.RE
.PP
debug_timestamps (булеве значення)
.RS 4
Додати часову позначку до діагностичних повідомлень\&. Якщо для запису діагностичного журналу у SSSD увімкнено journald, цей параметр буде проігноровано\&.
.sp
Типове значення: true
.RE
.PP
debug_microseconds (булеве значення)
.RS 4
Додати значення мікросекунд до часової позначки у діагностичних повідомлення\&. Якщо для запису діагностичного журналу у SSSD увімкнено journald, цей параметр буде проігноровано\&.
.sp
Типове значення: false
.RE
.SS "Параметри які можна використовувати у розділах SERVICE та DOMAIN"
.PP
.PP
timeout (ціле число)
.RS 4
Проміжок у секундах між циклами роботи цієї служби\&. Використовується для перевірки працездатності процесу та його змоги відповідати на запити\&. Зауважте, що після трьох пропущених циклів процес перерве своє виконання самостійно\&.
.sp
Типове значення: 10
.RE
.SH "ОСОБЛИВІ РОЗДІЛИ"
.SS "Розділ [sssd]"
.PP
Окремі функції у SSSD виконуються особливими службами SSSD, які запускаються і зупиняються разом SSSD\&. Ці служби керуються окремою службою, яку часто називають \(Foмонітором\(Fc\&. Розділ
\(lq[sssd]\(rq
використовується для налаштування монітора та деяких інших важливих параметрів, зокрема доменів профілів\&.
.PP
\fBПараметри розділу\fR
.PP
config_file_version (ціле число)
.RS 4
Визначає версію синтаксичних конструкцій файла налаштування\&. Для версій SSSD 0\&.6\&.0 та пізніших слід використовувати версію 2\&.
.RE
.PP
services
.RS 4
Список служб, відокремлених комами, які запускаються разом із sssd\&.
.sp
Підтримувані служби: nss, pam
, sudo
, autofs
, ssh
, pac
, ifp
.sp
.RE
.PP
reconnection_retries (ціле число)
.RS 4
Кількість повторних спроб встановлення зв\(cqязку зі службами або їх перезапуску у разі аварійного завершення роботи інструменту надання даних до визнання подальших спроб безнадійними\&.
.sp
Типове значення: 3
.RE
.PP
domains
.RS 4
Домен \(em це база даних, у якій містяться дані щодо користувачів\&. SSSD може одночасно використовувати декілька доменів\&. Вам слід вказати принаймні один домен, інакше SSSD просто не запуститься\&. За допомогою цього параметра можна вказати список доменів, впорядкованих за пріоритетністю під час надсилання до них запитів щодо даних\&. Назва домену має складатися лише з літер і цифр ASCII, дефісів, крапок та знаків підкреслювання\&.
.RE
.PP
re_expression (рядок)
.RS 4
Типовий формальний вираз, який описує спосіб поділу рядка з іменем користувача і доменом на його частини\&.
.sp
Для кожного з доменів можна налаштувати окремий формальний вираз\&. Для деяких з засобів надання ідентифікаторів передбачено типові формальні вирази\&. Докладніше про ці формальні вирази можна дізнатися з довідки до РОЗДІЛІВ ДОМЕНІВ\&.
.RE
.PP
full_name_format (рядок)
.RS 4
Сумісний з
\fBprintf\fR(3)
формат, який описує спосіб створення повного імені на основі імені користувача та компонентів назви домену\&.
.sp
Передбачено використання таких замінників:
.PP
%1$s
.RS 4
ім\(cqя користувача
.RE
.PP
%2$s
.RS 4
назва домену у форматі, вказаному у файлі налаштувань SSSD\&.
.RE
.PP
%3$s
.RS 4
проста назва домену\&. Здебільшого використовується для доменів Active Directory, налаштованих та автоматично виявлених за зв\(cqязками довіри IPA\&.
.RE
.sp
Для кожного з доменів можна налаштувати окремий рядок формату\&. Докладніше про ці рядки можна дізнатися з довідки до РОЗДІЛІВ ДОМЕНІВ\&.
.RE
.PP
monitor_resolv_conf (boolean)
.RS 4
Controls if SSSD should monitor the state of resolv\&.conf to identify when it needs to update its internal DNS resolver\&.
.sp
Типове значення: true
.RE
.PP
try_inotify (булеве значення)
.RS 4
By default, SSSD will attempt to use inotify to monitor configuration files changes and will fall back to polling every five seconds if inotify cannot be used\&.
.sp
Зрідка бажано не вдаватися навіть до спроб скористатися inotify\&. У цих рідкісних випадках слід встановити для цього параметра значення \(Fofalse\(Fc\&.
.sp
Типове значення: \(Fotrue\(Fc на платформах, де підтримується inotify\&. \(Fofalse\(Fc на інших платформах\&.
.sp
Зауваження: цей параметр ні на що не вплине на платформах, де inotify недоступний\&. На цих платформах завжди використовуватиметься безпосереднє опитування файла\&.
.RE
.PP
krb5_rcache_dir (рядок)
.RS 4
Каталог у файловій системі, де SSSD має зберігати файли кешу відтворення Kerberos\&.
.sp
Цей параметр приймає особливе значення __LIBKRB5_DEFAULTS__, за допомогою якого можна наказати SSSD надати змогу libkrb5 визначити відповідну адресу для кешу відтворення\&.
.sp
Типове значення: визначається дистрибутивом та вказується під час збирання\&. (__LIBKRB5_DEFAULTS__, якщо не вказано)
.RE
.PP
user (рядок)
.RS 4
Користувач, до якого слід скинути права доступу, якщо це потрібно для уникнення запуску від імені користувача root\&.
.sp
Типове значення: не встановлено, процес буде запущено від імені root
.RE
.PP
default_domain_suffix (рядок)
.RS 4
Цей рядок буде використано як типову назву домену для всіх назв без компонента назви домену\&. Основним призначенням використання цього рядка є середовища, де основний домен призначено для керування правилами вузлів та всіма користувачами, розташованими на надійному (довіреному) домені\&. За допомогою цього параметра користувачі можуть входити до системи за допомогою лише імені користувача без додавання до нього назви домену\&.
.sp
Please note that if this option is set all users from the primary domain have to use their fully qualified name, e\&.g\&. user@domain\&.name, to log in\&. Setting this option changes default of use_fully_qualified_names to True\&. It is not allowed to use this option together with use_fully_qualified_names set to False\&. One exception from this rule are domains with
\(lqid_provider=files\(rq
that always try to match the behaviour of nss_files and therefore their output is not qualified even when the default_domain_suffix option is used\&.
.sp
Типове значення: not set
.RE
.PP
override_space (рядок)
.RS 4
За допомогою цього параметра можна змінити пробіли у іменах користувачів та назвах груп вказаним симовлом, наприклад _\&. Ім\(cqя користувача \(Fojohn doe\(Fc буде перетворено на \(Fojohn_doe\(Fc\&. Цю можливість було додано для сумісності із скриптами командної оболонки, у яких виникають проблеми із обробкою пробілів через типовий роздільник полів у оболонці\&.
.sp
Будь ласка, зауважте, що використання символу\-замінника, який може бути використано у іменах користувачів і назвах груп, є помилкою у налаштуваннях\&. Якщо назва містить символ\-замінник, SSSD спробує повернути незмінену назву, але, загалом, результат пошуку буде невизначеним\&.
.sp
Типове значення: не встановлено (пробіли не замінятимуться)
.RE
.PP
certificate_verification (рядок)
.RS 4
За допомогою цього параметра можна виконати тонке налаштовування перевірки сертифікатів на основі списку параметрів, відокремлених комами\&. Підтримувані параметри:
.PP
no_ocsp
.RS 4
Вимикає перевірки протоколу стану мережевої сертифікації (Online Certificate Status Protocol або OCSP)\&. Це може знадобитися, якщо сервери OCSP, визначені у сертифікаті, є недоступними з клієнта\&.
.RE
.PP
soft_ocsp
.RS 4
(NSS Version) This option is ignored\&.
.sp
(OpenSSL Version) If a connection cannot be established to an OCSP responder the OCSP check is skipped\&. This option should be used to allow authentication when the system is offline and the OCSP responder cannot be reached\&.
.RE
.PP
ocsp_dgst
.RS 4
Digest (hash) function used to create the certificate ID for the OCSP request\&. Allowed values are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sha1
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sha256
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sha384
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sha512
.RE
.sp
Default: sha256
.sp
(NSS Version) This option is ignored, because NSS uses sha1 unconditionally\&.
.RE
.PP
no_verification
.RS 4
Повністю вимикає перевірку\&. Цим варіантом слід користуватися лише для тестування\&.
.RE
.PP
ocsp_default_responder=URL
.RS 4
Встановлює типовий відповідач OCSP, який слід використовувати замість визначеного у сертифікаті\&. Адресу слід замінити адресою типового відповідача, наприклад http://example\&.com:80/ocsp\&.
.sp
(Версія з NSS) Цей параметр слід використовувати разом із параметром ocsp_default_responder_signing_cert\&.
.RE
.PP
ocsp_default_responder_signing_cert=НАЗВА
.RS 4
(Версія з NSS) Альтернативна назва сертифіката, якому слід довіряти (очікувано) для підписування відповідей OCSP\&. Сертифікат із вказаною альтернативною назвою має зберігатися у базі даних NSS системи\&.
.sp
Цим параметром слід користуватися разом із параметром ocsp_default_responder\&.
.sp
(Версія з OpenSSL) У поточній версії програма ігнорує цей параметр\&. Усі потрібні сертифікати мають бути у файлі PEM, який вказано параметром pam_cert_db_path\&.
.RE
.PP
crl_file=/ШЛЯХ/ДО/ФАЙЛА/CRL
.RS 4
(Версія з NSS) Цей параметр буде проігноровано, будь ласка, див\&.
\fBcrlutil\fR(1), щоб дізнатися про те, як імпортувати список відкликання сертифікатів (CRL) до бази даних NSS\&.
.sp
(Версія з OpenSSL) Використовувати список відкликання сертифікатів (CRL) з вказаного файла під час перевірки сертифіката\&. CRL має бути вказано у форматі PEM, див\&.
\fBcrl\fR(1ssl), щоб дізнатися більше\&.
.RE
.PP
soft_crl
.RS 4
(NSS Version) This option is ignored\&.
.sp
(OpenSSL Version) If a Certificate Revocation List (CRL) is expired ignore the CRL checks for the related certificates\&. This option should be used to allow authentication when the system is offline and the CRL cannot be renewed\&.
.RE
.sp
Цю сторінку підручника було створено для версії NSS\&.
.sp
Обробник параметрів повідомлятиме про невідомі параметри і просто ігноруватиме їх\&.
.sp
Типове значення: не встановлено, тобто перевірка сертифікатів нічим не обмежуватиметься
.RE
.PP
disable_netlink (булеве значення)
.RS 4
Перехоплювачі SSSD у інтерфейсі netlink для стеження за змінами у маршрутах, адресах, посилання та виконання певних дій\&.
.sp
Зміни стану SSSD, спричинені подіями netlink, можуть бути небажаними, їх можна вимкнути встановленням для цього параметра значення \(Fotrue\(Fc
.sp
Типове значення: false (виявлення змін у netlink)
.RE
.PP
enable_files_domain (булеве значення)
.RS 4
Якщо цю можливість увімкнено, SSSD дописуватиме неявний домен із
\(lqid_provider=files\(rq
до усіх явним чином налаштованих доменів\&.
.sp
Типове значення: false
.RE
.PP
domain_resolution_order
.RS 4
Список доменів і піддоменів, відокремлених комами, який визначає порядок пошуку, який використовуватиметься\&. Список не обов\*(Aqязково включатиме усі можливі домени, оскільки пошук у пропущених доменах відбуватиметься у порядку, у якому їх вказано у параметрі налаштування
\(lqdomains\(rq\&. Пошук у піддоменах, яких немає у списку
\(lqlookup_order\(rq, відбуватиметься у випадковому порядку для кожного батьківського домену\&.
.sp
Будь ласка, зауважте, що якщо встановлено цей параметр, для виведення даних усіма командами використовуватиметься повний формат, навіть якщо у вхідних даних були скорочені назви для усіх користувачів, окрім тих, які керуються засобом надання даних файлів\&. Якщо адміністратору потрібні скорочені дані у виведенні, параметр full_name_format можна використати так:
\(lqfull_name_format=%1$s\(rq
Втім, слід пам\*(Aqятати, що під час входу до облікового запису програми часто перетворюють ім\*(Aqя користувача до канонічної форми, викликаючи програму
\fBgetpwnam\fR(3), яка, якщо повернуто скорочену назву для повних вхідних даних (під час спроби обробки даних користувача, запис якого існує у декількох доменах) може переспрямувати спробу входу до домену, де використовуються скорочені назви, і знівелює цей обхідний маневр, якщо імена користувачів у різних доменах можуть бути однаковими\&.
.sp
Типове значення: не встановлено
.RE
.SH "РОЗДІЛИ СЛУЖБ"
.PP
У цьому розділі описано параметри, якими можна скористатися для налаштування різноманітних служб\&. Ці параметри має бути зібрано у розділах з назвами [\fI$NAME\fR]\&. Наприклад, параметри служби NSS зібрано у розділі
\(lq[nss]\(rq
.SS "Загальні параметри налаштування служб"
.PP
Цими параметрами можна скористатися для налаштування будь\-яких служб\&.
.PP
reconnection_retries (ціле число)
.RS 4
Кількість повторних спроб встановлення зв\(cqязку зі службами або їх перезапуску у разі аварійного завершення роботи інструменту надання даних до визнання подальших спроб безнадійними\&.
.sp
Типове значення: 3
.RE
.PP
fd_limit
.RS 4
За допомогою цього параметра можна визначити максимальну кількість дескрипторів файлів, які одночасно може бути відкрито цим процесом SSSD\&. У системах, де SSSD надано можливості CAP_SYS_RESOURCE, цей параметр використовуватиметься незалежно від інших параметрів системи\&. У системах без цієї можливості, кількість дескрипторів визначатиметься найменшим зі значень цього параметра і обмеженням "hard" у limits\&.conf\&.
.sp
Типове значення: 8192 (або обмеження у limits\&.conf "hard")
.RE
.PP
client_idle_timeout
.RS 4
За допомогою цього параметра можна визначити кількість секунд, протягом яких клієнтська частина SSSD може утримувати дескриптор файла без здійснення за його допомогою обміну даними\&. Таке обмеження потрібне для того, щоб уникнути вичерпання ресурсів системи\&. Час очікування не може бути меншим за 10 секунд\&. Якщо у налаштуваннях вказано менше значення, його буде скориговано до 10 секунд\&.
.sp
Типове значення: 60
.RE
.PP
offline_timeout (ціле число)
.RS 4
Коли SSSD перемикається на автономний режим роботи, час, який має минути, перш ніж буде здійснено спробу повернутися до режиму у мережі, збільшуватиметься, відповідно до часу, проведеного у режимі від\(cqєднання\&. Це значення вказується у секундах і обчислюється за такою формулою:
.sp
час_очікування_для_переходу_у_автономний_режим + випадковий_зсув
.sp
Випадковий зсув може збільшувати час на інтервал до 30 секунд\&. Після кожної невдалої спроби переходу до режиму у мережі новий інтервал часу обчислюється таким чином:
.sp
новий_інтервал = старий_інтервал*2 + випадковий_зсув
.sp
Зауважте, що максимальна тривалість кожного з інтервалів у поточній версії обмежено однією годиною\&. Якщо обчислена тривалість нового інтервалу перевищує годину, буде встановлено інтервал у одну годину\&.
.sp
Типове значення: 60
.RE
.PP
responder_idle_timeout
.RS 4
Цей параметр визначає кількість секунд, протягом яких процес відповідача SSSD може працювати без використання\&. Це значення обмежено з метою уникнення вичерпання ресурсів системи\&. Мінімальним прийнятним значенням для цього параметра є 60 секунд\&. Встановлення для цього параметра значення 0 (нуль) означає, що для відповідача не встановлюватиметься ніякого часу очікування\&. Цей параметр враховуватиметься, лише якщо SSSD зібрано з підтримкою systemd і якщо служби активуються за допомогою або сокетів або D\-Bus\&.
.sp
Типове значення: 300
.RE
.PP
cache_first
.RS 4
Цей параметр визначає, чи слід відповідачеві опитати усі кеші до надсилання запису до модулів засобів надання даних\&.
.sp
Типове значення: false
.RE
.SS "Параметри налаштування NSS"
.PP
Цими параметрами можна скористатися для налаштування служби Name Service Switch (NSS або перемикання служби визначення назв)\&.
.PP
enum_cache_timeout (ціле число)
.RS 4
Тривалість зберігання переліків (запитів щодо даних всіх користувачів) у кеші nss_sss у секундах
.sp
Типове значення: 120
.RE
.PP
entry_cache_nowait_percentage (ціле число)
.RS 4
Можна встановити кеш записів для автоматичного оновлення записів у фоновому режимі, якщо запит щодо них надходить у визначений у відсотках від entry_cache_timeout для домену період часу\&.
.sp
Наприклад, якщо entry_cache_timeout домену встановлено у значення 30s, а entry_cache_nowait_percentage \(em у значення 50 (у відсотках), записи, які надійдуть за 15 секунд після останнього оновлення кешу, буде повернуто одразу, але SSSD оновить власний кеш, отже наступні запити очікуватимуть на розблокування після оновлення кешу\&.
.sp
Коректними значеннями цього параметра є 0\-99\&. Ці значення відповідають відсоткам entry_cache_timeout для кожного з доменів\&. З міркувань покращення швидкодії це відсоткове значення ніколи не зменшуватиме час очікування nowait до значення, меншого за 10 секунд\&. Визначення значення 0 вимкне цю можливість\&.
.sp
Типове значення: 50
.RE
.PP
entry_negative_timeout (ціле число)
.RS 4
Визначає кількість секунд, протягом яких nss_sss має кешувати негативні результати пошуку у кеші (тобто запити щодо некоректних записів у базі даних, зокрема неіснуючих) перед повторним запитом до сервера обробки\&.
.sp
Типове значення: 15
.RE
.PP
local_negative_timeout (ціле число)
.RS 4
Визначає кількість секунд, протягом яких nss_sss має зберігати негативні результати пошуку у кеші користувачів і груп, перші ніж намагатися знову шукати їх за допомогою модуля надання даних\&. Встановлення значення 0 вимикає цю можливість\&.
.sp
Типове значення: 14400 (4 години)
.RE
.PP
filter_users, filter_groups (рядок)
.RS 4
Виключити певних користувачів або групи зі списку отримання даних з бази даних NSS sss\&. Таке виключення може бути корисним для облікових записів керування системою\&. Цей параметр також можна встановлювати для кожного з доменів окремо або включити до нього імена користувачів повністю для обмеження списку користувачами лише з певного домену або за назвою реєстраційного запису користувача (UPN)\&.
.sp
ЗАУВАЖЕННЯ: параметр filter_groups не впливає на успадкованість вкладених записів групи, оскільки фільтрування відбувається після їх передавання для повернення за допомогою NSS\&. Наприклад, у списку групи, що містить вкладену групу, яку відфільтровано, залишатимуться записи користувачів відфільтрованої групи\&.
.sp
Типове значення: root
.RE
.PP
filter_users_in_groups (булеве значення)
.RS 4
Якщо ви хочете, щоб фільтровані користувачі залишалися учасниками груп, встановіть для цього параметра значення \(Fofalse\(Fc\&.
.sp
Типове значення: true
.RE
.PP
override_homedir (рядок)
.RS 4
Перевизначити домашній каталог користувача\&. Ви можете вказати абсолютне значення або шаблон\&. У шаблоні можна використовувати такі замінники:
.PP
%u
.RS 4
ім\*(Aqя користувача
.RE
.PP
%U
.RS 4
номер UID
.RE
.PP
%d
.RS 4
назва домену
.RE
.PP
%f
.RS 4
ім\(cqя користувача повністю (користувач@домен)
.RE
.PP
%l
.RS 4
Перша літера назви облікового запису\&.
.RE
.PP
%P
.RS 4
UPN \- User Principal Name (ім\(cqя@ОБЛАСТЬ)
.RE
.PP
%o
.RS 4
Початкова домашня тека, отримана від служби профілів\&.
.RE
.PP
%H
.RS 4
Значення параметра налаштовування
\fIhomedir_substring\fR\&.
.RE
.PP
%%
.RS 4
символ відсотків (\(Fo%\(Fc)
.RE
.sp
Значення цього параметра можна встановлювати для кожного з доменів окремо\&.
.sp
приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
override_homedir = /home/%u
        
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: не встановлено (SSSD використовуватиме значення, отримане від LDAP)
.RE
.PP
homedir_substring (рядок)
.RS 4
Значення цього параметра буде використано під час розгортання параметра
\fIoverride_homedir\fR, якщо у шаблоні міститься рядок форматування
\fI%H\fR\&. Запис каталогу LDAP може безпосередньо містити цей шаблон для розгортання шляху до домашнього каталогу на кожному з клієнтських комп\(cqютерів (або у кожній з операційних систем)\&. Значення параметра можна вказати окремо для кожного з доменів або на загальному рівні у розділі [nss]\&. Значення, вказане у розділі домену, має вищий пріоритет за значення, встановлене за допомогою розділу [nss]\&.
.sp
Типове значення: /home
.RE
.PP
fallback_homedir (рядок)
.RS 4
Встановити типовий шаблон назви домашнього каталогу користувача, якщо цей каталог не вказано явним чином засобом надання даних домену\&.
.sp
Можливі варіанти значень для цього параметра збігаються з варіантами значень для параметра override_homedir\&.
.sp
приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
fallback_homedir = /home/%u
                            
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: не встановлено (без замін для невстановлених домашніх каталогів)
.RE
.PP
override_shell (рядок)
.RS 4
Перевизначити командну оболонку входу до системи для усіх користувачів\&. Цей параметр має пріоритет над будь\-якими іншими параметрами визначення командної оболонки, якщо він діє\&. Його можна встановити або у розділі [nss] або для кожного з доменів окремо\&.
.sp
Типове значення: не встановлено (SSSD використовуватиме значення, отримане від LDAP)
.RE
.PP
allowed_shells (рядок)
.RS 4
Обмежити перелік можливих командних оболонок користувачів вказаними\&. Порядок визначення оболонки є таким:
.sp
1\&. Якщо оболонку вказано у
\(lq/etc/shells\(rq, її буде використано\&.
.sp
2\&. Якщо оболонку вказано у списку allowed_shells, але її немає у списку
\(lq/etc/shells\(rq, буде використано значення параметра shell_fallback\&.
.sp
3\&. Якщо оболонку не вказано у списку allowed_shells і її немає у списку
\(lq/etc/shells\(rq, буде використано оболонку nologin\&.
.sp
Для визначення будь\-якої командної оболонки можна скористатися шаблоном заміни (*)\&.
.sp
Значенням (*) варто користуватися, якщо ви хочете скористатися shell_fallback, коли командної оболонки користувача немає у \(Fo/etc/shells\(Fc, а супровід списку усіх командних оболонок у allowed_shells є надто марудною справою\&.
.sp
Порожній рядок оболонки буде передано без обробки до libc\&.
.sp
Читання
\(lq/etc/shells\(rq
виконується лише під час запуску SSSD, тобто у разі встановлення нової оболонки слід перезапустити SSSD\&.
.sp
Типове значення: не встановлено\&. Автоматично використовується оболонка користувача\&.
.RE
.PP
vetoed_shells (рядок)
.RS 4
Замінити всі записи цих оболонок на shell_fallback
.RE
.PP
shell_fallback (рядок)
.RS 4
Типова оболонка, яку слід використовувати, якщо дозволеної оболонки у системі не встановлено\&.
.sp
Типове значення: /bin/sh
.RE
.PP
default_shell
.RS 4
Типова командна оболонка, яку буде використано, якщо засобом надання даних не було повернуто назви оболонки під час пошуку\&. Цей параметр можна вказати або на загальному рівні у розділі [nss], або окремо для кожного з доменів\&.
.sp
Типове значення: не встановлено (повернути NULL, якщо оболонку не встановлено і покластися на libc у визначенні потрібного програмі значення, зазвичай /bin/sh)
.RE
.PP
get_domains_timeout (ціле число)
.RS 4
Визначає час у секундах, протягом якого список піддоменів вважатиметься чинним\&.
.sp
Типове значення: 60
.RE
.PP
memcache_timeout (ціле число)
.RS 4
Визначає час у секундах, протягом якого список піддоменів вважатиметься чинним\&. Встановлення для цього параметра нульового значення вимикає кеш у пам\*(Aqяті\&.
.sp
Типове значення: 300
.sp
Попередження: вимикання кешу у пам\*(Aqяті значно погіршить швидкодію SSSD, ним варто користуватися лише для тестування\&.
.sp
ЗАУВАЖЕННЯ: якщо для змінної середовища SSS_NSS_USE_MEMCACHE встановлено значення \(FoNO\(Fc, клієнтські програми не використовуватимуть fast у кеші у пам\(cqяті\&.
.RE
.PP
user_attributes (рядок)
.RS 4
Деякі із додаткових запитів до відповідача NSS можуть повертати більшу кількість атрибутів, ніж це визначено POSIX для інтерфейсу NSS\&. Списком атрибутів можна керувати за допомогою цього параметра\&. Обробка виконується у той самий спосіб, що і для параметра \(Fouser_attributes\(Fc відповідача InfoPipe (див\&.
\fBsssd-ifp\fR(5), щоб дізнатися більше), але без типових значень\&.
.sp
Щоб полегшити налаштовування відповідач NSS перевірятиме параметр InfoPipe на те, чи не встановлено його для відповідача NSS\&.
.sp
Типове значення: не встановлено, резервне значення визначається за параметром InfoPipe
.RE
.PP
pwfield (рядок)
.RS 4
Значення, яке повертають операції NSS, які повертають записи користувачів чи груп, для поля
\(lqpassword\(rq\&.
.sp
Значення цього параметра можна встановлювати для кожного з доменів окремо\&.
.sp
Типове значення:
\(lq*\(rq
(віддалені домени) або
\(lqx\(rq
(файловий домен)
.RE
.SS "Параметри налаштування PAM"
.PP
Цими параметрами можна скористатися для налаштування служби Pluggable Authentication Module (PAM або блокового модуля розпізнавання)\&.
.PP
offline_credentials_expiration (ціле число)
.RS 4
У разі неможливості встановлення з\(cqєднання з сервером розпізнавання визначає тривалість зберігання кешованих входів (у днях з часу останнього успішного входу до системи)\&.
.sp
Типове значення: 0 (без обмежень)
.RE
.PP
offline_failed_login_attempts (ціле число)
.RS 4
У разі неможливості встановлення з\(cqєднання з сервером розпізнавання визначає дозволену кількість спроб входу з визначенням помилкового пароля\&.
.sp
Типове значення: 0 (без обмежень)
.RE
.PP
offline_failed_login_delay (ціле число)
.RS 4
Час у хвилинах, який має пройти між досягненням значення offline_failed_login_attempts і повторним вмиканням можливості входу до системи\&.
.sp
Якщо встановлено значення 0, користувач не зможе пройти розпізнавання у автономному режимі, якщо буде досягнуто значення offline_failed_login_attempts\&. Лише успішне розпізнавання може знову увімкнути можливість автономного розпізнавання\&.
.sp
Типове значення: 5
.RE
.PP
pam_verbosity (ціле число)
.RS 4
Керує типами повідомлень, які буде показано користувачеві під час розпізнавання\&. Чим більшим є значення, тим більше повідомлень буде показано\&.
.sp
У поточній версії sssd передбачено підтримку таких значень:
.sp
\fI0\fR: не показувати жодних повідомлень
.sp
\fI1\fR: показувати лише важливі повідомлення
.sp
\fI2\fR: показувати всі інформаційні повідомлення
.sp
\fI3\fR: показувати всі повідомлення та діагностичні дані
.sp
Типове значення: 1
.RE
.PP
pam_response_filter (ціле число)
.RS 4
Список рядків, відокремлених комами, за допомогою якого можна вилучати (фільтрувати) дані, які надсилаються відповідачем PAM до модуля PAM pam_sss\&. Існують різні тип відповідей, які надсилаються до pam_sss, наприклад повідомлення, які показуються користувачеві, або змінні середовища, які слід встановлювати за допомогою pam_sss\&.
.sp
Хоча повідомленнями вже можна керувати за допомогою параметра pam_verbosity, за допомогою цього параметра можна відфільтрувати також інші типи повідомлень\&.
.sp
У поточній версії передбачено підтримку таких фільтрів:
.PP
ENV
.RS 4
Не надсилати жодних змінних середовища до жодної служби\&.
.RE
.PP
ENV:назва_змінної
.RS 4
Не надсилати змінної середовища назва_змінної до жодної служби\&.
.RE
.PP
ENV:назва_змінної:служба
.RS 4
Не надсилати змінної середовища назва_змінної до вказаної служби\&.
.RE
.sp
Типове значення: not set
.sp
Приклад: ENV:KRB5CCNAME:sudo\-i
.RE
.PP
pam_id_timeout (ціле число)
.RS 4
Для кожного з запитів PAM під час роботи SSSD система SSSD зробить спробу негайно оновити кешовані дані щодо профілю користувача з метою переконатися, що розпізнавання виконується на основі найсвіжіших даних\&.
.sp
Повний обмін даними сеансу PAM може включати декілька запитів PAM, зокрема для керування обліковими записами та відкриття сеансів\&. За допомогою цього параметра можна керувати (для окремих клієнтів\-програм) тривалістю (у секундах) кешування даних профілю з метою уникнути повторних викликів засобу надання даних профілів\&.
.sp
Типове значення: 5
.RE
.PP
pam_pwd_expiration_warning (ціле число)
.RS 4
Показати попередження за вказану кількість днів перед завершенням дії пароля\&.
.sp
Будь ласка, зауважте, що сервер обробки має надати дані щодо часу завершення дії пароля\&. Якщо ці дані не буде виявлено, sssd не зможе показати попередження\&.
.sp
Якщо встановлено нульове значення, цей фільтр не застосовуватиметься, тобто якщо з сервера обробки надійде попередження щодо завершення строку дії, його буде автоматично показано\&.
.sp
Цей параметр може бути перевизначено встановленням параметра
\fIpwd_expiration_warning\fR
для окремого домену\&.
.sp
Типове значення: 0
.RE
.PP
get_domains_timeout (ціле число)
.RS 4
Визначає час у секундах, протягом якого список піддоменів вважатиметься чинним\&.
.sp
Типове значення: 60
.RE
.PP
pam_trusted_users (рядок)
.RS 4
Визначає список відокремлених комами значень UID або імен користувачів, яким дозволено виконувати обмін даними PAM із довіреними доменами\&. Користувачі, яких не включено до цього списку, можуть отримувати доступ лише до доменів, які позначено як загальнодоступні (public) за допомогою
\(lqpam_public_domains\(rq\&. Імена користувачів перетворюються на UID під час запуску системи\&.
.sp
Типове значення: типово усі користувачі вважаються надійними (довіреними)
.sp
Будь ласка, зауважте, що користувачеві з UID 0 завжди мають доступ до відповідача PAM, навіть якщо користувача немає у списку pam_trusted_users\&.
.RE
.PP
pam_public_domains (рядок)
.RS 4
Визначає список назв доменів, відокремлених комами, доступ до яких можуть отримувати навіть ненадійні користувачі\&.
.sp
Визначено два спеціальних значення параметра pam_public_domains:
.sp
all (Ненадійним користувачам відкрито доступ до усіх доменів у відповідачі PAM\&.)
.sp
none (Ненадійним користувачам заборонено доступ до усіх доменів PAM у відповідачі\&.)
.sp
Типове значення: none
.RE
.PP
pam_account_expired_message (рядок)
.RS 4
Надає змогу встановити нетипове повідомлення щодо завершення строку дії, яке замінити типове повідомлення \(FoДоступ заборонено\(Fc (\(FoPermission denied\(Fc)\&.
.sp
Зауваження: будь ласка, зверніть увагу на те, що повідомлення буде виведено для служби SSH, лише якщо pam_verbosity не встановлено у значення 3 (показувати усі повідомлення і діагностичні дані)\&.
.sp
приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
pam_account_expired_message = Account expired, please contact help desk\&.
                            
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: none
.RE
.PP
pam_account_locked_message (рядок)
.RS 4
Надає змогу встановити нетипове повідомлення щодо блокування, яке замінити типове повідомлення \(FoДоступ заборонено\(Fc (\(FoPermission denied\(Fc)\&.
.sp
приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
pam_account_locked_message = Account locked, please contact help desk\&.
                            
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: none
.RE
.PP
pam_cert_auth (булеве значення)
.RS 4
Увімкнути сертифікацію на основі розпізнавання за смарткартками\&. Оскільки це потребує додаткового обміну даним із смарткарткою, що затримує процес розпізнавання, типово таку сертифікацію вимкнено\&.
.sp
Типове значення: False
.RE
.PP
pam_cert_db_path (рядок)
.RS 4
Шлях до бази даних сертифікатів, яка містить модулі PKCS#11 для доступу до смарткартки\&.
.sp
Типове значення:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/etc/pki/nssdb (версія NSS, шлях до бази даних NSS)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/etc/sssd/pki/sssd_auth_ca_db\&.pem (версія OpenSSL, шлях до файла із довіреними сертифікатами служб сертифікації у форматі PEM)
.RE
.sp
Цю сторінку підручника було створено для версії NSS\&.
.RE
.PP
p11_child_timeout (ціле число)
.RS 4
Час у секундах, протягом якого pam_sss очікуватиме на завершення роботи p11_child\&.
.sp
Типове значення: 10
.RE
.PP
pam_app_services (рядок)
.RS 4
Визначає, яким службам PAM дозволено встановлювати з\*(Aqєднання із доменами типу
\(lqapplication\(rq
.sp
Типове значення: не встановлено
.RE
.PP
pam_p11_allowed_services (ціле число)
.RS 4
Список назв служб PAM, відокремлених комами, для яких буде дозволено використання смарткарток\&.
.sp
Можна додати іншу назву служби PAM до типового набору за допомогою конструкції \(Fo+назва_служби\(Fc або явним чином вилучити назву служби PAM з типового набору за допомогою конструкції \(Fo\-назва_служби\(Fc\&. Наприклад, щоб замінити типову назву служби PAM для розпізнавання за смарткарткою (наприклад, \(Fologin\(Fc) з нетиповою назвою служби PAM (наприклад, \(Fomy_pam_service\(Fc), вам слід скористатися такими налаштуваннями:
.sp
.if n \{\
.RS 4
.\}
.nf
pam_p11_allowed_services = +my_pam_service, \-login
                            
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: типовий набір назв служб PAM складається з таких значень:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
login
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
su
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
su\-l
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gdm\-smartcard
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gdm\-password
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
kdm
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sudo
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sudo\-i
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gnome\-screensaver
.RE
.sp
.RE
.PP
p11_wait_for_card_timeout (ціле число)
.RS 4
Якщо обов\*(Aqязковим є розпізнавання за смарткарткою, кількість додаткових секунд, які буде додано до p11_child_timeout, протягом яких відповідача PAM має чекати на вставлення смарткартки\&.
.sp
Типове значення: 60
.RE
.PP
p11_uri (рядок)
.RS 4
Адреса PKCS#11 (докладніший опис можна знайти у RFC\-7512), якою можна скористатися для обмеження переліку пристроїв, які використовуються для розпізнавання за допомогою смарткартки\&. Типово, p11_child зі складу SSSD виконуватиме пошук слоту PKCS#11 (зчитувача), для якого встановлено прапорці \(Foremovable\(Fc (\(Foпортативний\(Fc) і читатиме сертифікати із першого знайденого слоту вставленого ключа\&. Якщо з комп\*(Aqютером буде з\*(Aqєднано декілька зчитувачів, можна скористатися p11_uri для повідомлення p11_child про те, що слід використовувати вказаний зчитувач\&.
.sp
Приклади:
.sp
.if n \{\
.RS 4
.\}
.nf
p11_uri = slot\-description=My%20Smartcar%20Reader
                            
.fi
.if n \{\
.RE
.\}
.sp
або
.sp
.if n \{\
.RS 4
.\}
.nf
p11_uri = library\-description=OpenSC%20smartcard%20framework;slot\-id=2
                            
.fi
.if n \{\
.RE
.\}
.sp
Для визначення відповідної адреси, ознайомтеся із файлом діагностичних даних p11_child\&. Крім того, можна скористатися програмою GnuTLS p11tool, наприклад, із параметром \-\-list\-all, який покаже і адреси PKCS#11\&.
.sp
Типове значення: none
.RE
.SS "Параметри налаштування SUDO"
.PP
Цими параметрами можна скористатися для налаштовування служби sudo\&. Докладні настанови щодо налаштовування
\fBsudo\fR(8)
на роботу з
\fBsssd\fR(8)
можна знайти на сторінці довідника
\fBsssd-sudo\fR(5)\&.
.PP
sudo_timed (булеве значення)
.RS 4
Визначає, чи слід обробляти атрибути sudoNotBefore і sudoNotAfter, призначені для визначення часових обмежень для записів sudoers\&.
.sp
Типове значення: false
.RE
.PP
sudo_threshold (ціле число)
.RS 4
Максимальна кількість застарілих правил, які можна оновлювати за один крок\&. Якщо кількість застарілих правил є нижчою за це порогове значення, правила буде оновлено за допомогою механізму
\(lqrules refresh\(rq\&. Якщо порогове значення перевищено, замість нього буде використано
\(lqfull refresh\(rq
з правил sudo\&. Це порогове значення також стосується команди sudo IPA та групових пошуків команд\&.
.sp
Типове значення: 50
.RE
.SS "Параметри налаштування AUTOFS"
.PP
Цими параметрами можна скористатися для налаштування служби autofs\&.
.PP
autofs_negative_timeout (ціле число)
.RS 4
Визначає кількість секунд, протягом яких відповідач autofs має кешувати негативні результати пошуку у кеші (тобто запити щодо некоректних записів у базі даних, зокрема неіснуючих) перед повторним запитом до сервера обробки\&.
.sp
Типове значення: 15
.RE
.PP
Будь ласка, зауважте, що засіб автоматичного монтування читає основну карту лише під час запуску, отже якщо до ssd\&.conf внесено будь\-які пов\(cqязані з autofs зміни, типово слід перезапустити фонову службу автоматичного монтування після перезапуску SSSD\&.
.SS "Параметри налаштувань SSH"
.PP
Цими параметрами можна скористатися для налаштування служби SSH\&.
.PP
ssh_hash_known_hosts (булеве значення)
.RS 4
Чи слід хешувати назви та адреси вузлів у керованому файлі known_hosts\&.
.sp
Типове значення: true
.RE
.PP
ssh_known_hosts_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких запису вузла зберігатиметься у керованому файлі known_hosts після надсилання запиту щодо ключів вузла\&.
.sp
Типове значення: 180
.RE
.PP
ssh_use_certificate_keys (булеве значення)
.RS 4
Якщо встановлено значення true,
\fBsss_ssh_authorizedkeys\fR
поверне ключі ssh, які походять від відкритого ключа сертифікатів X\&.509, які також зберігаються у записі користувача\&. Докладніше про це на сторінці підручника
\fBsss_ssh_authorizedkeys\fR(1)\&.
.sp
Типове значення: true
.RE
.PP
ssh_use_certificate_matching_rules (string)
.RS 4
By default the ssh responder will use all available certificate matching rules to filter the certificates so that ssh keys are only derived from the matching ones\&. With this option the used rules can be restricted with a comma separated list of mapping and matching rule names\&. All other rules will be ignored\&.
.sp
If a non\-existing rule name is given all rules will be ignored and all available certificates will be used to derive ssh keys\&.
.sp
Default: not set, all found rules are used
.RE
.PP
ca_db (рядок)
.RS 4
Шлях до сховища довірених сертифікатів CA\&. Параметр використовується для перевірки сертифікатів користувачів до отримання з них відкритих ключів ssh\&.
.sp
Типове значення:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/etc/pki/nssdb (версія NSS, шлях до бази даних NSS)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/etc/sssd/pki/sssd_auth_ca_db\&.pem (версія OpenSSL, шлях до файла із довіреними сертифікатами служб сертифікації у форматі PEM)
.RE
.sp
Цю сторінку підручника було створено для версії NSS\&.
.RE
.SS "Параметри налаштування відповідача PAC"
.PP
Відповідач PAC працює разом з додатком даних уповноваження для sssd_pac_plugin\&.so зі складу MIT Kerberos та засобу надання даних піддоменів\&. Цей додаток надсилає до відповідача PAC дані PAC під час розпізнавання за допомогою GSSAPI\&. Засіб надання даних піддоменів збирає дані щодо діапазонів SID і ID домену, до якого долучено клієнт, та віддалених надійних доменів з локального контролера доменів\&. Якщо PAC декодовано і визначено, виконуються деякі з таких дій:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Якщо у кеші немає даних віддаленого користувача, запис цих даних буде створено\&. UID буде визначено за допомогою SID, надійні домени матимуть UPG, а gid матиме те саме значення, що і UID\&. Дані домашнього каталогу буде засновано на значенні параметра subdomain_homedir\&. Типово, для командної оболонки буде вибрано порожнє значення, тобто використовуватимуться типові параметри системи\&. Значення для оболонки можна змінити за допомогою параметра default_shell\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Якщо існують SID груп з доменів, про які відомо SSSD, запис користувача буде додано до цих груп\&.
.RE
.PP
Цими параметрами можна скористатися для налаштовування відповідача PAC\&.
.PP
allowed_uids (рядок)
.RS 4
Визначає список значень UID або імен користувачів, відокремлених комами\&. Користувачам з цього списку буде дозволено доступ до відповідача PAC\&. UID за іменами користувачів визначатимуться під час запуску\&.
.sp
Типове значення: 0 (доступ до відповідача PAC має лише адміністративний користувач (root))
.sp
Будь ласка, зауважте, що хоча типово використовується UID 0, значення UID буде перевизначено на основі цього параметра\&. Якщо ви хочете надати адміністративному користувачеві (root) доступ до відповідача PAC, що може бути типовим варіантом, вам слід додати до списку UID з правами доступу запис 0\&.
.RE
.PP
pac_lifetime (ціле число)
.RS 4
Строк дії запису PAC у секундах\&. Якщо PAC є чинним, дані PAC можна використовувати для визначення членства користувача у групі\&.
.sp
Типове значення: 300
.RE
.SS "Параметри налаштовування запису сеансів"
.PP
Запис сеансів працює у зв\*(Aqязці з
\fBtlog-rec-session\fR(8), частиною пакунка tlog, для запису даних, які бачать і вводять користувачі після входу до текстового термінала\&. Див\&. також
\fBsssd-session-recording\fR(5)\&.
.PP
Цими параметрами можна скористатися для налаштовування запису сеансів\&.
.PP
scope (рядок)
.RS 4
Один із вказаних нижче рядків, що визначають область запису сеансів:
.PP
"none"
.RS 4
Користувачі не записуються\&.
.RE
.PP
"some"
.RS 4
Запис вестиметься для користувачів і груп, вказаних параметрами
\fIкористувачі\fR
і
\fIгрупи\fR\&.
.RE
.PP
"all"
.RS 4
Усі користувачі записуються\&.
.RE
.sp
Типове значення: none
.RE
.PP
users (рядок)
.RS 4
Список відокремлених комами записів користувачів, для яких увімкнено записування сеансів\&. Належність до списку визначатиметься за іменами, повернутими NSS, тобто після можливих замін пробілів, змін регістру символів тощо\&.
.sp
Типове значення: порожнє\&. Не відповідає жодному користувачу\&.
.RE
.PP
groups (рядок)
.RS 4
Список відокремлених комами записів груп, для користувачів яких буде увімкнено записування сеансів\&. Належність до списку визначатиметься за назвами, повернутими NSS, тобто після можливих замін пробілів, змін регістру символів тощо\&.
.sp
Зауваження: використання цього параметра (встановлення для нього будь\-якого значення) значно впливає на швидкодію, оскільки некешований запит щодо користувача потребує отримання і встановлення відповідності груп, до яких належить користувач\&.
.sp
Типове значення: порожнє\&. Не відповідає жодній групі\&.
.RE
.SH "РОЗДІЛИ ДОМЕНІВ"
.PP
Ці параметри налаштування може бути вказано у розділі налаштування домену, тобто у розділі з назвою
\(lq[domain/\fIНАЗВА\fR]\(rq
.PP
domain_type (рядок)
.RS 4
Визначає, чи призначено домен для використання клієнтами у стандарті POSIX, зокрема NSS, або програмами, які не потребують наявності або створення даних POSIX\&. Інтерфейсам та інструментам операційних систем доступні лише об\*(Aqєкти з доменів POSIX\&.
.sp
Дозволеними значеннями цього параметра є
\(lqposix\(rq
і
\(lqapplication\(rq\&.
.sp
Домени POSIX доступні для усіх служб\&. Домени програм доступні лише з відповідача InfoPipe (див\&.
\fBsssd-ifp\fR(5)) і відповідача PAM\&.
.sp
ЗАУВАЖЕННЯ: належне тестування у поточній версії виконано лише для доменів application з
\(lqid_provider=ldap\(rq\&.
.sp
Щоб ознайомитися із простим способом налаштовування не\-POSIX доменів, будь ласка, ознайомтеся із розділом
\(lqДомени програм\(rq\&.
.sp
Типове значення: posix
.RE
.PP
min_id,max_id (ціле значення)
.RS 4
Обмеження UID і GID для домену\&. Якщо у домені міститься запис, що не відповідає цим обмеженням, його буде проігноровано\&.
.sp
Для користувачів зміна цього параметра вплине на основне обмеження GID\&. Запис користувача не буде повернуто до NSS, якщо UID або основний GID не належать вказаному діапазону\&. Записи користувачів, які не є учасниками основної групи і належать діапазону, буде виведено у звичайному режимі\&.
.sp
Ці обмеження на ідентифікатори стосуються і збереження записів до кешу, не лише повернення записів за назвою або ідентифікатором\&.
.sp
Типові значення: 1 для min_id, 0 (без обмежень) для max_id
.RE
.PP
enumerate (булеве значення)
.RS 4
Визначає, чи можна нумерувати домен, тобто, чи може домен створити список усіх користувачів і груп, які у ньому містяться\&. Зауважте, що вмикання нумерування не є обов\*(Aqязковим для показу вторинних груп\&. Цей параметр може мати такі значення:
.sp
TRUE = користувачі і групи нумеруються
.sp
FALSE = не використовувати нумерацію для цього домену
.sp
Типове значення: FALSE
.sp
Нумерування домену потребує від SSSD отримання і зберігання усіх записів користувачів і груп із віддаленого сервера\&.
.sp
Зауваження: вмикання нумерації помірно знизить швидкодію SSSD на час виконання нумерації\&. Нумерація може тривати до декількох хвилин після запуску SSSD\&. Протягом виконання нумерації окремі запити щодо даних буде надіслано безпосередньо до LDAP, хоча і з уповільненням через навантаження системи виконанням нумерації\&. Збереження великої кількості записів до кешу після завершення нумерації може також значно навантажити процесор, оскільки повторне визначення параметрів участі також іноді є складним завданням\&. Це може призвести до проблем із отриманням відповіді від процесу
\(lqsssd_be\(rq
або навіть перезапуску усього засобу стеження\&.
.sp
Під час першого виконання нумерації запити щодо повних списків користувачів та груп можуть не повертати жодних результатів, аж доки нумерацію не буде завершено\&.
.sp
Крім того, вмикання нумерації може збільшити час, потрібний для виявлення того, що мережеве з\(cqєднання розірвано, оскільки потрібне буде збільшення часу очікування для забезпечення успішного завершення пошуків нумерації\&. Щоб отримати додаткову інформацію, зверніться до сторінок довідника (man) відповідного використаного засобу обробки ідентифікаторів (id_provider)\&.
.sp
З вказаних вище причин не рекомендуємо вам вмикати нумерацію, особливо у об\(cqємних середовищах\&.
.RE
.PP
subdomain_enumerate (рядок)
.RS 4
Визначає, чи слід нумерувати усі автоматично виявлені надійні (довірені) домени\&. Підтримувані значення:
.PP
all
.RS 4
Усі виявлені надійні домени буде пронумеровано
.RE
.PP
none
.RS 4
Нумерація виявлених надійних доменів не виконуватиметься
.RE
.sp
Якщо потрібно, можна вказати список з однієї або декількох назв надійних доменів, для яких буде увімкнено нумерацію\&.
.sp
Типове значення: none
.RE
.PP
entry_cache_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких nss_sss вважатиме записи чинними, перш ніж надсилати повторний запит до сервера
.sp
Дані щодо часових позначок завершення строку дії записів кешу зберігаються як атрибути окремих об\(cqєктів у кеші\&. Тому зміна часу очікування на дані у кеші впливає лише на нові записи та записи, строк дії яких вичерпано\&. Для примусового оновлення записів, які вже було кешовано, вам слід запустити програму
\fBsss_cache\fR(8)\&.
.sp
Типове значення: 5400
.RE
.PP
entry_cache_user_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких nss_sss вважатиме записи користувачів чинними, перш ніж надсилати повторний запит до сервера
.sp
Типове значення: entry_cache_timeout
.RE
.PP
entry_cache_group_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких nss_sss вважатиме записи груп чинними, перш ніж надсилати повторний запит до сервера
.sp
Типове значення: entry_cache_timeout
.RE
.PP
entry_cache_netgroup_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких nss_sss вважатиме записи мережевих груп чинними, перш ніж надсилати повторний запит до сервера
.sp
Типове значення: entry_cache_timeout
.RE
.PP
entry_cache_service_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких nss_sss вважатиме записи служб чинними, перш ніж надсилати повторний запит до сервера
.sp
Типове значення: entry_cache_timeout
.RE
.PP
entry_cache_sudo_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких sudo вважатиме правила чинними, перш ніж надсилати повторний запит до сервера
.sp
Типове значення: entry_cache_timeout
.RE
.PP
entry_cache_autofs_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких служба autofs вважатиме карти автомонтування чинними, перш ніж надсилати повторний запит до сервера
.sp
Типове значення: entry_cache_timeout
.RE
.PP
entry_cache_ssh_host_timeout (ціле число)
.RS 4
Кількість секунд, протягом яких слід зберігати ключ ssh вузла після оновлення\&. Іншими словами, параметр визначає тривалість зберігання ключа вузла у кеші\&.
.sp
Типове значення: entry_cache_timeout
.RE
.PP
refresh_expired_interval (ціле число)
.RS 4
Визначає кількість секунд, протягом яких SSSD має очікувати до запуску завдання з оновлення у фоновому режимі записів кешу, строк дії яких вичерпано або майже вичерпано\&.
.sp
The background refresh will process users, groups and netgroups in the cache\&. For users who have performed the initgroups (get group membership for user, typically ran at login) operation in the past, both the user entry and the group membership are updated\&.
.sp
This option is automatically inherited for all trusted domains\&.
.sp
Варто визначити для цього параметра значення 3/4 * entry_cache_timeout\&.
.sp
Типове значення: 0 (вимкнено)
.RE
.PP
cache_credentials (булеве значення)
.RS 4
Визначає, чи слід також кешувати реєстраційні дані користувача у локальному кеші LDB
.sp
Реєстраційні дані користувача зберігаються у форматі хешу SHA512, а не у форматі звичайного тексту
.sp
Типове значення: FALSE
.RE
.PP
cache_credentials_minimal_first_factor_length (ціле число)
.RS 4
Якщо використано двофакторне розпізнавання (2FA) і реєстраційні дані мають зберігатися, це значення визначає мінімальну довжину першого фактора розпізнавання (довготривалого пароля), який має бути збережено у форматі контрольної суми SHA512 у кеші\&.
.sp
Таким чином забезпечується уникнення випадку, коли короткі PIN\-коди заснованої на PIN\-кодах схеми 2FA зберігаються у кеші, що робить їх простою мішенню атак із перебиранням паролів\&.
.sp
Типове значення: 8
.RE
.PP
account_cache_expiration (ціле число)
.RS 4
Кількість днів, протягом яких записи залишатимуться у кеші після успішного входу до системи до вилучення під час спорожнення кешу\&. 0 \(em не вилучати записи\&. Значення цього параметра має бути більшим або рівним значенню offline_credentials_expiration\&.
.sp
Типове значення: 0 (без обмежень)
.RE
.PP
pwd_expiration_warning (ціле число)
.RS 4
Показати попередження за вказану кількість днів перед завершенням дії пароля\&.
.sp
Якщо встановлено нульове значення, цей фільтр не застосовуватиметься, тобто якщо з сервера обробки надійде попередження щодо завершення строку дії, його буде автоматично показано\&.
.sp
Будь ласка, зауважте, що сервер обробки має надати дані щодо часу завершення дії пароля\&. Якщо ці дані не буде виявлено, sssd не зможе показати попередження\&. Крім того для цього сервера може бути вказано службу надання даних розпізнавання\&.
.sp
Типове значення: 7 (Kerberos), 0 (LDAP)
.RE
.PP
id_provider (рядок)
.RS 4
Засіб надання даних ідентифікації, який використовується для цього домену\&. Серед підтримуваних засобів такі:
.sp
\(Foproxy\(Fc: підтримка застарілого модуля надання даних NSS
.sp
\(lqfiles\(rq: засіб надання даних FILES\&. Докладніше про те, як працює віддзеркалення локальних користувачів і груп у SSSD, можна дізнатися зі сторінки підручника
\fBsssd-files\fR(5)\&.
.sp
\(lqldap\(rq: засіб LDAP\&. Докладніше про налаштовування LDAP можна дізнатися з довідки до
\fBsssd-ldap\fR(5)\&.
.sp
\(lqipa\(rq: засіб FreeIPA та керування профілями Red Hat Enterprise\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR()\&.
.sp
\(lqad\(rq: засіб Active Directory\&. Докладніші відомості щодо налаштовування Active Directory викладено у довіднику з
\fBsssd-ad\fR(5)\&.
.RE
.PP
use_fully_qualified_names (булеве значення)
.RS 4
Використовувати ім\(cqя та домен повністю (у форматі, визначеному full_name_format домену) як ім\(cqя користувача у системі, що повідомляється NSS\&.
.sp
Якщо встановлено значення TRUE, всі запити до цього домену мають використовувати повні назви\&. Наприклад, якщо використано домен LOCAL, який містить запис користувача \(Fotest\(Fc user,
\fBgetent passwd test\fR
не покаже користувача, а
\fBgetent passwd test@LOCAL\fR
покаже\&.
.sp
ЗАУВАЖЕННЯ: цей параметр не впливатиме на пошук у мережевих групах через тенденцію до включення до таких груп вкладених мережевих груп\&. Для мережевих груп, якщо задано неповну назву, буде виконано пошук у всіх доменах\&.
.sp
Типове значення: FALSE (TRUE, якщо використано default_domain_suffix)
.RE
.PP
ignore_group_members (булеве значення)
.RS 4
Не повертати записи учасників груп для пошуків груп\&.
.sp
Якщо встановлено значення TRUE, сервер LDAP не запитуватиме дані щодо атрибутів участі у групах, а списки учасників груп не повертаються під час обробки запитів щодо пошуку груп, зокрема
\fBgetgrnam\fR(3)
або
\fBgetgrgid\fR(3)\&. Отже,
\(lqgetent group $groupname\(rq
поверне запитану групу так, наче вона була порожня\&.
.sp
Вмикання цього параметра може також значно пришвидшити перевірки засобу надання доступу для участі у групі, особливо для груп, у яких багато учасників\&.
.sp
Типове значення: FALSE
.RE
.PP
auth_provider (рядок)
.RS 4
Служба розпізнавання, яку використано для цього домену\&. Серед підтримуваних служб розпізнавання:
.sp
\(lqldap\(rq
\(em вбудоване розпізнавання LDAP\&. Докладніші відомості щодо налаштовування LDAP викладено у довіднику з
\fBsssd-ldap\fR(5)\&.
.sp
\(lqkrb5\(rq
\(em вбудоване розпізнавання Kerberos\&. Докладніші відомості щодо налаштовування Kerberos викладено у довіднику з
\fBsssd-krb5\fR()\&.
.sp
\(lqipa\(rq: засіб FreeIPA та керування профілями Red Hat Enterprise\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR()\&.
.sp
\(lqad\(rq: засіб Active Directory\&. Докладніші відомості щодо налаштовування Active Directory викладено у довіднику з
\fBsssd-ad\fR(5)\&.
.sp
\(lqproxy\(rq
\(em трансльоване розпізнавання у іншій системі PAM\&.
.sp
\(lqnone\(rq
\(em вимкнути розпізнавання повністю\&.
.sp
Типове значення: буде використано
\(lqid_provider\(rq, якщо цей спосіб встановлено і можлива обробка запитів щодо розпізнавання\&.
.RE
.PP
access_provider (рядок)
.RS 4
Програма керування доступом для домену\&. Передбачено дві вбудованих програми керування доступом (окрім всіх встановлених додаткових серверів)\&. Вбудованими програмами є:
.sp
\(lqpermit\(rq
дозволяти доступ завжди\&. Єдиний дозволений засіб доступу для локального домену\&.
.sp
\(lqdeny\(rq
\(em завжди забороняти доступ\&.
.sp
\(lqldap\(rq
\(em вбудоване розпізнавання LDAP\&. Докладніші відомості щодо налаштовування LDAP викладено у довіднику з
\fBsssd-ldap\fR(5)\&.
.sp
\(lqipa\(rq: засіб FreeIPA та керування профілями Red Hat Enterprise\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR()\&.
.sp
\(lqad\(rq: засіб Active Directory\&. Докладніші відомості щодо налаштовування Active Directory викладено у довіднику з
\fBsssd-ad\fR(5)\&.
.sp
\(lqsimple\(rq
\(em керування доступом на основі списків дозволу або заборони\&. Докладніші відомості щодо налаштовування модуля доступу simple можна знайти у довідці до
\fBsssd-simple\fR(5)\&.
.sp
\(lqkrb5\(rq
\(em керування доступом на основі \&.k5login\&. Докладніші відомості щодо налаштовування Kerberos викладено у довіднику з
\fBsssd-krb5\fR()\&.
.sp
\(lqproxy\(rq
\(em для трансляції керування доступом до іншого модуля PAM\&.
.sp
Типове значення:
\(lqpermit\(rq
.RE
.PP
chpass_provider (рядок)
.RS 4
Система, яка має обробляти дії зі зміни паролів для домену\&. Передбачено підтримку таких систем зміни паролів:
.sp
\(lqldap\(rq
\(em змінити пароль, що зберігається на сервері LDAP\&. Докладніші відомості щодо налаштовування LDAP викладено у довіднику з
\fBsssd-ldap\fR(5)\&.
.sp
\(lqkrb5\(rq
\(em змінити пароль Kerberos\&. Докладніші відомості щодо налаштовування Kerberos викладено у довіднику з
\fBsssd-krb5\fR()\&.
.sp
\(lqipa\(rq: засіб FreeIPA та керування профілями Red Hat Enterprise\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR()\&.
.sp
\(lqad\(rq: засіб Active Directory\&. Докладніші відомості щодо налаштовування Active Directory викладено у довіднику з
\fBsssd-ad\fR(5)\&.
.sp
\(lqproxy\(rq
\(em трансльована зміна пароля у іншій системі PAM\&.
.sp
\(lqnone\(rq
\(em явно вимкнути можливість зміни пароля\&.
.sp
Типове значення: використовується \(Foauth_provider\(Fc, якщо встановлено значення цього параметра і якщо система здатна обробляти запити щодо паролів\&.
.RE
.PP
sudo_provider (рядок)
.RS 4
Служба SUDO, яку використано для цього домену\&. Серед підтримуваних служб SUDO:
.sp
\(lqldap\(rq
для правил, що зберігаються у LDAP\&. Докладніше про налаштовування LDAP можна дізнатися з довідки до
\fBsssd-ldap\fR(5)\&.
.sp
\(lqipa\(rq
\(em те саме, що і
\(lqldap\(rq, але з типовими параметрами IPA\&.
.sp
\(lqad\(rq
\(em те саме, що і
\(lqldap\(rq, але з типовими параметрами AD\&.
.sp
\(lqnone\(rq
явним чином вимикає SUDO\&.
.sp
Типове значення: використовується значення
\(lqid_provider\(rq, якщо його встановлено\&.
.sp
З докладними настановами щодо налаштовування sudo_provider можна ознайомитися за допомогою сторінки підручника (man)
\fBsssd-sudo\fR(5)\&. Передбачено доволі багато параметрів налаштовування, якими можна скористатися для коригування поведінки програми\&. Докладніший опис можна знайти у розділах щодо \(Foldap_sudo_*\(Fc" у підручнику з
\fBsssd-ldap\fR(5)\&.
.sp
\fIЗауваження:\fR
правила sudo періодично отримуються у фоновому режимі, якщо постачальник даних sudo не вимкнено явним чином\&. Встановіть значення
\fIsudo_provider = None\fR, щоб вимкнути усі дії, пов\*(Aqязані із sudo у SSSD, якщо ви взагалі не хочете використовувати sudo у SSSD\&.
.RE
.PP
selinux_provider (рядок)
.RS 4
Засіб, який має відповідати за завантаження параметрів SELinux\&. Зауважте, що цей засіб буде викликано одразу після завершення роботи служби надання доступу\&. Передбачено підтримку таких засобів надання даних SELinux:
.sp
\(lqipa\(rq
для завантаження параметрів selinux з сервера IPA\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR(5)\&.
.sp
\(lqnone\(rq
явним чином забороняє отримання даних щодо параметрів SELinux\&.
.sp
Типове значення: буде використано
\(lqid_provider\(rq, якщо цей спосіб встановлено і можлива обробка запитів щодо завантаження SELinux\&.
.RE
.PP
subdomains_provider (рядок)
.RS 4
Засіб надання даних, який має обробляти отримання даних піддоменів\&. Це значення має завжди збігатися зі значенням id_provider\&. Передбачено підтримку таких засобів надання даних піддоменів:
.sp
\(lqipa\(rq
для завантаження списку піддоменів з сервера IPA\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR(5)\&.
.sp
\(Foad\(Fc, з якої слід завантажувати список піддоменів з сервера Active Directory\&. Див\&.
\fBsssd-ad\fR(5), щоб дізнатися більше про налаштовування засобу надання даних AD\&.
.sp
\(lqnone\(rq
забороняє ячним чином отримання даних піддоменів\&.
.sp
Типове значення: використовується значення
\(lqid_provider\(rq, якщо його встановлено\&.
.RE
.PP
session_provider (рядок)
.RS 4
Постачальник даних, який налаштовує завдання, пов\*(Aqязані із сеансами користувачів, і керує ними\&. Єдиним завданням сеансів користувача у поточній версії є інтеграція із Fleet Commander, який працює лише з IPA\&. Підтримувані постачальники даних сеансів:
.sp
\(lqipa\(rq, щоб дозволити пов\*(Aqязані із сеансами користувачів завдання\&.
.sp
\(lqnone\(rq
\(em не виконувати жодних пов\*(Aqязаних із сеансами користувачів завдань\&.
.sp
Типове значення: використовується значення
\(lqid_provider\(rq, якщо його встановлено і дозволено виконувати пов\*(Aqязані із сеансами завдання\&.
.sp
\fIЗауваження:\fR
щоб ця можливість працювала як слід, SSSD має бути запущено від імені користувача root, а не якогось іншого непривілейованого користувача\&.
.RE
.PP
autofs_provider (рядок)
.RS 4
Служба autofs, яку використано для цього домену\&. Серед підтримуваних служб autofs:
.sp
\(lqldap\(rq
\(em завантажити карти, що зберігаються у LDAP\&. Докладніше про налаштовування LDAP можна дізнатися з довідки до
\fBsssd-ldap\fR(5)\&.
.sp
\(lqipa\(rq
\(em завантажити карти, що зберігається на сервері IPA\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR()\&.
.sp
\(lqad\(rq
\(em завантажити карти, що зберігаються на сервері AD\&. Див\&.
\fBsssd-ad\fR(5), щоб дізнатися більше про налаштовування засобу надання даних AD\&.
.sp
\(lqnone\(rq
вимикає autofs повністю\&.
.sp
Типове значення: використовується значення
\(lqid_provider\(rq, якщо його встановлено\&.
.RE
.PP
hostid_provider (рядок)
.RS 4
Засіб надання даних, який використовується для отримання даних щодо профілю вузла\&. Серед підтримуваних засобів надання hostid:
.sp
\(lqipa\(rq
\(em завантажити профіль системи, що зберігається на сервері IPA\&. Докладніші відомості щодо налаштовування IPA викладено у довіднику з
\fBsssd-ipa\fR()\&.
.sp
\(lqnone\(rq
вимикає hostid повністю\&.
.sp
Типове значення: використовується значення
\(lqid_provider\(rq, якщо його встановлено\&.
.RE
.PP
re_expression (рядок)
.RS 4
Формальний вираз для цього домену, який описує спосіб поділи рядка, що містить ім\(cqя користувача та назву домену на ці компоненти\&. \(FoДомен\(Fc може відповідати назві домену налаштувань SSSD або, у випадку піддоменів довіри IPA та доменів Active Directory, простій назві (NetBIOS) домену\&.
.sp
Типовий для засобів надання AD і IPA:
\(lq(((?P<domain>[^\e\e]+)\e\e(?P<name>\&.+$))|((?P<name>[^@]+)@(?P<domain>\&.+$))|(^(?P<name>[^@\e\e]+)$))\(rq
За його допомогою можна визначати три різні стилі запису імен користувачів:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
користувач
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
користувач@назва\&.домену
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
домен\eкористувач
.RE
.sp
Перші два стилі відповідають загальним типовим стилям, а третій введено для того, щоб полегшити інтеграцію користувачів з доменів Windows\&.
.sp
Типове значення:
\(lq(?P<name>[^@]+)@?(?P<domain>[^@]*$)\(rq, можна висловити так: іменем користувача є все до символу \(Fo@\(Fc, назвою домену \(em все після цього символу\&.
.sp
Зауваження: у деяких групах Active Directory, типово, тих, які використовуються для MS Exchange, назви містять символ
\(lq@\(rq\&. Такі назви конфліктують із типовим значенням re_expression для надавачів даних AD та IPA\&. Щоб забезпечити підтримку таких груп, варто змінити значення re_expression на таке:
\(lq((?P<name>\&.+)@(?P<domain>[^@]+$))\(rq\&.
.RE
.PP
full_name_format (рядок)
.RS 4
Сумісний з
\fBprintf\fR(3)
формат, який описує спосіб створення повного імені на основі імені користувача та компонентів назви домену\&.
.sp
Передбачено використання таких замінників:
.PP
%1$s
.RS 4
ім\(cqя користувача
.RE
.PP
%2$s
.RS 4
назва домену у форматі, вказаному у файлі налаштувань SSSD\&.
.RE
.PP
%3$s
.RS 4
проста назва домену\&. Здебільшого використовується для доменів Active Directory, налаштованих та автоматично виявлених за зв\(cqязками довіри IPA\&.
.RE
.sp
Типове значення:
\(lq%1$s@%2$s\(rq\&.
.RE
.PP
lookup_family_order (рядок)
.RS 4
Надає можливість вибрати бажане сімейство адрес, яке слід використовувати під час виконання пошуків у DNS\&.
.sp
Передбачено підтримку таких значень:
.sp
ipv4_first: спробувати визначити адресу у форматі IPv4, у разі невдачі спробувати формат IPv6
.sp
ipv4_only: намагатися визначити назви вузлів лише у форматі адрес IPv4\&.
.sp
ipv6_first: спробувати визначити адресу у форматі IPv6, у разі невдачі спробувати формат IPv4
.sp
ipv6_only: намагатися визначити назви вузлів лише у форматі адрес IPv6\&.
.sp
Типове значення: ipv4_first
.RE
.PP
dns_resolver_timeout (ціле число)
.RS 4
Визначає кількість часу (у секундах) очікування відповіді від внутрішньої служби перемикання на резервний ресурс, перш ніж службу буде визначено недоступним\&. Якщо час очікування буде перевищено, домен продовжуватиме роботу у автономному режимі\&.
.sp
Будь ласка, ознайомтеся із розділом
\(lqРЕЗЕРВ\(rq, щоб дізнатися більше про розв\*(Aqязування питань, пов\*(Aqязаних із службами\&.
.sp
Типове значення: 6
.RE
.PP
dns_discovery_domain (рядок)
.RS 4
Якщо у модулі обробки використовується визначення служб, вказує доменну частину запиту визначення служб DNS\&.
.sp
Типова поведінка: використовувати назву домену з назви вузла комп\(cqютера\&.
.RE
.PP
override_gid (ціле число)
.RS 4
Замірити значення основного GID на вказане\&.
.RE
.PP
case_sensitive (рядок)
.RS 4
Враховувати регістр записів імен користувачів та назв груп\&. Можливі значення параметра:
.PP
True
.RS 4
Враховується регістр\&. Це значення є некоректним для засобу надання даних AD\&.
.RE
.PP
False
.RS 4
Без врахування регістру\&.
.RE
.PP
Preserving
.RS 4
Те саме, що і False (без врахування регістру символів), але без переведення у нижній регістр імен у результатах дій NSS\&. Зауважте, що альтернативні імена (у випадку служб також назви протоколів) у виведених даних все одно буде переведено у нижній регістр\&.
.RE
.sp
Типове значення: True (False для засобу надання даних AD)
.RE
.PP
subdomain_inherit (рядок)
.RS 4
Визначає список параметрів налаштування, які слід успадковувати для піддомену\&. Будь ласка, зауважте, що успадковуватимуться лише вказані параметри\&. У поточній версії передбачено можливість успадковування таких параметрів:
.sp
ignore_group_members
.sp
ldap_purge_cache_timeout
.sp
ldap_use_tokengroups
.sp
ldap_user_principal
.sp
ldap_krb5_keytab (значення krb5_keytab буде використано, якщо ldap_krb5_keytab не встановлено явним чином)
.sp
Приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
subdomain_inherit = ldap_purge_cache_timeout
                            
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: none
.sp
Зауваження: цей параметр працює лише для засобів надання даних IPA і AD\&.
.RE
.PP
subdomain_homedir (рядок)
.RS 4
Використовувати вказаний домашній каталог як типовий для всіх піддоменів у цьому домені у межах довіри AD IPA\&. Дані щодо можливих значень наведено у описі параметра
\fIoverride_homedir\fR\&. Крім того, розгортання можна використовувати лише з
\fIsubdomain_homedir\fR\&.
.PP
%F
.RS 4
спрощена (NetBIOS) назва піддомену\&.
.RE
.sp
Це значення може бути перевизначено параметром
\fIoverride_homedir\fR\&.
.sp
Типове значення:
/home/%d/%u
.RE
.PP
realmd_tags (рядок)
.RS 4
Різноманітні теґи, що зберігаються службою налаштовування realmd для цього домену\&.
.RE
.PP
cached_auth_timeout (ціле число)
.RS 4
Визначає час у секундах з моменту останнього успішного розпізнавання у мережі, для якого користувача буде розпізнано за допомогою кешованих реєстраційних даних, доки SSSD перебуває у режимі \(Foу мережі\(Fc\&. Якщо реєстраційні дані є помилковими, SSSD повертається до інтерактивного розпізнавання\&.
.sp
Значення цього параметра успадковується усіма довіреними доменами\&. У поточній версії не передбачено можливості встановлювати окремі різні значення для різних довірених доменів\&.
.sp
Спеціальне значення 0 означає, що цю можливість вимкнено\&.
.sp
Будь ласка, зауважте, що якщо
\(lqcached_auth_timeout\(rq
має більше значення за
\(lqpam_id_timeout\(rq, модуль може бути викликано для обробки
\(lqinitgroups\(rq\&.
.sp
Типове значення: 0
.RE
.PP
auto_private_groups (рядок)
.RS 4
Цей параметр приймає будь\-яке з таких трьох доступних значень:
.PP
true
.RS 4
Безумовно створює приватну групу користувача на основі номера UID користувача\&. У цьому випадку номер GID буде проігноровано\&.
.sp
Зауваження: оскільки номер GID і приватна група користувача успадковуються з номера UID, підтримки декількох записів із однаковим номером UID або GID у цьому параметрі не передбачено\&. Іншими словами, вмикання цього параметра примусово встановлює унікальність записів у просторі ідентифікаторів\&.
.RE
.PP
false
.RS 4
Завжди використовувати номер основної GID користувача\&. Номер GID має вказувати на об\*(Aqєкт групи у базі даних LDAP\&.
.RE
.PP
hybrid
.RS 4
A primary group is autogenerated for user entries whose UID and GID numbers have the same value and at the same time the GID number does not correspond to a real group object in LDAP\&. If the values are the same, but the primary GID in the user entry is also used by a group object, the primary GID of the user resolves to that group object\&.
.sp
Якщо UID і GID користувача є різними, значення GID має відповідати запису групи, інакше надійне визначення GID буде просто неможливим\&.
.sp
Ця можливість є корисною для середовищ, де бажаним є усування потреби у супроводі окремих об\*(Aqєктів груп для користувачів у приватних групах, але зі збереженням наявних приватних груп для користувачів\&.
.RE
.sp
Для піддоменів типовим значенням є False для тих піддоменів, які пов\*(Aqязано із ідентифікаторами POSIX, і True для тих піддоменів, для яких використовується автоматична прив\*(Aqязка до ідентифікаторів\&.
.sp
Значення параметра auto_private_groups може встановлюватися або на рівні окремих піддоменів у підрозділі, приклад:
.sp
.if n \{\
.RS 4
.\}
.nf
[domain/forest\&.domain/sub\&.domain]
auto_private_groups = false
.fi
.if n \{\
.RE
.\}
.sp
або на загальному рівні для усіх піддоменів у основному розділі домену за допомогою параметра subdomain_inherit:
.sp
.if n \{\
.RS 4
.\}
.nf
[domain/forest\&.domain]
subdomain_inherit = auto_private_groups
auto_private_groups = false
.fi
.if n \{\
.RE
.\}
.sp
.RE
.PP
Параметри, які є чинними для доменів проксі\&.
.PP
proxy_pam_target (рядок)
.RS 4
Комп\(cqютер, для якого виконує проксі\-сервер PAM\&.
.sp
Типове значення: типово не встановлено, вам слід скористатися вже створеними налаштуваннями pam або створити нові і тут додати назву служби\&.
.RE
.PP
proxy_lib_name (рядок)
.RS 4
Назва бібліотеки NSS для використання у доменах з проксі\-серверами\&. Функції NSS шукаються у бібліотеці у форматі _nss_$(назва_бібліотеки)_$(функція), наприклад _nss_files_getpwent\&.
.RE
.PP
proxy_fast_alias (булеве значення)
.RS 4
Під час пошуку запису користувача чи групи за назвою у системі надання даних переадресації виконується вторинний пошук за ідентифікатором з метою визначення \(Foканонічної\(Fc форми назви, якщо результат знайдено за альтернативною назвою (псевдонімом)\&. Встановлення для цього параметра значення \(Fotrue\(Fc призведе до того, що SSSD виконуватиме пошук ідентифікатора у кеші, щоб пришвидшити надання результатів\&.
.sp
Типове значення: false
.RE
.PP
proxy_max_children (ціле число)
.RS 4
Цей параметр визначає кількість попередньо розгалужених дочірніх проксі\&. Він корисний для високонавантажених середовищ SSSD, де sssd може вичерпати кількість доступних дочірніх слотів, що може спричинити деякі вади через використання черги запитів\&.
.sp
Типове значення: 10
.RE
.SS "Домени програм (application)"
.PP
SSSD, з його інтерфейсом D\-Bus (див\&.
\fBsssd-ifp\fR(5)) є привабливим для програм як шлюз до каталогу LDAP, де зберігаються дані користувачів і груп\&. Втім, на відміну від традиційного формату роботи SSSD, де усі користувачі і групи або мають атрибути POSIX, або ці атрибути може бути успадковано з SID Windows, у багатьох випадках користувачі і групи у сценарії підтримки роботи програм не мають атрибутів POSIX\&. Замість визначення розділу
\(lq[domain/\fIНАЗВА\fR]\(rq
адміністратор може визначити розділ
\(lq[application/\fIНАЗВА\fR]\(rq, який на внутрішньому рівні представляє домен типу
\(lqapplication\(rq, який може успадковувати параметр з традиційного домену SSSD\&.
.PP
Будь ласка, зауважте, що домен програм має так само явним чином увімкнено у параметрі
\(lqdomains\(rq, отже порядок пошуку між доменом програм і його доменом\-близнюком у POSIX має бути встановлено належним чином\&.
.PP
\fBПараметри доменів програм\fR
.PP
inherit_from (рядок)
.RS 4
Домен типу POSIX SSSD, з якого домен програм успадковує усі параметри\&. Далі, домен програм поже додавати власні параметри до параметрів програми, які розширюють або перевизначають параметри домену\-\(lqблизнюка\(rq\&.
.sp
Типове значення: не встановлено
.RE
.PP
У наведеному нижче прикладі проілюстровано використання домену програм\&. У цій конфігурації домен POSIX з\*(Aqєднано із сервером LDAP, він використовується операційною системою через відповідач NSS\&. Крім того, домен програм також надсилає запит щодо атрибута telephoneNumber, зберігає його як атрибут phone у кеші і робить атрибут phone доступним через інтерфейс D\-Bus\&.
.sp
.if n \{\
.RS 4
.\}
.nf
[sssd]
domains = appdom, posixdom

[ifp]
user_attributes = +phone

[domain/posixdom]
id_provider = ldap
ldap_uri = ldap://ldap\&.example\&.com
ldap_search_base = dc=example,dc=com

[application/appdom]
inherit_from = posixdom
ldap_user_extra_attrs = phone:telephoneNumber
.fi
.if n \{\
.RE
.\}
.SH "РОЗДІЛ ДОВІРЕНИХ ДОМЕНІВ"
.PP
Деякі параметри, які використовуються у розділі домену, можна також використовувати у розділі довіреного домену, тобто у розділі, який називається
\(lq[domain/\fIНАЗВА_ДОМЕНУ\fR/\fIНАЗВА_ДОВІРЕНОГО_ДОМЕНУ\fR]\(rq\&. Де НАЗВА_ДОМЕНУ є справжнім базовим доменом для долучення\&. Приклади наведено нижче\&. У поточній версії підтримуваними параметрами у розділі довіреного домену є такі параметри:
.PP
ldap_search_base,
.PP
ldap_user_search_base,
.PP
ldap_group_search_base,
.PP
ldap_netgroup_search_base,
.PP
ldap_service_search_base,
.PP
ldap_sasl_mech,
.PP
ad_server,
.PP
ad_backup_server,
.PP
ad_site,
.PP
use_fully_qualified_names
.PP
Докладніший опис цих параметрів можна знайти у окремих описах на сторінці підручника\&.
.SH "РОЗДІЛ ПРИВ\*(AQЯЗКИ СЕРТИФІКАТІВ"
.PP
Щоб уможливити розпізнавання за смарткартками та сертифікатами, SSSD повинна мати можливість пов\*(Aqязувати сертифікати із записами користувачів\&. Забезпечити таку можливість можна додаванням повного сертифіката до об\*(Aqєкта LDAP користувача або локальним перевизначенням\&. Хоча використання повного сертифіката є обов\*(Aqязковим для використання можливості розпізнавання за смарткарткою у (див\&.
\fBsss_ssh_authorizedkeys\fR(8), щоб дізнатися більше), додавання таких сертифікатів може бути марудною або навіть неможливою справою для загального випадку, коли локальні служби використовують для розпізнавання PAM\&.
.PP
Для додавання гнучкості прив\*(Aqязкам у SSSD додано правила прив\*(Aqязки і встановлення відповідності (докладніше про це у розділі
\fBsss-certmap\fR(5))\&.
.PP
Правила пов\*(Aqязування та відповідності можна додати до налаштувань SSSD у окремий розділ із назвою, подібною до
\(lq[certmap/\fIНАЗВА_ДОМЕНУ\fR/\fIНАЗВА_ПРАВИЛА\fR]\(rq\&. У цьому розділі можна використовувати такі параметри:
.PP
matchrule (рядок)
.RS 4
Буде виконано обробку лише тих сертифікатів зі смарткартки, які відповідають цьому правилу\&. Усі інші сертифікати буде проігноровано\&.
.sp
Типове значення: KRB5:<EKU>clientAuth, тобто лише сертифікати, у яких Extended Key Usage (розширене використання ключа) дорівнює
\(lqclientAuth\(rq
.RE
.PP
maprule (рядок)
.RS 4
Визначає спосіб пошуку користувача для вказаного сертифіката\&.
.sp
Типове значення:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LDAP:(userCertificate;binary={cert!bin}) для заснованих на LDAP надавачів даних, зокрема
\(lqldap\(rq,
\(lqAD\(rq
та
\(lqipa\(rq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
RULE_NAME для надавача даних
\(lqfiles\(rq, який намагається знайти запис користувача і такою самою назвою\&.
.RE
.sp
.RE
.PP
domains (рядок)
.RS 4
Список відокремлених комами назв доменів, до яких слід застосовувати правило\&. Типово, правило стосуватиметься лише домену, який налаштовано у sssd\&.conf\&. Якщо для надавача даних передбачено підтримку піддоменів, цей параметр можна використати і для додавання правила до піддоменів\&.
.sp
Типове значення: домен, який налаштовано у sssd\&.conf
.RE
.PP
priority (ціле число)
.RS 4
Ціле невід\*(Aqємне значення, яке визначає пріоритетність правила\&. Чим більшим є значення, тим нижчою є пріоритетність\&.
\(lq0\(rq
\(em найвища пріоритетність, а
\(lq4294967295\(rq
\(em найнижча\&.
.sp
Типове значення: найнижча пріоритетність
.RE
.PP
Щоб спростити налаштовування із зменшити кількість параметрів налаштовування, у надавачі даних
\(lqfiles\(rq
передбачено декілька спеціальних властивостей:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
якщо не встановлено maprule, припускається, що значенням RULE_NAME є назва відповідного облікового запису користувача
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
якщо maprule використовує обидва, назву облікового запису окремого користувача або шаблон, подібний до
\(lq{назва_об\*(Aqєкта_rfc822\&.коротка_назва}\(rq, слід брати у дужки, наприклад
\(lq(користувач)\(rq
або
\(lq({назва_об\*(Aqєкта_rfc822\&.коротка_назва})\(rq
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
параметр
\(lqdomains\(rq
буде проігноровано
.RE
.sp
.SH "РОЗДІЛ НАЛАШТОВУВАННЯ ЗАПИТІВ"
.PP
Якщо існує спеціальний файл (/var/lib/sss/pubconf/pam_preauth_available), модуль PAM SSSD pam_sss надсилатиме запит до SSSD для визначення того, які методи розпізнавання доступні для користувача, який намагається увійти до системи\&. На основі отриманих результатів pam_sss надсилатиме запит до користувача щодо відповідних реєстраційних даних\&.
.PP
With the growing number of authentication methods and the possibility that there are multiple ones for a single user the heuristic used by pam_sss to select the prompting might not be suitable for all use cases\&. The following options should provide a better flexibility here\&.
.PP
Each supported authentication method has its own configuration subsection under
\(lq[prompting/\&.\&.\&.]\(rq\&. Currently there are:
.PP
[prompting/password]
.RS 4
для налаштовування запиту щодо пароля; дозволені параметри:
.PP
password_prompt
.RS 4
для зміни рядка запиту пароля
.RE
.sp
.RE
.PP
[prompting/2fa]
.RS 4
для налаштовування запиту щодо двофакторного розпізнавання; дозволені параметри:
.PP
first_prompt
.RS 4
для зміни рядка запиту для першого фактора
.RE
.PP
second_prompt
.RS 4
для зміни рядка запиту для другого фактора
.RE
.PP
single_prompt
.RS 4
boolean value, if True there will be only a single prompt using the value of first_prompt where it is expected that both factors are entered as a single string
.RE
.sp
.RE
.PP
It is possible to add a subsection for specific PAM services, e\&.g\&.
\(lq[prompting/password/sshd]\(rq
to individual change the prompting for this service\&.
.SH "ПРИКЛАДИ"
.PP
1\&. Нижче наведено приклад типових налаштувань SSSD\&. Налаштування самого домену не наведено, \(em щоб дізнатися більше про неї, ознайомтеся з документацією щодо налаштовування доменів\&.
.sp
.if n \{\
.RS 4
.\}
.nf
[sssd]
domains = LDAP
services = nss, pam
config_file_version = 2

[nss]
filter_groups = root
filter_users = root

[pam]

[domain/LDAP]
id_provider = ldap
ldap_uri = ldap://ldap\&.example\&.com
ldap_search_base = dc=example,dc=com

auth_provider = krb5
krb5_server = kerberos\&.example\&.com
krb5_realm = EXAMPLE\&.COM
cache_credentials = true

min_id = 10000
max_id = 20000
enumerate = False
.fi
.if n \{\
.RE
.\}
.PP
2\&. У наведеному нижче прикладі показано налаштування довіри AD у IPA, де ліс AD складається з двох доменів у структурі батьківський\-дочірній\&. Нехай домен IPA (ipa\&.com) має стосунки довіри з доменом AD (ad\&.com)\&. ad\&.com має дочірній домен (child\&.ad\&.com)\&. Щоб увімкнути скорочені назви у дочірньому домені, слід скористатися наведеними нижче налаштуваннями\&.
.sp
.if n \{\
.RS 4
.\}
.nf
[domain/ipa\&.com/child\&.ad\&.com]
use_fully_qualified_names = false
.fi
.if n \{\
.RE
.\}
.PP
3\&. У наведеному нижче прикладі показано налаштування для двох правил пов\*(Aqязування сертифікатів\&. Перше є чинним для налаштованого домену
\(lqmy\&.domain\(rq
і, додатково, для піддоменів
\(lqyour\&.domain\(rq
і використовує повний сертифікат у фільтрі пошуку\&. Другий приклад є чинним для домену
\(lqfiles\(rq, де припускається, що для цього домену використовується засіб надання даних файлів, і містить правило відповідності для локального користувача
\(lqmyname\(rq\&.
.sp
.if n \{\
.RS 4
.\}
.nf
[certmap/my\&.domain/rule_name]
matchrule = <ISSUER>^CN=My\-CA,DC=MY,DC=DOMAIN$
maprule = (userCertificate;binary={cert!bin})
domains = my\&.domain, your\&.domain
priority = 10

[certmap/files/myname]
matchrule = <ISSUER>^CN=My\-CA,DC=MY,DC=DOMAIN$<SUBJECT>^CN=User\&.Name,DC=MY,DC=DOMAIN$
.fi
.if n \{\
.RE
.\}
.sp
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
