'\" t
.\"     Title: sssd-ifp
.\"    Author: Основна гілка розробки SSSD \(em https://pagure.io/SSSD/sssd/
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/09/2020
.\"    Manual: Формати файлів та правила
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-IFP" "5" "12/09/2020" "SSSD" "Формати файлів та правила"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-ifp \- Відповідач InfoPipe SSSD
.SH "ОПИС"
.PP
На цій сторінці довідника описано налаштування засобу надання відповідей InfoPipe для
\fBsssd\fR(8)\&. Щоб дізнатися більше про синтаксис налаштування, зверніться до розділу \(FoФОРМАТ ФАЙЛІВ\(Fc сторінки довідника
\fBsssd.conf\fR(5)\&.
.PP
Відповідач InfoPipe забезпечує роботу відкритого інтерфейсу D\-Bus над системним каналом повідомлень\&. За допомогою цього інтерфейсу користувачі можуть надсилати загальносистемним каналом повідомлень запити щодо інформації про віддалених користувачів і групи\&.
.SH "ПАРАМЕТРИ НАЛАШТУВАННЯ"
.PP
Цими параметрами можна скористатися для налаштовування відповідача InfoPipe\&.
.PP
allowed_uids (рядок)
.RS 4
Визначає список значень UID або імен користувачів, відокремлених комами\&. Користувачам з цього списку буде дозволено доступ до відповідача InfoPipe\&. UID за іменами користувачів визначатимуться під час запуску\&.
.sp
Типове значення: 0 (доступ до відповідача InfoPipe має лише адміністративний користувач (root))
.sp
Будь ласка, зауважте, що хоча типово використовується UID 0, значення UID буде перевизначено на основі цього параметра\&. Якщо ви хочете надати адміністративному користувачеві (root) доступ до відповідача InfoPipe, що може бути типовим варіантом, вам слід додати до списку UID з правами доступу запис 0\&.
.RE
.PP
user_attributes (рядок)
.RS 4
Визначає список атрибутів з \(Foбілого\(Fc або \(Foчорного\(Fc списків, відокремлених комами\&.
.sp
Типово, відповідач InfoPipe надає дані лише щодо типового набору атрибутів POSIX\&. Цей набір є тим самим, який повертає програма
\fBgetpwnam\fR(3), його елементи:
.PP
name
.RS 4
реєстраційне ім\(cqя користувача
.RE
.PP
uidNumber
.RS 4
ідентифікатор користувача
.RE
.PP
gidNumber
.RS 4
ідентифікатор основної групи
.RE
.PP
gecos
.RS 4
дані щодо користувача, типово ім\(cqя повністю
.RE
.PP
homeDirectory
.RS 4
домашній каталог
.RE
.PP
loginShell
.RS 4
командна оболонка користувача
.RE
.sp
Ви можете додати інший атрибут до цього набору за допомогою параметра \(Fo+назва_атрибута\(Fc або явним чином виключити атрибут за допомогою параметра \(Fo\-назва_атрибута\(Fc\&. Наприклад, щоб дозволити \(FotelephoneNumber\(Fc, але заборонити \(FologinShell\(Fc, вам слід скористатися такими налаштуваннями:
.sp
.if n \{\
.RS 4
.\}
.nf
user_attributes = +telephoneNumber, \-loginShell
                        
.fi
.if n \{\
.RE
.\}
.sp
Типове значення: не встановлено\&. Дозволено лише типовий набір атрибутів POSIX\&.
.RE
.PP
wildcard_limit (ціле число)
.RS 4
Визначає верхню межу для кількості записів, які отримуватимуться під час пошуку з використанням символів\-замінників, які перевизначають обмеження, яке накладається функцією виклику\&.
.sp
Типове значення: 0 (дозволити встановлювати верхнє обмеження функції виклику)
.RE
.SH "ТАКОЖ ПЕРЕГЛЯНЬТЕ"
.PP
\fBsssd\fR(8),
\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd-simple\fR(5),
\fBsssd-ipa\fR(5),
\fBsssd-ad\fR(5),
\fBsssd-files\fR(5),
\fBsssd-sudo\fR(5),
\fBsssd-session-recording\fR(5),
\fBsss_cache\fR(8),
\fBsss_debuglevel\fR(8),
\fBsss_obfuscate\fR(8),
\fBsss_seed\fR(8),
\fBsssd_krb5_locator_plugin\fR(8),
\fBsss_ssh_authorizedkeys\fR(8), \fBsss_ssh_knownhostsproxy\fR(8),
\fBsssd-ifp\fR(5),
\fBpam_sss\fR(8)\&.
\fBsss_rpcidmapd\fR(5)
.SH "AUTHORS"
.PP
\fBОсновна гілка розробки SSSD \(em
https://pagure\&.io/SSSD/sssd/\fR
